import type { AppLanguage } from './i18n';

export interface GuideSection {
  title: string;
  desc?: string;
  items: GuideItem[];
}

export interface GuideItem {
  iconKey: string;
  title: string;
  steps?: string[];
  desc?: string;
}

export interface GuideFlowStep {
  num: string;
  title: string;
  desc: string;
}

export interface GuideContent {
  naverSection: {
    title: string;
    desc: string;
    guideTitle: string;
    guideSteps: string;
    linkText: string;
    notice: string;
  };
  flowTitle: string;
  flowDesc: string;
  flowSteps: GuideFlowStep[];
  featuresTitle: string;
  featuresDesc?: string;
  featureSections: GuideSection[];
  usageTitle: string;
  usageDesc: string;
  usageSections: GuideSection[];
  platformTitle: string;
  platformDesc: string;
  platformSections: GuideSection[];
  soundTitle: string;
  soundDesc: string;
  soundSections: GuideSection[];
  helpTitle: string;
  helpItems: GuideItem[];
  feedbackTitle: string;
  feedbackDesc: string;
  feedbackItems: GuideItem[];
  footer: string;
  onboardingTitle: string;
  onboardingDesc: string;
}

const ko: GuideContent = {
  naverSection: {
    title: '네이버 쇼핑커넥트 안내',
    desc: '네이버 쇼핑커넥트는 브랜드커넥트(banner.naver.com)에서 크리에이터로 가입 후, 상품별로 전용 수수료 링크를 직접 발급받는 시스템입니다. 단순한 ID 입력으로는 자동 추적 링크를 만들 수 없습니다.',
    guideTitle: '이용 방법',
    guideSteps: '1. 네이버 브랜드커넥트에 크리에이터로 가입합니다\n2. 채널(블로그/인스타/유튜브)을 연동합니다\n3. 상품 찾기에서 홍보할 상품을 선택합니다\n4. 링크 발급 버튼으로 전용 수수료 링크를 받습니다\n5. 발급받은 링크를 콘텐츠에 삽입합니다',
    linkText: '네이버 브랜드커넥트 바로가기',
    notice: '본 앱은 AI가 상품을 식별하고 네이버 쇼핑 검색 링크를 자동 생성합니다. 정확한 수수료 추적을 위해서는 브랜드커넥트에서 발급받은 개별 링크를 직접 사용하세요.',
  },
  flowTitle: '콘텐츠 제작 순서 가이드',
  flowDesc: '앱에서 만들 수 있는 콘텐츠의 전체 제작 흐름을 한눈에 보여줍니다',
  flowSteps: [
    { num: 'STEP 1', title: '촬영 & AI 분석', desc: '상품을 촬영하면 AI가 제품명, 카테고리, 가격대를 자동 식별합니다' },
    { num: 'STEP 2', title: '쇼핑 매칭 & 제휴 링크', desc: '네이버/쿠팡에서 동일 상품을 찾고 제휴 수수료 링크를 자동 생성합니다' },
    { num: 'STEP 3', title: '숏폼 카드 & 템플릿', desc: '사진 위에 가격, 한줄평 스티커를 합성한 카드를 만듭니다' },
    { num: 'STEP 4', title: '캐러셀 & 숏폼 영상', desc: '여러 장의 카드를 슬라이드 캐러셀이나 숏폼 영상으로 제작합니다' },
    { num: 'STEP 5', title: '만화 콘텐츠 제작', desc: '상품을 활용한 4컷 만화 시나리오를 AI로 생성하고 이미지로 완성합니다' },
    { num: 'STEP 6', title: '공유 & 수익 추적', desc: '인스타, 틱톡, 카카오톡으로 공유하고 클릭수와 수익을 추적합니다' },
    { num: 'STEP 7', title: '바이럴 예측 & 트렌드 분석', desc: '콘텐츠의 바이럴 잠재력을 예측하고 트렌드 매칭으로 최적화합니다' },
  ],
  featuresTitle: '기능 소개',
  featuresDesc: undefined,
  featureSections: [
    {
      title: '',
      items: [
        { iconKey: 'Camera', title: '실물 촬영 & 쇼핑 매칭', desc: '신발, 조명, 옷 등을 촬영하면 AI가 제품을 식별하고 네이버 쇼핑 상품을 매칭합니다' },
        { iconKey: 'Link2', title: '제휴 링크 자동 생성', desc: '설정한 파트너스 ID로 수수료 링크를 즉시 생성합니다' },
        { iconKey: 'Sparkles', title: '숏폼 템플릿 자동 완성', desc: '사진 위에 가격과 추천 한줄평 스티커가 합성된 카드를 자동 생성합니다' },
        { iconKey: 'Send', title: 'SNS 원터치 공유 (아코디언)', desc: '공유 버튼을 탭하면 네이버클립·네이버TV·인스타·카카오톡·블로그 버튼이 펼쳐집니다' },
        { iconKey: 'Wand2', title: 'AI 스타일 추천', desc: '상품에 맞는 디자인 스타일을 AI가 추천하고 원탭으로 적용합니다' },
        { iconKey: 'Target', title: '바이럴 예측 & 페르소나 시뮬레이터', desc: '콘텐츠의 바이럴 잠재력을 예측하고 타겟 고객 관점의 반응을 시뮬레이션합니다' },
        { iconKey: 'Globe', title: '글로벌 현지화 & 멀티 플랫폼 익스포트', desc: '마케팅 카피를 다국어로 현지화하고, 인스타·틱톡·쇼츠 맞춤 이미지를 한 번에 생성합니다' },
        { iconKey: 'TrendingUp', title: '트렌드 매칭 & 트렌드 카피', desc: '실시간 SNS 트렌드 키워드와 상품을 자동 매칭하여 시의성 있는 카피를 생성합니다' },
        { iconKey: 'Store', title: '내 가게 정보 & 오프라인 연계', desc: '매장 정보를 등록하면 숏폼 카드와 공유 콘텐츠에 자동으로 포함됩니다' },
        { iconKey: 'Clapperboard', title: 'AR 촬영 모드', desc: '실시간 AR 효과를 적용하며 상품을 촬영할 수 있습니다' },
        { iconKey: 'Music2', title: '소리 펀치 (사운드 효과)', desc: '인기 밈 효과음을 직접 녹음해서 만화 숏폼에 타이밍별로 추가합니다' },
      ],
    },
  ],
  usageTitle: '콘텐츠 제작 기능 설명서',
  usageDesc: '각 제작 기능을 탭하면 상세 사용법이 펼쳐집니다',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: '숏폼 카드 (템플릿) 만들기', steps: [
          '결과 화면에서 "숏폼 카드" 버튼을 탭합니다',
          'AI가 제공한 한줄평과 가격이 사진 위에 스티커로 자동 합성됩니다',
          '스타일(매거진/볼드/미니멀/피드)을 선택해 디자인을 바꿀 수 있습니다',
          '가격, 한줄평, 해시태그 텍스트를 직접 수정할 수 있습니다',
          '배경 제거 버튼으로 깔끔한 상품 이미지를 만들 수 있습니다',
          '색상 테마를 변경해 브랜드에 맞는 디자인을 적용합니다',
          '완성된 카드를 저장하거나 바로 공유할 수 있습니다',
        ]},
        { iconKey: 'LayoutTemplate', title: '캐러셀 (여러 장 슬라이드) 만들기', steps: [
          '결과 화면에서 "캐러셀" 버튼을 탭합니다',
          '여러 상품이나 여러 각도의 사진을 순서대로 배치합니다',
          '각 슬라이드마다 개별 텍스트와 가격을 입력할 수 있습니다',
          '슬라이드 순서를 드래그하여 변경할 수 있습니다',
          '전체 슬라이드에 통일된 스타일을 적용합니다',
          '인스타그램 게시물용으로 세로 크기에 맞춰 자동 조정됩니다',
          '완성된 캐러셀을 이미지로 저장하거나 공유합니다',
        ]},
        { iconKey: 'Film', title: '숏폼 영상 (클립) 만들기', steps: [
          '결과 화면에서 "숏폼 영상" 버튼을 탭합니다',
          '상품 사진과 텍스트를 이어붙여 짧은 영상을 만듭니다',
          '화면 전환 효과와 텍스트 애니메이션이 자동 적용됩니다',
          '배경 음악(업비트/차분/에너지/없음)과 모션 효과(켄번스/줌/팬)를 선택할 수 있습니다',
          '고급 설정에서 화면 비율(세로/가로/정사각형)과 템플릿 스타일을 바꿀 수 있습니다',
          '하이브리드 모드(사진→만화 전환)를 켜면 영상 중반에 만화 효과가 적용됩니다',
          '영상 길이(10초/15초/20초/30초)를 선택합니다 - 기본 15초',
          '세로(9:16) 비율로 틱톡/인스타 릴스/유튜브 쇼츠에 최적화됩니다',
          '완성된 영상을 갤러리에 저장하거나 클라우드에 저장 후 각 플랫폼에 업로드합니다',
        ]},
        { iconKey: 'BookOpen', title: '만화 숏폼 (만화 영상) 만들기', steps: [
          '결과 화면에서 "만화 숏폼" 버튼을 탭합니다',
          'AI가 상품을 활용한 만화 시나리오를 자동 생성합니다 (싱글/2컷/3컷 분할)',
          '각 컷의 대사와 상황을 직접 수정할 수 있습니다',
          '웹툰 화풍(인스타툰/B급 병맛/미식 요리툰/아메리칸 코믹스/감성 지브리풍)을 선택합니다',
          'AI 성우 목소리(밝은 20대/차분한 나레이션/B급 억양)를 선택해 더빙할 수 있습니다',
          '고급 설정에서 영상 길이(10초/15초/20초/30초)를 선택합니다 - 컷 수에 따라 자동 추천',
          'AI 내레이션 더빙, 감정 표정 오버레이, MBTI 맞춤형 해설을 추가할 수 있습니다',
          '연작 에피소드 모드를 켜면 "1일차-3일차-7일차" 시간 흐름 스토리로 만들어집니다',
          '사운드 펀치 효과로 만화 효과음을 시간대별로 추가할 수 있습니다',
          '효과음은 감정에 따라 자동 매칭됩니다 (놀람: 헐 대박!, 행복: 샤방~, 확신: 따봉! 등)',
          '완성된 만화 숏폼을 저장하거나 틱톡/인스타/쇼츠로 바로 공유합니다',
        ]},
        { iconKey: 'Film', title: '타임라인 숏폼 (연작 에피소드) 만들기', steps: [
          '결과 화면에서 "만화 숏폼" 버튼을 탭합니다',
          '고급 설정에서 "연작 에피소드 모드"를 켭니다',
          '1일차-3일차-7일차 등 시간 흐름 스토리로 만화 숏폼이 자동 제작됩니다',
          '각 일차별 시나리오와 대사를 직접 수정할 수 있습니다',
          '웹툰 화풍과 내레이션 더빙을 함께 적용할 수 있습니다',
          '완성된 타임라인 숏폼을 저장하거나 틱톡/인스타/쇼츠로 공유합니다',
        ]},
        { iconKey: 'PenLine', title: '카피라이팅 (글 자동 생성)', steps: [
          '결과 화면에서 "카피 작성" 버튼을 탭합니다',
          'AI가 상품 분석 결과를 바탕으로 마케팅 문구를 생성합니다',
          '톤앤매너(캐주얼/전문/감성/유머)를 선택할 수 있습니다',
          '생성된 카피를 그대로 복사하거나 수정 후 사용합니다',
          '해시태그 추천도 함께 제공됩니다',
          '여러 버전의 카피를 비교하고 가장 좋은 것을 선택합니다',
        ]},
        { iconKey: 'Type', title: '리뷰 & 한줄평 작성', steps: [
          '결과 화면에서 "리뷰 입력" 버튼을 탭합니다',
          '직접 상품에 대한 한줄평을 작성하거나 AI 추천을 받습니다',
          '작성한 리뷰는 숏폼 카드와 캐러셀에 자동 반영됩니다',
          '리뷰를 수정하면 연결된 모든 콘텐츠가 업데이트됩니다',
        ]},
        { iconKey: 'Scissors', title: '배경 제거 & 이미지 편집', steps: [
          '결과 화면에서 "배경 제거" 버튼을 탭합니다',
          'AI가 상품의 배경을 자동으로 감지하고 제거합니다',
          '투명 배경 이미지로 저장되어 다양한 디자인에 활용 가능합니다',
          '제거된 이미지는 숏폼 카드, 캐러셀, 만화에 자동 적용됩니다',
          '필요시 배경 색상을 직접 변경할 수 있습니다',
        ]},
        { iconKey: 'Wand2', title: 'AI 스타일 추천', steps: [
          '결과 화면에서 "AI 스타일" 섹션을 확인합니다',
          'AI가 상품 카테고리와 분위기에 맞는 디자인 스타일을 추천합니다',
          '추천된 스타일을 탭하면 숏폼 카드에 즉시 적용됩니다',
          '스타일을 변경하면 텍스트 배치, 색상, 폰트가 자동으로 조정됩니다',
          '마음에 드는 스타일을 선택하면 모든 콘텐츠에 일관되게 적용됩니다',
        ]},
        { iconKey: 'Target', title: '바이럴 예측', steps: [
          '결과 화면에서 "바이럴 예측" 섹션을 확인합니다',
          'AI가 콘텐츠의 바이럴 잠재력을 점수로 예측합니다',
          '예측 점수는 후킹력, 트렌드 적합도, 공유 가능성을 종합 평가합니다',
          '개선 제안을 탭하면 점수를 높일 수 있는 팁을 확인할 수 있습니다',
          '제안에 따라 카피나 스타일을 수정하면 예측 점수가 다시 계산됩니다',
        ]},
        { iconKey: 'Users', title: '페르소나 시뮬레이터', steps: [
          '결과 화면에서 "페르소나 시뮬레이터" 섹션을 확인합니다',
          '타겟 고객의 페르소나(연령, 성별, 관심사)를 선택합니다',
          'AI가 해당 페르소나 관점에서 상품을 어떻게 평가할지 시뮬레이션합니다',
          '예상 반응, 구매 확률, 주요 어필 포인트를 확인할 수 있습니다',
          '시뮬레이션 결과를 바탕으로 마케팅 카피를 최적화할 수 있습니다',
        ]},
        { iconKey: 'Globe', title: '글로벌 현지화', steps: [
          '결과 화면에서 "글로벌 현지화" 섹션을 확인합니다',
          '마케팅 카피를 영어, 일본어, 중국어 등 다국어로 번역합니다',
          '단순 번역이 아닌 각국 문화와 SNS 트렌드에 맞게 현지화합니다',
          '국가별 인기 해시태그와 마케팅 톤을 자동 반영합니다',
          '번역된 카피를 탭하면 클립보드에 복사됩니다',
          '해외 진출 시 각국 플랫폼에 맞춘 콘텐츠를 빠르게 제작할 수 있습니다',
        ]},
        { iconKey: 'Shuffle', title: '멀티 플랫폼 익스포트', steps: [
          '결과 화면에서 "멀티 플랫폼 익스포트" 섹션을 확인합니다',
          '인스타그램, 틱톡, 유튜브 쇼츠 세 플랫폼에 맞춘 이미지를 한 번에 생성합니다',
          '각 플랫폼별 최적 화면 비율과 텍스트 위치가 자동 조정됩니다',
          '플랫폼별 권장 해시태그와 캡션 스타일이 자동 적용됩니다',
          '생성된 이미지를 각 플랫폼에 맞춰 개별 저장할 수 있습니다',
          '세 플랫폼 동시 업로드로 노출을 극대화할 수 있습니다',
        ]},
        { iconKey: 'TrendingUp', title: '트렌드 매칭', steps: [
          '결과 화면에서 "트렌드 매칭" 섹션을 확인합니다',
          'AI가 현재 SNS에서 유행하는 키워드와 상품을 자동 매칭합니다',
          '실시간 트렌드 키워드를 탭하면 관련 마케팅 카피가 자동 생성됩니다',
          '트렌드에 맞춘 해시태그 추천도 함께 제공됩니다',
          '시의성 있는 콘텐츠로 알고리즘 노출을 높일 수 있습니다',
        ]},
        { iconKey: 'Store', title: '내 가게 정보', steps: [
          '결과 화면에서 "내 가게 정보" 섹션을 확인합니다',
          '오프라인 매장 정보(주소, 영업시간, 전화번호)를 등록할 수 있습니다',
          '등록한 가게 정보가 숏폼 카드와 공유 콘텐츠에 자동 포함됩니다',
          '고객이 콘텐츠를 보고 매장 위치를 바로 확인할 수 있습니다',
          '온·오프라인 연계 마케팅에 활용하세요',
        ]},
        { iconKey: 'Video', title: '비디오 임포트', steps: [
          '결과 화면에서 "비디오 임포트" 기능을 사용합니다',
          '기존에 촬영한 영상을 불러와 숏폼 콘텐츠로 변환합니다',
          '영상에서 핵심 구간을 자동 추출하여 숏폼으로 만듭니다',
          '추출된 구간에 텍스트와 스티커를 추가할 수 있습니다',
          '기존 영상 자산을 재활용하여 콘텐츠 제작 시간을 단축하세요',
        ]},
      ],
    },
  ],
  platformTitle: '플랫폼별 영상 게시 방법',
  platformDesc: '완성된 숏폼 영상을 각 플랫폼에 업로드하는 방법을 단계별로 설명합니다',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: '틱톡 (TikTok) 업로드', steps: [
          '완성 화면에서 "틱톡" 공유 버튼을 탭하거나, 갤러리에 저장한 영상을 사용합니다',
          '틱톡 앱을 실행하고 하단 중앙의 "+" 버튼을 탭합니다',
          '갤러리에서 저장한 숏폼 영상을 선택합니다',
          '편집 화면에서 텍스트, 스티커, 효과를 추가할 수 있습니다 (선택사항)',
          '다음 버튼을 탭하고 영상 제목(캡션)을 입력합니다',
          '관련 해시태그를 추가합니다 (앱에서 추천받은 해시태그 활용)',
          '제휴 링크는 틱톡 프로필 바이오에 넣거나, 댓글에 고정하는 것이 효과적입니다',
          '공개 범위를 "공개"로 설정하고 게시 버튼을 탭합니다',
        ]},
        { iconKey: 'Instagram', title: '인스타그램 릴스 (Instagram Reels) 업로드', steps: [
          '완성 화면에서 "인스타" 공유 버튼을 탭하거나, 갤러리에 저장한 영상을 사용합니다',
          '인스타그램 앱을 실행하고 하단의 "+" 버튼을 탭한 후 "릴스"를 선택합니다',
          '갤러리에서 저장한 숏폼 영상을 선택합니다',
          '음악 추가: 인스타그램 내장 음악이나 원본 영상의 오디오를 선택합니다',
          '필요시 텍스트 스티커를 추가합니다 (상품명이나 후킹 문구를 화면에 표시)',
          '다음 버튼을 탭하고 캡션을 입력합니다',
          '제휴 링크는 캡션에 직접 넣거나, 프로필 바이오 링크를 통해 유도합니다',
          '관련 해시태그를 추가하고 "공개"로 설정한 후 공유 버튼을 탭합니다',
          '릴스 업로드 후 프로필의 "링크" 버튼에 제휴 링크를 등록해 두면 클릭률이 높아집니다',
        ]},
        { iconKey: 'Youtube', title: '유튜브 쇼츠 (YouTube Shorts) 업로드', steps: [
          '완성 화면에서 "쇼츠" 공유 버튼을 탭하거나, 갤러리에 저장한 영상을 사용합니다',
          '유튜브 앱을 실행하고 하단 중앙의 "+" 버튼을 탭한 후 "쇼츠 만들기"를 선택합니다',
          '갤러리에서 저장한 숏폼 영상을 선택합니다',
          '편집 화면에서 텍스트, 필터, 음악을 추가할 수 있습니다 (선택사항)',
          '다음 버튼을 탭하고 영상 제목을 입력합니다',
          '제목에 #Shorts 해시태그를 포함하면 쇼츠 피드에 더 잘 노출됩니다',
          '제휴 링크는 영상 설명란에 넣거나, 채널 프로필 링크에 등록합니다',
          '공개 설정을 "공개"로 하고 업로드 버튼을 탭합니다',
        ]},
        { iconKey: 'Share2', title: '네이버클립 & 카카오톡 공유', steps: [
          '네이버클립: 완성 화면에서 "공유" 버튼을 탭하면 홍보 문구와 이미지가 클립보드에 복사됩니다',
          '네이버클립 앱 또는 네이버TV에서 새 클립 만들기를 선택합니다',
          '저장한 영상을 업로드하고 복사된 홍보 문구를 붙여넣습니다',
          '카카오톡: 공유 버튼으로 메시지에 이미지와 링크를 함께 보낼 수 있습니다',
          '카카오톡 채널이나 오픈채팅방에 영상과 제휴 링크를 공유하면 직접 클릭 유도가 가능합니다',
        ]},
        { iconKey: 'Lightbulb', title: '멀티 플랫폼 동시 업로드 전략', steps: [
          '하나의 숏폼 영상을 틱톡, 인스타 릴스, 유튜브 쇼츠 세 곳에 모두 업로드하면 노출이 3배 늘어납니다',
          '각 플랫폼마다 캡션과 해시태그를 조금씩 다르게 작성하는 것이 알고리즘에 유리합니다',
          '틱톡은 트렌드 해시태그, 인스타는 상품 관련 해시태그, 쇼츠는 #Shorts를 함께 사용하세요',
          '제휴 링크는 각 플랫폼의 프로필 바이오에 동일하게 등록해 두면 관리가 편합니다',
          '업로드 시간대는 저녁 6시~10시(한국 시간)가 가장 시청률이 높습니다',
          '영상 길이는 15~30초로 설정하면 시청 지속 시간이 충분하면서도 알고리즘 노출에 유리합니다',
        ]},
      ],
    },
  ],
  soundTitle: '소리 펀치 (사운드 효과) 사용법',
  soundDesc: '인기 밈 효과음을 직접 녹음해서 만화 숏폼에 타이밍별로 추가하는 기능입니다',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: '소리 펀치 편집기 사용법', steps: [
          '만화 숏폼 생성기에서 "고급 옵션"을 펼칩니다',
          '"소리 펀치 컷 편집" 토글을 켭니다 (웹 브라우저에서만 사용 가능)',
          '녹음 버튼을 누르고 마이크에 소리를 내면 실시간으로 음파가 표시됩니다',
          '큰 소리가 감지되면 자동으로 효과 마커가 추가됩니다 (빵, 줌, 코믹 등)',
          '음성 명령으로 효과를 지정할 수도 있습니다 ("빵", "줌 인", "코믹" 등)',
          '녹음을 중지하면 타임라인에 마커가 표시되고 재생할 수 있습니다',
          '마커를 탭하면 효과 종류를 변경하거나 삭제할 수 있습니다',
          '만화 숏폼 생성 시 녹음된 효과가 영상에 자동으로 합성됩니다',
          '모바일에서는 "웹 브라우저에서만 사용할 수 있어요" 메시지가 표시됩니다',
        ]},
      ],
    },
  ],
  helpTitle: '도움말',
  helpItems: [
    { iconKey: 'Info', title: '사용 방법', desc: '사진을 찍거나 업로드하면 AI가 제품을 분석합니다. 결과 화면에서 쇼핑 매칭, 숏폼 카드, 공유를 한 번에 이용하세요.' },
    { iconKey: 'Link2', title: '수수료 링크 적용', desc: "결과 화면에서 '내 수수료 링크 붙여넣기' 버튼으로 브랜드커넥트 링크를 적용하세요. 공유와 카드에 자동 반영됩니다." },
  ],
  feedbackTitle: '피드백 & 오류 신고',
  feedbackDesc: '사용 중 불편한 점이나 오류를 발견하면 알려주세요. 여러분의 의견이 앱을 더 좋게 만듭니다.',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: '의견 보내기', desc: '구글 설문지로 피드백을 남겨주세요' },
    { iconKey: 'Bug', title: '오류 신고 & 오픈채팅', desc: '카카오톡 오픈채팅방에서 빠르게 도움받기' },
  ],
  footer: 'ShortConnect (숏커넥트) — 온·오프라인 셀러를 위한 올인원 AI 커머스',
  onboardingTitle: '앱 둘러보기 다시 보기',
  onboardingDesc: '처음 안내를 다시 확인하고 싶다면 눌러주세요',
};

const en: GuideContent = {
  naverSection: {
    title: 'Naver Shopping Connect Guide',
    desc: 'Naver Shopping Connect requires signing up as a creator on Brand Connect (brandconnect.naver.com) and generating dedicated commission links for each product. Simply entering an ID will not create automatic tracking links.',
    guideTitle: 'How to Use',
    guideSteps: '1. Sign up as a creator on Naver Brand Connect\n2. Link your channel (blog/Instagram/YouTube)\n3. Search for products you want to promote\n4. Click the link generation button to get your commission link\n5. Insert the generated link into your content',
    linkText: 'Go to Naver Brand Connect',
    notice: 'This app uses AI to identify products and automatically generate Naver Shopping search links. For accurate commission tracking, use the individual links issued by Brand Connect.',
  },
  flowTitle: 'Content Creation Workflow',
  flowDesc: 'An overview of the entire content creation flow available in the app',
  flowSteps: [
    { num: 'STEP 1', title: 'Capture & AI Analysis', desc: 'AI automatically identifies product name, category, and price range from photos' },
    { num: 'STEP 2', title: 'Shopping Match & Affiliate Links', desc: 'Finds the same product on Naver/Coupang and auto-generates affiliate commission links' },
    { num: 'STEP 3', title: 'Short-form Cards & Templates', desc: 'Creates cards with price and review stickers composited on photos' },
    { num: 'STEP 4', title: 'Carousel & Short-form Video', desc: 'Turns multiple cards into slide carousels or short-form videos' },
    { num: 'STEP 5', title: 'Comic Content Creation', desc: 'AI generates 4-panel comic scenarios using your product and completes them as images' },
    { num: 'STEP 6', title: 'Share & Revenue Tracking', desc: 'Share to Instagram, TikTok, KakaoTalk and track clicks and revenue' },
    { num: 'STEP 7', title: 'Viral Prediction & Trend Analysis', desc: 'Predicts viral potential of content and optimizes with trend matching' },
  ],
  featuresTitle: 'Feature Overview',
  featuresDesc: undefined,
  featureSections: [
    {
      title: '',
      items: [
        { iconKey: 'Camera', title: 'Product Capture & Shopping Match', desc: 'Photograph shoes, lighting, clothing — AI identifies the product and matches it on Naver Shopping' },
        { iconKey: 'Link2', title: 'Auto Affiliate Link Generation', desc: 'Instantly creates commission links using your partner ID' },
        { iconKey: 'Sparkles', title: 'Short-form Template Auto-Complete', desc: 'Auto-generates cards with price and recommended review stickers on photos' },
        { iconKey: 'Send', title: 'One-Tap SNS Sharing (Accordion)', desc: 'Tap share to expand Naver Clip, Naver TV, Instagram, KakaoTalk, and Blog buttons' },
        { iconKey: 'Wand2', title: 'AI Style Recommendation', desc: 'AI recommends design styles matching your product and applies them with one tap' },
        { iconKey: 'Target', title: 'Viral Prediction & Persona Simulator', desc: 'Predicts viral potential and simulates reactions from target customer perspectives' },
        { iconKey: 'Globe', title: 'Global Localization & Multi-Platform Export', desc: 'Localizes marketing copy into multiple languages and generates platform-optimized images at once' },
        { iconKey: 'TrendingUp', title: 'Trend Matching & Trend Copy', desc: 'Auto-matches real-time SNS trend keywords with products for timely copy' },
        { iconKey: 'Store', title: 'My Store Info & Offline Integration', desc: 'Register store info and it will be automatically included in short-form cards and shared content' },
        { iconKey: 'Clapperboard', title: 'AR Capture Mode', desc: 'Capture products with real-time AR effects applied' },
        { iconKey: 'Music2', title: 'Sound Punch (Sound Effects)', desc: 'Record popular meme sounds and add them to comic short-forms by timing' },
      ],
    },
  ],
  usageTitle: 'Content Creation Guide',
  usageDesc: 'Tap each feature to see detailed usage instructions',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: 'Create Short-form Cards (Templates)', steps: [
          'Tap the "Short-form Card" button on the result screen',
          'AI-provided review and price are automatically composited as stickers on the photo',
          'Choose a style (Magazine/Bold/Minimal/Feed) to change the design',
          'You can directly edit price, review, and hashtag text',
          'Use the background removal button for a clean product image',
          'Change color themes to match your brand',
          'Save the completed card or share it directly',
        ]},
        { iconKey: 'LayoutTemplate', title: 'Create Carousel (Multi-Slide)', steps: [
          'Tap the "Carousel" button on the result screen',
          'Arrange multiple products or multi-angle photos in order',
          'Each slide can have individual text and price input',
          'Drag to change slide order',
          'Apply a unified style across all slides',
          'Automatically adjusted to vertical size for Instagram posts',
          'Save the completed carousel as an image or share it',
        ]},
        { iconKey: 'Film', title: 'Create Short-form Video (Clip)', steps: [
          'Tap the "Short-form Video" button on the result screen',
          'Product photos and text are stitched into a short video',
          'Transition effects and text animations are automatically applied',
          'Choose background music (Upbeat/Calm/Energetic/None) and motion effects (Kenburns/Zoom/Pan)',
          'Advanced settings let you change aspect ratio (vertical/horizontal/square) and template style',
          'Enable hybrid mode (photo-to-comic transition) for a comic effect in the second half',
          'Choose video length (10s/15s/20s/30s) — default 15s',
          'Optimized for vertical (9:16) ratio for TikTok/Instagram Reels/YouTube Shorts',
          'Save the completed video to gallery or cloud, then upload to each platform',
        ]},
        { iconKey: 'BookOpen', title: 'Create Comic Short-form (Comic Video)', steps: [
          'Tap the "Comic Short-form" button on the result screen',
          'AI automatically generates a comic scenario using your product (single/2-panel/3-panel split)',
          'You can directly edit dialogue and situations for each panel',
          'Choose a webtoon style (Instatoon/B-grade/ Food comic/American comic/Studio Ghibli style)',
          'Choose an AI narrator voice (Bright 20s/Calm narration/B-grade accent) for dubbing',
          'In advanced settings, select video length (10s/15s/20s/30s) — auto-recommended based on panel count',
          'Add AI narration dubbing, emotion expression overlays, and MBTI-tailored commentary',
          'Enable episode mode for a "Day 1–Day 3–Day 7" timeline story',
          'Add comic sound effects by timing with the Sound Punch feature',
          'Sound effects are auto-matched by emotion (Surprise: Whoa!, Happy: Yay~, Confidence: Thumbs up!)',
          'Save the completed comic short-form or share directly to TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'Film', title: 'Create Timeline Short-form (Episode Series)', steps: [
          'Tap the "Comic Short-form" button on the result screen',
          'Enable "Episode Mode" in advanced settings',
          'A timeline story (Day 1–Day 3–Day 7) comic short-form is automatically produced',
          'You can edit the scenario and dialogue for each day',
          'Webtoon style and narration dubbing can be applied together',
          'Save the completed timeline short-form or share to TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'PenLine', title: 'Copywriting (Auto Text Generation)', steps: [
          'Tap the "Write Copy" button on the result screen',
          'AI generates marketing copy based on product analysis results',
          'Choose tone and manner (Casual/Professional/Emotional/Humor)',
          'Copy the generated copy as-is or edit before use',
          'Hashtag recommendations are also provided',
          'Compare multiple copy versions and choose the best one',
        ]},
        { iconKey: 'Type', title: 'Review & One-line Comment', steps: [
          'Tap the "Review Input" button on the result screen',
          'Write your own one-line review or get AI recommendations',
          'Written reviews are automatically reflected in short-form cards and carousels',
          'Editing a review updates all linked content',
        ]},
        { iconKey: 'Scissors', title: 'Background Removal & Image Editing', steps: [
          'Tap the "Remove Background" button on the result screen',
          'AI automatically detects and removes the product background',
          'Saved as a transparent background image for versatile design use',
          'The removed image is automatically applied to short-form cards, carousels, and comics',
          'You can manually change the background color if needed',
        ]},
        { iconKey: 'Wand2', title: 'AI Style Recommendation', steps: [
          'Check the "AI Style" section on the result screen',
          'AI recommends design styles matching the product category and mood',
          'Tap a recommended style to apply it instantly to the short-form card',
          'Changing style automatically adjusts text layout, colors, and fonts',
          'Selecting a style applies it consistently across all content',
        ]},
        { iconKey: 'Target', title: 'Viral Prediction', steps: [
          'Check the "Viral Prediction" section on the result screen',
          'AI predicts the viral potential of content as a score',
          'The prediction score evaluates hook power, trend fit, and shareability',
          'Tap improvement suggestions for tips to increase the score',
          'Editing copy or style based on suggestions recalculates the prediction score',
        ]},
        { iconKey: 'Users', title: 'Persona Simulator', steps: [
          'Check the "Persona Simulator" section on the result screen',
          'Select a target customer persona (age, gender, interests)',
          'AI simulates how the persona would evaluate the product',
          'View expected reactions, purchase probability, and key appeal points',
          'Use simulation results to optimize your marketing copy',
        ]},
        { iconKey: 'Globe', title: 'Global Localization', steps: [
          'Check the "Global Localization" section on the result screen',
          'Translate marketing copy into English, Japanese, Chinese, and more',
          'Not just translation — localized to each country\'s culture and SNS trends',
          'Country-specific popular hashtags and marketing tones are auto-reflected',
          'Tap translated copy to copy to clipboard',
          'Quickly create platform-optimized content for overseas expansion',
        ]},
        { iconKey: 'Shuffle', title: 'Multi-Platform Export', steps: [
          'Check the "Multi-Platform Export" section on the result screen',
          'Generate images optimized for Instagram, TikTok, and YouTube Shorts all at once',
          'Optimal aspect ratio and text position are auto-adjusted per platform',
          'Recommended hashtags and caption styles are auto-applied per platform',
          'Save generated images individually for each platform',
          'Maximize exposure with simultaneous uploads to all three platforms',
        ]},
        { iconKey: 'TrendingUp', title: 'Trend Matching', steps: [
          'Check the "Trend Matching" section on the result screen',
          'AI auto-matches currently trending SNS keywords with your product',
          'Tap a real-time trend keyword to auto-generate related marketing copy',
          'Trend-matched hashtag recommendations are also provided',
          'Create timely content to boost algorithm exposure',
        ]},
        { iconKey: 'Store', title: 'My Store Info', steps: [
          'Check the "My Store Info" section on the result screen',
          'Register offline store info (address, hours, phone number)',
          'Registered store info is automatically included in short-form cards and shared content',
          'Customers can check store location directly from content',
          'Use for online-offline integrated marketing',
        ]},
        { iconKey: 'Video', title: 'Video Import', steps: [
          'Use the "Video Import" feature on the result screen',
          'Import previously recorded videos and convert them to short-form content',
          'Automatically extract key segments from videos to create short-forms',
          'Add text and stickers to extracted segments',
          'Recycle existing video assets to shorten content creation time',
        ]},
      ],
    },
  ],
  platformTitle: 'Platform Upload Guide',
  platformDesc: 'Step-by-step instructions for uploading completed short-form videos to each platform',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'TikTok Upload', steps: [
          'Tap the "TikTok" share button on the result screen, or use a video saved to gallery',
          'Open the TikTok app and tap the "+" button at the bottom center',
          'Select the saved short-form video from your gallery',
          'Add text, stickers, and effects on the edit screen (optional)',
          'Tap Next and enter a video title (caption)',
          'Add relevant hashtags (use the app\'s recommended hashtags)',
          'Affiliate links are most effective in your TikTok profile bio or pinned comments',
          'Set visibility to "Public" and tap Post',
        ]},
        { iconKey: 'Instagram', title: 'Instagram Reels Upload', steps: [
          'Tap the "Instagram" share button on the result screen, or use a video saved to gallery',
          'Open the Instagram app, tap the "+" button, and select "Reels"',
          'Select the saved short-form video from your gallery',
          'Add music: Choose from Instagram\'s built-in music or the original video audio',
          'Add text stickers if needed (show product name or hook text on screen)',
          'Tap Next and enter a caption',
          'Add affiliate links directly in the caption or via profile bio link',
          'Add relevant hashtags, set to "Public", and tap Share',
          'After uploading the Reel, register the affiliate link in your profile\'s "Link" button for higher click rates',
        ]},
        { iconKey: 'Youtube', title: 'YouTube Shorts Upload', steps: [
          'Tap the "Shorts" share button on the result screen, or use a video saved to gallery',
          'Open the YouTube app, tap the "+" button, and select "Create Short"',
          'Select the saved short-form video from your gallery',
          'Add text, filters, and music on the edit screen (optional)',
          'Tap Next and enter a video title',
          'Include the #Shorts hashtag in the title for better Shorts feed exposure',
          'Add affiliate links in the video description or channel profile link',
          'Set visibility to "Public" and tap Upload',
        ]},
        { iconKey: 'Share2', title: 'Naver Clip & KakaoTalk Sharing', steps: [
          'Naver Clip: Tap the "Share" button to copy promotional text and image to clipboard',
          'Open the Naver Clip app or Naver TV and select Create New Clip',
          'Upload the saved video and paste the copied promotional text',
          'KakaoTalk: Use the share button to send images and links together in a message',
          'Share videos and affiliate links in KakaoTalk channels or open chat rooms for direct click engagement',
        ]},
        { iconKey: 'Lightbulb', title: 'Multi-Platform Simultaneous Upload Strategy', steps: [
          'Uploading one short-form video to TikTok, Instagram Reels, and YouTube Shorts triples your exposure',
          'Write slightly different captions and hashtags for each platform — this helps with the algorithm',
          'Use trend hashtags for TikTok, product-related hashtags for Instagram, and #Shorts for YouTube',
          'Register the same affiliate link in each platform\'s profile bio for easy management',
          'The best upload time is 6–10 PM (local time) for highest viewership',
          'Set video length to 15–30 seconds for sufficient watch time and algorithm-friendly exposure',
        ]},
      ],
    },
  ],
  soundTitle: 'Sound Punch (Sound Effects) Guide',
  soundDesc: 'Record popular meme sounds and add them to comic short-forms by timing',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'Sound Punch Editor Usage', steps: [
          'Expand "Advanced Options" in the comic short-form generator',
          'Enable the "Sound Punch Cut Edit" toggle (web browser only)',
          'Press the record button and make sounds into the mic — waveforms display in real time',
          'Loud sounds are automatically detected and effect markers are added (Bang, Zoom, Comic, etc.)',
          'You can also specify effects with voice commands ("Bang", "Zoom in", "Comic", etc.)',
          'Stop recording to see markers on the timeline and play them back',
          'Tap a marker to change the effect type or delete it',
          'Recorded effects are automatically composited into the video during comic short-form generation',
          'On mobile, a "Only available in web browser" message is displayed',
        ]},
      ],
    },
  ],
  helpTitle: 'Help',
  helpItems: [
    { iconKey: 'Info', title: 'How to Use', desc: 'Take or upload a photo and AI will analyze the product. Use shopping match, short-form cards, and sharing all from the result screen.' },
    { iconKey: 'Link2', title: 'Applying Commission Links', desc: "Use the 'Paste my commission link' button on the result screen to apply your Brand Connect link. It will be automatically reflected in sharing and cards." },
  ],
  feedbackTitle: 'Feedback & Bug Reports',
  feedbackDesc: 'Let us know about any inconveniences or bugs. Your feedback makes the app better.',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: 'Send Feedback', desc: 'Leave feedback via the Google Form' },
    { iconKey: 'Bug', title: 'Bug Reports & Open Chat', desc: 'Get quick help in the KakaoTalk open chat room' },
  ],
  footer: 'ShortConnect — All-in-one AI commerce for online and offline sellers',
  onboardingTitle: 'Replay App Tour',
  onboardingDesc: 'Tap to see the initial guide again',
};

const ja: GuideContent = {
  naverSection: {
    title: 'Naverショッピングコネクトガイド',
    desc: 'Naverショッピングコネクトは、Brand Connect（brandconnect.naver.com）でクリエイターとして登録後、商品ごとに専用コミッションリンクを直接発行するシステムです。ID入力だけでは自動追跡リンクを作成できません。',
    guideTitle: '使い方',
    guideSteps: '1. Naver Brand Connectにクリエイターとして登録します\n2. チャンネル（ブログ/インスタ/YouTube）を連携します\n3. プロモーションする商品を検索します\n4. リンク発行ボタンで専用コミッションリンクを取得します\n5. 発行されたリンクをコンテンツに挿入します',
    linkText: 'Naver Brand Connectへ移動',
    notice: '本アプリはAIが商品を識別し、Naverショッピング検索リンクを自動生成します。正確なコミッション追跡には、Brand Connectで発行された個別リンクを使用してください。',
  },
  flowTitle: 'コンテンツ制作ワークフロー',
  flowDesc: 'アプリで作成できるコンテンツの全体制作フローを一目で表示します',
  flowSteps: [
    { num: 'STEP 1', title: '撮影 & AI分析', desc: '商品を撮影するとAIが商品名、カテゴリ、価格帯を自動識別します' },
    { num: 'STEP 2', title: 'ショッピングマッチ & アフィリエイトリンク', desc: 'Naver/Coupangで同一商品を見つけ、アフィリエイトコミッションリンクを自動生成します' },
    { num: 'STEP 3', title: 'ショートフォームカード & テンプレート', desc: '写真の上に価格とレビューステッカーを合成したカードを作成します' },
    { num: 'STEP 4', title: 'カルーセル & ショートフォーム動画', desc: '複数のカードをスライドカルーセルやショートフォーム動画に制作します' },
    { num: 'STEP 5', title: '漫画コンテンツ制作', desc: '商品を使った4コマ漫画シナリオをAIで生成し、画像として完成させます' },
    { num: 'STEP 6', title: '共有 & 収益追跡', desc: 'インスタ、TikTok、カカオトークで共有し、クリック数と収益を追跡します' },
    { num: 'STEP 7', title: 'バイラル予測 & トレンド分析', desc: 'コンテンツのバイラルポテンシャルを予測し、トレンドマッチングで最適化します' },
  ],
  featuresTitle: '機能紹介',
  featuresDesc: undefined,
  featureSections: [
    {
      title: '',
      items: [
        { iconKey: 'Camera', title: '商品撮影 & ショッピングマッチ', desc: '靴、照明、服などを撮影するとAIが商品を識別し、Naverショッピング商品をマッチングします' },
        { iconKey: 'Link2', title: 'アフィリエイトリンク自動生成', desc: '設定したパートナーIDでコミッションリンクを即座に生成します' },
        { iconKey: 'Sparkles', title: 'ショートフォームテンプレート自動完成', desc: '写真の上に価格と推薦レビューステッカーを合成したカードを自動生成します' },
        { iconKey: 'Send', title: 'SNSワンタップ共有（アコーディオン）', desc: '共有ボタンをタップするとNaverクリップ・Naver TV・インスタ・カカオトーク・ブログボタンが展開します' },
        { iconKey: 'Wand2', title: 'AIスタイル推薦', desc: '商品に合ったデザインスタイルをAIが推薦し、ワンタップで適用します' },
        { iconKey: 'Target', title: 'バイラル予測 & ペルソナシミュレーター', desc: 'コンテンツのバイラルポテンシャルを予測し、ターゲット顧客の反応をシミュレーションします' },
        { iconKey: 'Globe', title: 'グローバル現地化 & マルチプラットフォーム出力', desc: 'マーケティングコピーを多言語に現地化し、インスタ・TikTok・ショート専用画像を一括生成します' },
        { iconKey: 'TrendingUp', title: 'トレンドマッチング & トレンドコピー', desc: 'リアルタイムSNSトレンドキーワードと商品を自動マッチングしてタイムリーなコピーを生成します' },
        { iconKey: 'Store', title: 'マイストア情報 & オフライン連携', desc: 'ストア情報を登録するとショートフォームカードと共有コンテンツに自動的に含まれます' },
        { iconKey: 'Clapperboard', title: 'AR撮影モード', desc: 'リアルタイムAR効果を適用して商品を撮影できます' },
        { iconKey: 'Music2', title: 'サウンドパンチ（効果音）', desc: '人気ミーム効果音を直接録音して漫画ショートフォームにタイミング別に追加します' },
      ],
    },
  ],
  usageTitle: 'コンテンツ制作機能ガイド',
  usageDesc: '各制作機能をタップすると詳細な使い方が展開します',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: 'ショートフォームカード（テンプレート）作成', steps: [
          '結果画面で「ショートフォームカード」ボタンをタップします',
          'AIが提供したレビューと価格が写真の上にステッカーとして自動合成されます',
          'スタイル（マガジン/ボールド/ミニマル/フィード）を選択してデザインを変更できます',
          '価格、レビュー、ハッシュタグテキストを直接編集できます',
          '背景除去ボタンでクリーンな商品画像を作成できます',
          'カラーテーマを変更してブランドに合ったデザインを適用します',
          '完成したカードを保存または直接共有できます',
        ]},
        { iconKey: 'LayoutTemplate', title: 'カルーセル（複数スライド）作成', steps: [
          '結果画面で「カルーセル」ボタンをタップします',
          '複数の商品や複数角度の写真を順番に配置します',
          '各スライドに個別テキストと価格を入力できます',
          'スライドの順序をドラッグで変更できます',
          '全スライドに統一スタイルを適用します',
          'Instagram投稿用に縦サイズに自動調整されます',
          '完成したカルーセルを画像として保存または共有します',
        ]},
        { iconKey: 'Film', title: 'ショートフォーム動画（クリップ）作成', steps: [
          '結果画面で「ショートフォーム動画」ボタンをタップします',
          '商品写真とテキストをつなぎ合わせて短い動画を作成します',
          '画面切り替え効果とテキストアニメーションが自動適用されます',
          'BGM（アップビート/落ち着き/エネルギー/なし）とモーション効果（ケンバーンズ/ズーム/パン）を選択できます',
          '詳細設定で画面比率（縦/横/正方形）とテンプレートスタイルを変更できます',
          'ハイブリッドモード（写真→漫画切り替え）をオンにすると動画後半に漫画効果が適用されます',
          '動画の長さ（10秒/15秒/20秒/30秒）を選択します — デフォルト15秒',
          '縦（9:16）比率でTikTok/Instagramリール/YouTubeショートに最適化されています',
          '完成した動画をギャラリーに保存またはクラウドに保存後、各プラットフォームにアップロードします',
        ]},
        { iconKey: 'BookOpen', title: '漫画ショートフォーム（漫画動画）作成', steps: [
          '結果画面で「漫画ショートフォーム」ボタンをタップします',
          'AIが商品を使った漫画シナリオを自動生成します（シングル/2コマ/3コマ分割）',
          '各コマのセリフと状況を直接編集できます',
          'ウェブトゥーン画風（インストゥーン/B級/グルメコミック/アメリカンコミック/ジブリ風）を選択します',
          'AI声優の声（明るい20代/落ち着いたナレーション/B級アクセント）を選択してダビングできます',
          '詳細設定で動画の長さ（10秒/15秒/20秒/30秒）を選択します — コマ数に応じて自動推奨',
          'AIナレーションダビング、感情表情オーバーレイ、MBTI解説を追加できます',
          'エピソードモードをオンにすると「1日目-3日目-7日目」のタイムラインストーリーになります',
          'サウンドパンチ効果で漫画効果音をタイミング別に追加できます',
          '効果音は感情に応じて自動マッチングされます（驚き：うわ！、幸せ：イェイ～、確信：いいね！など）',
          '完成した漫画ショートフォームを保存またはTikTok/インスタ/ショートに直接共有します',
        ]},
        { iconKey: 'Film', title: 'タイムラインショートフォーム（連作エピソード）作成', steps: [
          '結果画面で「漫画ショートフォーム」ボタンをタップします',
          '詳細設定で「エピソードモード」をオンにします',
          '1日目-3日目-7日目などのタイムラインストーリーの漫画ショートフォームが自動制作されます',
          '各日のシナリオとセリフを直接編集できます',
          'ウェブトゥーン画風とナレーションダビングを一緒に適用できます',
          '完成したタイムラインショートフォームを保存またはTikTok/インスタ/ショートに共有します',
        ]},
        { iconKey: 'PenLine', title: 'コピーライティング（テキスト自動生成）', steps: [
          '結果画面で「コピー作成」ボタンをタップします',
          'AIが商品分析結果に基づいてマーケティング文案を生成します',
          'トーン＆マナー（カジュアル/プロ/エモーショナル/ユーモア）を選択できます',
          '生成されたコピーをそのままコピーまたは編集後に使用します',
          'ハッシュタグ推奨も一緒に提供されます',
          '複数バージョンのコピーを比較して最適なものを選択します',
        ]},
        { iconKey: 'Type', title: 'レビュー & 一行コメント作成', steps: [
          '結果画面で「レビュー入力」ボタンをタップします',
          '直接商品についての一行レビューを書くかAI推奨を受け取ります',
          '書かれたレビューはショートフォームカードとカルーセルに自動反映されます',
          'レビューを編集すると連携された全コンテンツが更新されます',
        ]},
        { iconKey: 'Scissors', title: '背景除去 & 画像編集', steps: [
          '結果画面で「背景除去」ボタンをタップします',
          'AIが商品の背景を自動検出して除去します',
          '透明背景画像として保存され、様々なデザインに活用可能です',
          '除去された画像はショートフォームカード、カルーセル、漫画に自動適用されます',
          '必要に応じて背景色を直接変更できます',
        ]},
        { iconKey: 'Wand2', title: 'AIスタイル推薦', steps: [
          '結果画面で「AIスタイル」セクションを確認します',
          'AIが商品カテゴリと雰囲気に合ったデザインスタイルを推薦します',
          '推薦されたスタイルをタップするとショートフォームカードに即座に適用されます',
          'スタイルを変更するとテキスト配置、カラー、フォントが自動調整されます',
          '気に入ったスタイルを選択すると全コンテンツに一貫して適用されます',
        ]},
        { iconKey: 'Target', title: 'バイラル予測', steps: [
          '結果画面で「バイラル予測」セクションを確認します',
          'AIがコンテンツのバイラルポテンシャルをスコアで予測します',
          '予測スコアはフック力、トレンド適合度、共有可能性を総合評価します',
          '改善提案をタップするとスコアを上げるヒントを確認できます',
          '提案に従ってカピーやスタイルを修正すると予測スコアが再計算されます',
        ]},
        { iconKey: 'Users', title: 'ペルソナシミュレーター', steps: [
          '結果画面で「ペルソナシミュレーター」セクションを確認します',
          'ターゲット顧客のペルソナ（年齢、性別、興味）を選択します',
          'AIがそのペルソナの観点で商品をどう評価するかシミュレーションします',
          '予想される反応、購入確率、主要アピールポイントを確認できます',
          'シミュレーション結果を基にマーケティングコピーを最適化できます',
        ]},
        { iconKey: 'Globe', title: 'グローバル現地化', steps: [
          '結果画面で「グローバル現地化」セクションを確認します',
          'マーケティングコピーを英語、日本語、中国語など多言語に翻訳します',
          '単なる翻訳ではなく各国の文化とSNSトレンドに合わせて現地化します',
          '国別人気ハッシュタグとマーケティングトーンを自動反映します',
          '翻訳されたコピーをタップするとクリップボードにコピーされます',
          '海外進出時に各国プラットフォームに合ったコンテンツを素早く制作できます',
        ]},
        { iconKey: 'Shuffle', title: 'マルチプラットフォーム出力', steps: [
          '結果画面で「マルチプラットフォーム出力」セクションを確認します',
          'Instagram、TikTok、YouTubeショートの3プラットフォーム向け画像を一括生成します',
          '各プラットフォームの最適画面比率とテキスト位置が自動調整されます',
          'プラットフォーム別推奨ハッシュタグとキャプションスタイルが自動適用されます',
          '生成された画像を各プラットフォームに合わせて個別保存できます',
          '3プラットフォーム同時アップロードで露出を最大化できます',
        ]},
        { iconKey: 'TrendingUp', title: 'トレンドマッチング', steps: [
          '結果画面で「トレンドマッチング」セクションを確認します',
          'AIが現在SNSで流行しているキーワードと商品を自動マッチングします',
          'リアルタイムトレンドキーワードをタップすると関連マーケティングコピーが自動生成されます',
          'トレンドに合わせたハッシュタグ推奨も一緒に提供されます',
          'タイムリーなコンテンツでアルゴリズム露出を高められます',
        ]},
        { iconKey: 'Store', title: 'マイストア情報', steps: [
          '結果画面で「マイストア情報」セクションを確認します',
          'オフラインストア情報（住所、営業時間、電話番号）を登録できます',
          '登録したストア情報がショートフォームカードと共有コンテンツに自動含まれます',
          '顧客がコンテンツを見てストア位置を直接確認できます',
          'オン・オフライン連携マーケティングに活用してください',
        ]},
        { iconKey: 'Video', title: 'ビデオインポート', steps: [
          '結果画面で「ビデオインポート」機能を使用します',
          '以前に撮影した動画を読み込んでショートフォームコンテンツに変換します',
          '動画から重要な区間を自動抽出してショートフォームにします',
          '抽出された区間にテキストとステッカーを追加できます',
          '既存の動画資産を再利用してコンテンツ制作時間を短縮してください',
        ]},
      ],
    },
  ],
  platformTitle: 'プラットフォーム別動画投稿ガイド',
  platformDesc: '完成したショートフォーム動画を各プラットフォームにアップロードする方法をステップ別に説明します',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'TikTokアップロード', steps: [
          '完成画面で「TikTok」共有ボタンをタップするか、ギャラリーに保存した動画を使用します',
          'TikTokアプリを起動し、下部中央の「+」ボタンをタップします',
          'ギャラリーから保存したショートフォーム動画を選択します',
          '編集画面でテキスト、ステッカー、エフェクトを追加できます（任意）',
          '次へボタンをタップし、動画タイトル（キャプション）を入力します',
          '関連ハッシュタグを追加します（アプリの推奨ハッシュタグを活用）',
          'アフィリエイトリンクはTikTokプロフィールのバイオまたはピン留めコメントに入れるのが効果的です',
          '公開範囲を「公開」に設定して投稿ボタンをタップします',
        ]},
        { iconKey: 'Instagram', title: 'Instagramリールアップロード', steps: [
          '完成画面で「インスタ」共有ボタンをタップするか、ギャラリーに保存した動画を使用します',
          'Instagramアプリを起動し、下部の「+」ボタンをタップ後「リール」を選択します',
          'ギャラリーから保存したショートフォーム動画を選択します',
          '音楽追加：Instagram内蔵音楽または元の動画のオーディオを選択します',
          '必要に応じてテキストステッカーを追加します（商品名やフックテキストを画面に表示）',
          '次へボタンをタップし、キャプションを入力します',
          'アフィリエイトリンクはキャプションに直接入れるか、プロフィールバイオリンクで誘導します',
          '関連ハッシュタグを追加し、「公開」に設定後、共有ボタンをタップします',
          'リールアップロード後、プロフィールの「リンク」ボタンにアフィリエイトリンクを登録するとクリック率が上がります',
        ]},
        { iconKey: 'Youtube', title: 'YouTubeショートアップロード', steps: [
          '完成画面で「ショート」共有ボタンをタップするか、ギャラリーに保存した動画を使用します',
          'YouTubeアプリを起動し、下部中央の「+」ボタンをタップ後「ショートを作成」を選択します',
          'ギャラリーから保存したショートフォーム動画を選択します',
          '編集画面でテキスト、フィルター、音楽を追加できます（任意）',
          '次へボタンをタップし、動画タイトルを入力します',
          'タイトルに#Shortsハッシュタグを含めるとショートフィードにより露出しやすくなります',
          'アフィリエイトリンクは動画説明欄またはチャンネルプロフィールリンクに登録します',
          '公開設定を「公開」にしてアップロードボタンをタップします',
        ]},
        { iconKey: 'Share2', title: 'Naverクリップ & カカオトーク共有', steps: [
          'Naverクリップ：完成画面で「共有」ボタンをタップするとプロモテキストと画像がクリップボードにコピーされます',
          'NaverクリップアプリまたはNaver TVで新規クリップ作成を選択します',
          '保存した動画をアップロードし、コピーされたプロモテキストを貼り付けます',
          'カカオトーク：共有ボタンでメッセージに画像とリンクを一緒に送信できます',
          'カカオトークチャンネルやオープンチャットに動画とアフィリエイトリンクを共有すると直接的なクリック誘導が可能です',
        ]},
        { iconKey: 'Lightbulb', title: 'マルチプラットフォーム同時アップロード戦略', steps: [
          '一つのショートフォーム動画をTikTok、Instagramリール、YouTubeショートの3箇所に全てアップロードすると露出が3倍になります',
          '各プラットフォームでキャプションとハッシュタグを少し変えるとアルゴリズムに有利です',
          'TikTokはトレンドハッシュタグ、インスタは商品関連ハッシュタグ、ショートは#Shortsを一緒に使用してください',
          'アフィリエイトリンクは各プラットフォームのプロフィールバイオに同じように登録すると管理が楽です',
          'アップロード時間帯は午後6時〜10時（現地時間）が最も視聴率が高いです',
          '動画の長さは15〜30秒に設定すると視聴継続時間が十分でアルゴリズム露出にも有利です',
        ]},
      ],
    },
  ],
  soundTitle: 'サウンドパンチ（効果音）ガイド',
  soundDesc: '人気ミーム効果音を直接録音して漫画ショートフォームにタイミング別に追加する機能です',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'サウンドパンチエディタの使い方', steps: [
          '漫画ショートフォームジェネレーターで「詳細オプション」を展開します',
          '「サウンドパンチカット編集」トグルをオンにします（Webブラウザのみ）',
          '録音ボタンを押してマイクに音を出すとリアルタイムで音波が表示されます',
          '大きな音が検出されると自動的にエフェクトマーカーが追加されます（バン、ズーム、コミックなど）',
          '音声コマンドでエフェクトを指定することもできます（「バン」、「ズームイン」、「コミック」など）',
          '録音を停止するとタイムラインにマーカーが表示され、再生できます',
          'マーカーをタップするとエフェクトの種類を変更または削除できます',
          '漫画ショートフォーム生成時に録音されたエフェクトが動画に自動合成されます',
          'モバイルでは「Webブラウザでのみ使用できます」というメッセージが表示されます',
        ]},
      ],
    },
  ],
  helpTitle: 'ヘルプ',
  helpItems: [
    { iconKey: 'Info', title: '使い方', desc: '写真を撮るかアップロードするとAIが商品を分析します。結果画面でショッピングマッチ、ショートフォームカード、共有を一度に利用してください。' },
    { iconKey: 'Link2', title: 'コミッションリンク適用', desc: "結果画面の「コミッションリンクを貼り付け」ボタンでBrand Connectリンクを適用してください。共有とカードに自動反映されます。" },
  ],
  feedbackTitle: 'フィードバック & バグ報告',
  feedbackDesc: 'ご不便な点やバグを発見したらお知らせください。皆様の意見がアプリをより良くします。',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: 'フィードバックを送信', desc: 'Googleフォームでフィードバックをお残しください' },
    { iconKey: 'Bug', title: 'バグ報告 & オープンチャット', desc: 'カカオトークオープンチャットで素早くサポートを受けられます' },
  ],
  footer: 'ShortConnect — オンライン・オフラインセラーのためのオールインワンAIコマース',
  onboardingTitle: 'アプリツアーをもう一度見る',
  onboardingDesc: '初期ガイドをもう一度確認したい場合はタップしてください',
};

const vi: GuideContent = {
  naverSection: {
    title: 'Hướng dẫn Naver Shopping Connect',
    desc: 'Naver Shopping Connect yêu cầu đăng ký làm nhà sáng tạo trên Brand Connect (brandconnect.naver.com) và tự tạo liên kết hoa hồng riêng cho từng sản phẩm. Chỉ nhập ID sẽ không tạo được liên kết theo dõi tự động.',
    guideTitle: 'Cách sử dụng',
    guideSteps: '1. Đăng ký làm nhà sáng tạo trên Naver Brand Connect\n2. Liên kết kênh (blog/Instagram/YouTube)\n3. Tìm sản phẩm bạn muốn quảng bá\n4. Nhấn nút tạo liên kết để nhận liên kết hoa hồng\n5. Chèn liên kết đã tạo vào nội dung',
    linkText: 'Đi đến Naver Brand Connect',
    notice: 'Ứng dụng này sử dụng AI để nhận diện sản phẩm và tự động tạo liên kết tìm kiếm Naver Shopping. Để theo dõi hoa hồng chính xác, hãy sử dụng liên kết riêng được cấp bởi Brand Connect.',
  },
  flowTitle: 'Quy trình tạo nội dung',
  flowDesc: 'Tổng quan toàn bộ quy trình tạo nội dung có sẵn trong ứng dụng',
  flowSteps: [
    { num: 'BƯỚC 1', title: 'Chụp & Phân tích AI', desc: 'AI tự động nhận diện tên sản phẩm, danh mục và mức giá từ ảnh' },
    { num: 'BƯỚC 2', title: 'Khớp sản phẩm & Liên kết tiếp thị', desc: 'Tìm sản phẩm tương tự trên Naver/Coupang và tự tạo liên kết hoa hồng' },
    { num: 'BƯỚC 3', title: 'Thẻ short-form & Mẫu', desc: 'Tạo thẻ với giá và sticker đánh giá được ghép trên ảnh' },
    { num: 'BƯỚC 4', title: 'Carousel & Video short-form', desc: 'Chuyển nhiều thẻ thành carousel trượt hoặc video short-form' },
    { num: 'BƯỚC 5', title: 'Tạo nội dung truyện tranh', desc: 'AI tạo kịch bản truyện tranh 4 khung sử dụng sản phẩm và hoàn thiện thành ảnh' },
    { num: 'BƯỚC 6', title: 'Chia sẻ & Theo dõi doanh thu', desc: 'Chia sẻ lên Instagram, TikTok, KakaoTalk và theo dõi lượt nhấp và doanh thu' },
    { num: 'BƯỚC 7', title: 'Dự đoán viral & Phân tích xu hướng', desc: 'Dự đoán tiềm năng viral của nội dung và tối ưu hóa với khớp xu hướng' },
  ],
  featuresTitle: 'Tổng quan tính năng',
  featuresDesc: undefined,
  featureSections: [
    {
      title: '',
      items: [
        { iconKey: 'Camera', title: 'Chụp sản phẩm & Khớp mua sắm', desc: 'Chụp giày, đèn, quần áo — AI nhận diện sản phẩm và khớp trên Naver Shopping' },
        { iconKey: 'Link2', title: 'Tự động tạo liên kết tiếp thị', desc: 'Tạo ngay liên kết hoa hồng bằng ID đối tác của bạn' },
        { iconKey: 'Sparkles', title: 'Tự động hoàn thành mẫu short-form', desc: 'Tự động tạo thẻ với sticker giá và đánh giá trên ảnh' },
        { iconKey: 'Send', title: 'Chia sẻ SNS một chạm (Accordion)', desc: 'Nhấn chia sẻ để mở rộng nút Naver Clip, Naver TV, Instagram, KakaoTalk, Blog' },
        { iconKey: 'Wand2', title: 'AI gợi ý phong cách', desc: 'AI gợi ý phong cách thiết kế phù hợp sản phẩm và áp dụng một chạm' },
        { iconKey: 'Target', title: 'Dự đoán viral & Mô phỏng persona', desc: 'Dự đoán tiềm năng viral và mô phỏng phản ứng từ góc nhìn khách hàng mục tiêu' },
        { iconKey: 'Globe', title: 'Bản địa hóa toàn cầu & Xuất đa nền tảng', desc: 'Bản địa hóa copy marketing sang nhiều ngôn ngữ và tạo ảnh tối ưu cho từng nền tảng' },
        { iconKey: 'TrendingUp', title: 'Khớp xu hướng & Copy xu hướng', desc: 'Tự động khớp từ khóa xu hướng SNS với sản phẩm để tạo copy thời sự' },
        { iconKey: 'Store', title: 'Thông tin cửa hàng & Tích hợp offline', desc: 'Đăng ký thông tin cửa hàng và tự động đưa vào thẻ short-form và nội dung chia sẻ' },
        { iconKey: 'Clapperboard', title: 'Chế độ chụp AR', desc: 'Chụp sản phẩm với hiệu ứng AR thời gian thực' },
        { iconKey: 'Music2', title: 'Sound Punch (Hiệu ứng âm thanh)', desc: 'Thu âm hiệu ứng meme phổ biến và thêm vào truyện tranh short-form theo thời điểm' },
      ],
    },
  ],
  usageTitle: 'Hướng dẫn tạo nội dung',
  usageDesc: 'Nhấn từng tính năng để xem hướng dẫn chi tiết',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: 'Tạo thẻ short-form (mẫu)', steps: [
          'Nhấn nút "Thẻ short-form" trên màn hình kết quả',
          'Đánh giá và giá do AI cung cấp được tự động ghép làm sticker trên ảnh',
          'Chọn phong cách (Tạp chí/Đậm/Tối giản/Feed) để thay đổi thiết kế',
          'Bạn có thể chỉnh sửa trực tiếp văn bản giá, đánh giá và hashtag',
          'Sử dụng nút xóa nền để có ảnh sản phẩm sạch',
          'Thay đổi chủ đề màu sắc để phù hợp với thương hiệu',
          'Lưu thẻ hoàn chỉnh hoặc chia sẻ trực tiếp',
        ]},
        { iconKey: 'LayoutTemplate', title: 'Tạo carousel (nhiều slide)', steps: [
          'Nhấn nút "Carousel" trên màn hình kết quả',
          'Sắp xếp nhiều sản phẩm hoặc ảnh nhiều góc độ theo thứ tự',
          'Mỗi slide có thể nhập văn bản và giá riêng',
          'Kéo để thay đổi thứ tự slide',
          'Áp dụng phong cách thống nhất cho tất cả slide',
          'Tự động điều chỉnh kích thước dọc cho bài đăng Instagram',
          'Lưu carousel hoàn chỉnh thành ảnh hoặc chia sẻ',
        ]},
        { iconKey: 'Film', title: 'Tạo video short-form (clip)', steps: [
          'Nhấn nút "Video short-form" trên màn hình kết quả',
          'Ảnh sản phẩm và văn bản được ghép thành video ngắn',
          'Hiệu ứng chuyển cảnh và hoạt ảnh văn bản được tự động áp dụng',
          'Chọn nhạc nền (Sôi động/Êm dịu/Năng lượng/Không) và hiệu ứng chuyển động (Kenburns/Zoom/Pan)',
          'Cài đặt nâng cao cho phép đổi tỷ lệ khung hình (dọc/ngang/vuông) và phong cách mẫu',
          'Bật chế độ lai (ảnh→truyện tranh) để áp dụng hiệu ứng truyện tranh ở nửa sau',
          'Chọn độ dài video (10s/15s/20s/30s) — mặc định 15s',
          'Tối ưu tỷ lệ dọc (9:16) cho TikTok/Instagram Reels/YouTube Shorts',
          'Lưu video hoàn chỉnh vào thư viện hoặc đám mây rồi tải lên từng nền tảng',
        ]},
        { iconKey: 'BookOpen', title: 'Tạo truyện tranh short-form (video truyện)', steps: [
          'Nhấn nút "Truyện tranh short-form" trên màn hình kết quả',
          'AI tự động tạo kịch bản truyện tranh sử dụng sản phẩm (đơn/2 khung/3 khung)',
          'Bạn có thể chỉnh sửa trực tiếp hội thoại và tình huống từng khung',
          'Chọn phong cách webtoon (Instatoon/B-grade/Truyện ẩm thực/Comic Mỹ/Phong cách Ghibli)',
          'Chọn giọng AI (Trẻ 20s/Trầm tĩnh/B-grade) để lồng tiếng',
          'Trong cài đặt nâng cao, chọn độ dài video (10s/15s/20s/30s) — tự gợi ý theo số khung',
          'Thêm lồng tiếng AI, overlay biểu cảm và bình luận theo MBTI',
          'Bật chế độ episode cho cốt truyện "Ngày 1–Ngày 3–Ngày 7"',
          'Thêm hiệu ứng âm thanh truyện tranh theo thời điểm với Sound Punch',
          'Hiệu ứng âm thanh được tự khớp theo cảm xúc (Ngạc nhiên: Ôi!, Vui: Yay~, Tự tin: Thumbs up!)',
          'Lưu truyện tranh short-form hoàn chỉnh hoặc chia sẻ trực tiếp lên TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'Film', title: 'Tạo timeline short-form (series episode)', steps: [
          'Nhấn nút "Truyện tranh short-form" trên màn hình kết quả',
          'Bật "Chế độ episode" trong cài đặt nâng cao',
          'Truyện tranh short-form theo cốt truyện ngày 1–3–7 được tự động sản xuất',
          'Bạn có thể chỉnh sửa kịch bản và hội thoại từng ngày',
          'Phong cách webtoon và lồng tiếng có thể áp dụng cùng nhau',
          'Lưu timeline short-form hoàn chỉnh hoặc chia sẻ lên TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'PenLine', title: 'Copywriting (tự động tạo văn bản)', steps: [
          'Nhấn nút "Viết copy" trên màn hình kết quả',
          'AI tạo văn bản marketing dựa trên kết quả phân tích sản phẩm',
          'Chọn tông giọng (Casual/Chuyên nghiệp/Cảm xúc/Hài hước)',
          'Sao chép copy đã tạo hoặc chỉnh sửa trước khi dùng',
          'Gợi ý hashtag cũng được cung cấp',
          'So sánh nhiều phiên bản copy và chọn cái tốt nhất',
        ]},
        { iconKey: 'Type', title: 'Đánh giá & Nhận xét một dòng', steps: [
          'Nhấn nút "Nhập đánh giá" trên màn hình kết quả',
          'Tự viết nhận xét một dòng hoặc nhận gợi ý AI',
          'Đánh giá đã viết được tự động đưa vào thẻ short-form và carousel',
          'Chỉnh sửa đánh giá sẽ cập nhật tất cả nội dung liên kết',
        ]},
        { iconKey: 'Scissors', title: 'Xóa nền & Chỉnh sửa ảnh', steps: [
          'Nhấn nút "Xóa nền" trên màn hình kết quả',
          'AI tự động phát hiện và xóa nền sản phẩm',
          'Lưu dưới dạng ảnh nền trong suốt để sử dụng đa dạng',
          'Ảnh đã xóa nền được tự động áp dụng vào thẻ, carousel và truyện tranh',
          'Bạn có thể tự đổi màu nền nếu cần',
        ]},
        { iconKey: 'Wand2', title: 'AI gợi ý phong cách', steps: [
          'Kiểm tra phần "AI phong cách" trên màn hình kết quả',
          'AI tạo nhiều cảnh thử đồ dựa trên ảnh sản phẩm',
          'Tối ưu cho sản phẩm có thể mặc như quần áo và phụ kiện',
          'Nhấn ảnh thử đồ để phóng to',
          'Dùng nút "Dùng ảnh này" để đặt ảnh thử đồ làm ảnh chính',
          'Lưu ảnh đã tạo hoặc dùng trong thẻ short-form',
        ]},
        { iconKey: 'Layers', title: 'Thư viện cắt ảo', steps: [
          'Kiểm tra phần "Cắt ảo" trên màn hình kết quả',
          'AI tạo cắt như thể sản phẩm được chụp từ nhiều góc度和 nền khác nhau',
          'Tự động ghép với nền studio, thiên nhiên, cửa hàng, gradient',
          'Nhấn cắt đã tạo để phóng to và xác nhận',
          'Dùng nút "Dùng ảnh này" để đặt cắt ưa thích làm ảnh chính',
          'Nhiều cắt có thể dùng trong carousel hoặc video short-form',
        ]},
        { iconKey: 'Wand2', title: 'AI gợi ý phong cách', steps: [
          'Kiểm tra phần "AI phong cách" trên màn hình kết quả',
          'AI gợi ý phong cách thiết kế phù hợp danh mục và không khí sản phẩm',
          'Nhấn phong cách gợi ý để áp dụng ngay vào thẻ short-form',
          'Đổi phong cách sẽ tự điều chỉnh bố cục văn bản, màu sắc, font chữ',
          'Chọn phong cách ưng ý sẽ áp dụng nhất quán cho mọi nội dung',
        ]},
        { iconKey: 'Target', title: 'Dự đoán viral', steps: [
          'Kiểm tra phần "Dự đoán viral" trên màn hình kết quả',
          'AI dự đoán tiềm năng viral của nội dung bằng điểm số',
          'Điểm dự đoán đánh giá sức hút, phù hợp xu hướng và khả năng chia sẻ',
          'Nhấn gợi ý cải thiện để xem mẹo tăng điểm',
          'Chỉnh sửa copy hoặc phong cách theo gợi ý sẽ tính lại điểm dự đoán',
        ]},
        { iconKey: 'Users', title: 'Mô phỏng persona', steps: [
          'Kiểm tra phần "Mô phỏng persona" trên màn hình kết quả',
          'Chọn persona khách hàng mục tiêu (tuổi, giới tính, sở thích)',
          'AI mô phỏng cách persona đó đánh giá sản phẩm',
          'Xem phản ứng dự kiến, xác suất mua và điểm appeal chính',
          'Dùng kết quả mô phỏng để tối ưu copy marketing',
        ]},
        { iconKey: 'Globe', title: 'Bản địa hóa toàn cầu', steps: [
          'Kiểm tra phần "Bản địa hóa toàn cầu" trên màn hình kết quả',
          'Dịch copy marketing sang tiếng Anh, Nhật, Trung, v.v.',
          'Không chỉ dịch — bản địa hóa theo văn hóa và xu hướng SNS từng nước',
          'Hashtag phổ biến và tông marketing theo quốc gia được tự động áp dụng',
          'Nhấn copy đã dịch để sao chép vào clipboard',
          'Nhanh chóng tạo nội dung tối ưu cho nền tảng từng nước khi mở rộng ra nước ngoài',
        ]},
        { iconKey: 'Shuffle', title: 'Xuất đa nền tảng', steps: [
          'Kiểm tra phần "Xuất đa nền tảng" trên màn hình kết quả',
          'Tạo ảnh tối ưu cho Instagram, TikTok và YouTube Shorts cùng lúc',
          'Tỷ lệ khung hình và vị trí văn bản tối ưu được tự điều chỉnh cho từng nền tảng',
          'Hashtag và phong cách caption được tự áp dụng cho từng nền tảng',
          'Lưu ảnh đã tạo riêng cho từng nền tảng',
          'Tối đa hóa tiếp cận với tải lên đồng thời cả ba nền tảng',
        ]},
        { iconKey: 'TrendingUp', title: 'Khớp xu hướng', steps: [
          'Kiểm tra phần "Khớp xu hướng" trên màn hình kết quả',
          'AI tự khớp từ khóa xu hướng SNS hiện tại với sản phẩm',
          'Nhấn từ khóa xu hướng thời gian thực để tự tạo copy marketing liên quan',
          'Gợi ý hashtag theo xu hướng cũng được cung cấp',
          'Tạo nội dung thời sự để tăng tiếp cận thuật toán',
        ]},
        { iconKey: 'Store', title: 'Thông tin cửa hàng', steps: [
          'Kiểm tra phần "Thông tin cửa hàng" trên màn hình kết quả',
          'Đăng ký thông tin cửa hàng offline (địa chỉ, giờ mở cửa, số điện thoại)',
          'Thông tin đã đăng ký được tự động đưa vào thẻ short-form và nội dung chia sẻ',
          'Khách hàng có thể kiểm tra vị trí cửa hàng trực tiếp từ nội dung',
          'Sử dụng cho marketing tích hợp online-offline',
        ]},
        { iconKey: 'Video', title: 'Nhập video', steps: [
          'Sử dụng tính năng "Nhập video" trên màn hình kết quả',
          'Nhập video đã quay trước và chuyển thành nội dung short-form',
          'Tự động trích xuất đoạn chính từ video để tạo short-form',
          'Thêm văn bản và sticker vào đoạn đã trích xuất',
          'Tái sử dụng tài sản video hiện có để rút ngắn thời gian tạo nội dung',
        ]},
      ],
    },
  ],
  platformTitle: 'Hướng dẫn tải lên theo nền tảng',
  platformDesc: 'Hướng dẫn từng bước tải video short-form đã hoàn thành lên từng nền tảng',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'Tải lên TikTok', steps: [
          'Nhấn nút chia sẻ "TikTok" trên màn hình hoàn chỉnh hoặc dùng video đã lưu vào thư viện',
          'Mở ứng dụng TikTok và nhấn nút "+" ở giữa dưới',
          'Chọn video short-form đã lưu từ thư viện',
          'Thêm văn bản, sticker và hiệu ứng trên màn hình chỉnh sửa (tùy chọn)',
          'Nhấn Tiếp và nhập tiêu đề video (caption)',
          'Thêm hashtag liên quan (sử dụng hashtag gợi ý từ ứng dụng)',
          'Liên kết tiếp thị hiệu quả nhất trong bio TikTok hoặc bình luận ghim',
          'Đặt hiển thị "Công khai" và nhấn Đăng',
        ]},
        { iconKey: 'Instagram', title: 'Tải lên Instagram Reels', steps: [
          'Nhấn nút chia sẻ "Instagram" hoặc dùng video đã lưu vào thư viện',
          'Mở Instagram, nhấn "+" và chọn "Reels"',
          'Chọn video short-form đã lưu từ thư viện',
          'Thêm nhạc: Chọn từ nhạc built-in Instagram hoặc audio video gốc',
          'Thêm sticker văn bản nếu cần (hiện tên sản phẩm hoặc hook trên màn hình)',
          'Nhấn Tiếp và nhập caption',
          'Thêm liên kết tiếp thị trực tiếp trong caption hoặc qua link bio',
          'Thêm hashtag liên quan, đặt "Công khai" và nhấn Chia sẻ',
          'Sau khi đăng Reel, đăng ký liên kết tiếp thị trong nút "Link" của profile để tăng tỷ lệ nhấp',
        ]},
        { iconKey: 'Youtube', title: 'Tải lên YouTube Shorts', steps: [
          'Nhấn nút chia sẻ "Shorts" hoặc dùng video đã lưu vào thư viện',
          'Mở YouTube, nhấn "+" và chọn "Tạo Short"',
          'Chọn video short-form đã lưu từ thư viện',
          'Thêm văn bản, bộ lọc và nhạc trên màn hình chỉnh sửa (tùy chọn)',
          'Nhấn Tiếp và nhập tiêu đề video',
          'Bao gồm hashtag #Shorts trong tiêu đề để hiển thị tốt hơn trên Shorts feed',
          'Thêm liên kết tiếp thị trong phần mô tả hoặc link kênh',
          'Đặt hiển thị "Công khai" và nhấn Tải lên',
        ]},
        { iconKey: 'Share2', title: 'Chia sẻ Naver Clip & KakaoTalk', steps: [
          'Naver Clip: Nhấn nút "Chia sẻ" để sao chép văn bản quảng bá và ảnh vào clipboard',
          'Mở ứng dụng Naver Clip hoặc Naver TV và chọn Tạo clip mới',
          'Tải lên video đã lưu và dán văn bản quảng bá đã sao chép',
          'KakaoTalk: Dùng nút chia sẻ để gửi ảnh và liên kết cùng trong tin nhắn',
          'Chia sẻ video và liên kết tiếp thị trong kênh KakaoTalk hoặc phòng chat mở để thúc đẩy nhấp trực tiếp',
        ]},
        { iconKey: 'Lightbulb', title: 'Chiến lược tải lên đa nền tảng cùng lúc', steps: [
          'Tải một video short-form lên TikTok, Instagram Reels và YouTube Shorts để tăng 3 lần tiếp cận',
          'Viết caption và hashtag hơi khác cho từng nền tảng — giúp thuật toán',
          'Dùng hashtag xu hướng cho TikTok, hashtag sản phẩm cho Instagram và #Shorts cho YouTube',
          'Đăng ký cùng một liên kết tiếp thị trong bio của từng nền tảng để dễ quản lý',
          'Thời gian tải lên tốt nhất là 6–10 giờ tối (giờ địa phương) để có tỷ lệ xem cao nhất',
          'Đặt độ dài video 15–30 giây để đủ thời gian xem và thân thiện với thuật toán',
        ]},
      ],
    },
  ],
  soundTitle: 'Hướng dẫn Sound Punch (Hiệu ứng âm thanh)',
  soundDesc: 'Thu âm hiệu ứng meme phổ biến và thêm vào truyện tranh short-form theo thời điểm',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'Cách dùng trình chỉnh sửa Sound Punch', steps: [
          'Mở rộng "Tùy chọn nâng cao" trong trình tạo truyện tranh short-form',
          'Bật toggle "Chỉnh sửa Sound Punch" (chỉ trên trình duyệt web)',
          'Nhấn nút thu âm và tạo âm thanh vào mic — sóng âm hiển thị thời gian thực',
          'Âm thanh lớn được tự động phát hiện và marker hiệu ứng được thêm (Bang, Zoom, Comic, v.v.)',
          'Bạn cũng có thể chỉ định hiệu ứng bằng lệnh giọng nói ("Bang", "Zoom in", "Comic", v.v.)',
          'Dừng thu âm để xem marker trên timeline và phát lại',
          'Nhấn marker để đổi loại hiệu ứng hoặc xóa',
          'Hiệu ứng đã thu được tự động ghép vào video khi tạo truyện tranh short-form',
          'Trên mobile, hiển thị thông báo "Chỉ có thể sử dụng trên trình duyệt web"',
        ]},
      ],
    },
  ],
  helpTitle: 'Trợ giúp',
  helpItems: [
    { iconKey: 'Info', title: 'Cách sử dụng', desc: 'Chụp hoặc tải ảnh lên và AI sẽ phân tích sản phẩm. Sử dụng khớp mua sắm, thẻ short-form và chia sẻ từ màn hình kết quả.' },
    { iconKey: 'Link2', title: 'Áp dụng liên kết hoa hồng', desc: "Dùng nút 'Dán liên kết hoa hồng' trên màn hình kết quả để áp dụng liên kết Brand Connect. Tự động phản ánh vào chia sẻ và thẻ." },
  ],
  feedbackTitle: 'Phản hồi & Báo cáo lỗi',
  feedbackDesc: 'Hãy cho chúng tôi biết về bất kỳ bất tiện hoặc lỗi nào. Phản hồi của bạn giúp ứng dụng tốt hơn.',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: 'Gửi phản hồi', desc: 'Để lại phản hồi qua Google Form' },
    { iconKey: 'Bug', title: 'Báo cáo lỗi & Open chat', desc: 'Nhận hỗ trợ nhanh trong phòng chat mở KakaoTalk' },
  ],
  footer: 'ShortConnect — AI commerce all-in-one cho nhà bán online và offline',
  onboardingTitle: 'Xem lại hướng dẫn ứng dụng',
  onboardingDesc: 'Nhấn để xem lại hướng dẫn ban đầu',
};

const es: GuideContent = {
  naverSection: {
    title: 'Guía de Naver Shopping Connect',
    desc: 'Naver Shopping Connect requiere registrarse como creador en Brand Connect (brandconnect.naver.com) y generar enlaces de comisión dedicados para cada producto. Solo ingresar un ID no creará enlaces de seguimiento automáticos.',
    guideTitle: 'Cómo usar',
    guideSteps: '1. Regístrate como creador en Naver Brand Connect\n2. Vincula tu canal (blog/Instagram/YouTube)\n3. Busca productos que quieras promocionar\n4. Haz clic en el botón de generación de enlaces para obtener tu enlace de comisión\n5. Inserta el enlace generado en tu contenido',
    linkText: 'Ir a Naver Brand Connect',
    notice: 'Esta app usa IA para identificar productos y generar automáticamente enlaces de búsqueda en Naver Shopping. Para un seguimiento preciso de comisiones, usa los enlaces individuales emitidos por Brand Connect.',
  },
  flowTitle: 'Flujo de creación de contenido',
  flowDesc: 'Vista general del flujo completo de creación de contenido disponible en la app',
  flowSteps: [
    { num: 'PASO 1', title: 'Captura y Análisis IA', desc: 'La IA identifica automáticamente nombre, categoría y rango de precio desde fotos' },
    { num: 'PASO 2', title: 'Coincidencia y Enlaces Afiliados', desc: 'Encuentra el mismo producto en Naver/Coupang y genera enlaces de comisión automáticamente' },
    { num: 'PASO 3', title: 'Tarjetas Short-form y Plantillas', desc: 'Crea tarjetas con stickers de precio y reseña sobre fotos' },
    { num: 'PASO 4', title: 'Carrusel y Video Short-form', desc: 'Convierte múltiples tarjetas en carrusel o video short-form' },
    { num: 'PASO 5', title: 'Creación de Contenido Cómic', desc: 'La IA genera escenarios cómicos de 4 paneles usando tu producto' },
    { num: 'PASO 6', title: 'Compartir y Seguimiento de Ingresos', desc: 'Comparte en Instagram, TikTok, KakaoTalk y rastrea clics e ingresos' },
    { num: 'PASO 7', title: 'Prueba Virtual y Galería de Cortes', desc: 'La IA genera cortes de prueba virtual y múltiples ángulos desde fotos del producto' },
    { num: 'PASO 8', title: 'Predicción Viral y Análisis de Tendencias', desc: 'Predice el potencial viral y optimiza con coincidencia de tendencias' },
  ],
  featuresTitle: 'Resumen de Funciones',
  featuresDesc: undefined,
  featureSections: [
    {
      title: '',
      items: [
        { iconKey: 'Camera', title: 'Captura de Producto y Coincidencia', desc: 'Fotografía zapatos, iluminación, ropa — la IA identifica el producto y lo coincide en Naver Shopping' },
        { iconKey: 'Link2', title: 'Generación Automática de Enlaces', desc: 'Crea al instante enlaces de comisión usando tu ID de socio' },
        { iconKey: 'Sparkles', title: 'Autocompletado de Plantillas', desc: 'Genera automáticamente tarjetas con stickers de precio y reseña sobre fotos' },
        { iconKey: 'Send', title: 'Compartir SNS con Un Toque (Acordeón)', desc: 'Toca compartir para expandir botones de Naver Clip, Naver TV, Instagram, KakaoTalk y Blog' },
        { iconKey: 'Shirt', title: 'Prueba Virtual y Galería de Cortes', desc: 'La IA genera varias escenas de prueba y cortes de ángulos desde fotos del producto' },
        { iconKey: 'Wand2', title: 'Recomendación de Estilo IA', desc: 'La IA recomienda estilos de diseño y los aplica con un toque' },
        { iconKey: 'Target', title: 'Predicción Viral y Simulador de Persona', desc: 'Predice el potencial viral y simula reacciones de clientes objetivo' },
        { iconKey: 'Globe', title: 'Localización Global y Export Multi-Plataforma', desc: 'Localiza el copy de marketing a varios idiomas y genera imágenes optimizadas por plataforma' },
        { iconKey: 'TrendingUp', title: 'Coincidencia de Tendencias y Copy', desc: 'Coincide automáticamente palabras clave en tendencia con productos para copy oportuno' },
        { iconKey: 'Store', title: 'Info de Tienda e Integración Offline', desc: 'Registra info de tienda y se incluye automáticamente en tarjetas y contenido compartido' },
        { iconKey: 'Clapperboard', title: 'Modo de Captura AR', desc: 'Captura productos con efectos AR en tiempo real' },
        { iconKey: 'Music2', title: 'Sound Punch (Efectos de Sonido)', desc: 'Graba efectos de meme populares y añádelos a cómics short-form por tiempo' },
      ],
    },
  ],
  usageTitle: 'Guía de Creación de Contenido',
  usageDesc: 'Toca cada función para ver instrucciones detalladas',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: 'Crear Tarjetas Short-form (Plantillas)', steps: [
          'Toca el botón "Tarjeta Short-form" en la pantalla de resultados',
          'La reseña y precio proporcionados por IA se componen automáticamente como stickers',
          'Elige un estilo (Revista/Bold/Minimal/Feed) para cambiar el diseño',
          'Puedes editar precio, reseña y texto de hashtag directamente',
          'Usa el botón de eliminar fondo para una imagen limpia del producto',
          'Cambia temas de color para coincidir con tu marca',
          'Guarda la tarjeta completada o compártela directamente',
        ]},
        { iconKey: 'LayoutTemplate', title: 'Crear Carrusel (Multi-Diapositiva)', steps: [
          'Toca el botón "Carrusel" en la pantalla de resultados',
          'Organiza múltiples productos o fotos de múltiples ángulos en orden',
          'Cada diapositiva puede tener texto y precio individual',
          'Arrastra para cambiar el orden de las diapositivas',
          'Aplica un estilo unificado a todas las diapositivas',
          'Se ajusta automáticamente a tamaño vertical para Instagram',
          'Guarda el carrusel completado como imagen o compártelo',
        ]},
        { iconKey: 'Film', title: 'Crear Video Short-form (Clip)', steps: [
          'Toca el botón "Video Short-form" en la pantalla de resultados',
          'Fotos del producto y texto se unen en un video corto',
          'Efectos de transición y animaciones de texto se aplican automáticamente',
          'Elige música de fondo (Animado/Tranquilo/Energético/Ninguno) y efectos de movimiento (Kenburns/Zoom/Pan)',
          'Configuración avanzada permite cambiar relación de aspecto y estilo de plantilla',
          'Habilita modo híbrido (foto→cómic) para efecto cómic en la segunda mitad',
          'Elige duración de video (10s/15s/20s/30s) — predeterminado 15s',
          'Optimizado para relación vertical (9:16) para TikTok/Instagram Reels/YouTube Shorts',
          'Guarda el video en galería o nube y luego súbelo a cada plataforma',
        ]},
        { iconKey: 'BookOpen', title: 'Crear Cómic Short-form (Video Cómic)', steps: [
          'Toca el botón "Cómic Short-form" en la pantalla de resultados',
          'La IA genera automáticamente un escenario cómico usando tu producto (simple/2 paneles/3 paneles)',
          'Puedes editar diálogos y situaciones de cada panel',
          'Elige estilo webtoon (Instatoon/B-grade/Cómic gastronómico/Cómic americano/Estilo Ghibli)',
          'Elige voz de narrador IA (Joven brillante/Narración tranquila/Acento B-grade) para doblaje',
          'En configuración avanzada, selecciona duración (10s/15s/20s/30s) — recomendación automática según paneles',
          'Añade doblaje IA, overlay de emociones y comentario MBTI',
          'Habilita modo episodio para historia "Día 1–Día 3–Día 7"',
          'Añade efectos de sonido cómico por tiempo con Sound Punch',
          'Los efectos se emparejan automáticamente por emoción (Sorpresa: ¡Guau!, Feliz: ¡Yay~, Confianza: ¡Pulgar arriba!)',
          'Guarda el cómic completado o compártelo a TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'Film', title: 'Crear Timeline Short-form (Serie de Episodios)', steps: [
          'Toca el botón "Cómic Short-form" en la pantalla de resultados',
          'Habilita "Modo Episodio" en configuración avanzada',
          'Se produce automáticamente un cómic short-form con historia de línea temporal',
          'Puedes editar escenario y diálogo de cada día',
          'Estilo webtoon y doblaje se pueden aplicar juntos',
          'Guarda o comparte el timeline short-form a TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'PenLine', title: 'Copywriting (Generación Automática de Texto)', steps: [
          'Toca el botón "Escribir Copy" en la pantalla de resultados',
          'La IA genera copy de marketing basado en el análisis del producto',
          'Elige tono (Casual/Profesional/Emocional/Humor)',
          'Copia el copy generado o edítalo antes de usar',
          'También se proporcionan recomendaciones de hashtag',
          'Compara múltiples versiones y elige la mejor',
        ]},
        { iconKey: 'Type', title: 'Reseña y Comentario de Una Línea', steps: [
          'Toca el botón "Entrar Reseña" en la pantalla de resultados',
          'Escribe tu propia reseña o recibe recomendaciones de IA',
          'Las reseñas se reflejan automáticamente en tarjetas y carruseles',
          'Editar una reseña actualiza todo el contenido vinculado',
        ]},
        { iconKey: 'Scissors', title: 'Eliminación de Fondo y Edición', steps: [
          'Toca el botón "Eliminar Fondo" en la pantalla de resultados',
          'La IA detecta y elimina automáticamente el fondo del producto',
          'Se guarda como imagen de fondo transparente para uso versátil',
          'La imagen se aplica automáticamente a tarjetas, carruseles y cómics',
          'Puedes cambiar manualmente el color de fondo si es necesario',
        ]},
        { iconKey: 'Shirt', title: 'Galería de Prueba Virtual', steps: [
          'Revisa la sección "Prueba Virtual" en la pantalla de resultados',
          'La IA genera varias escenas de prueba basadas en fotos del producto',
          'Optimizado para productos usables como ropa y accesorios',
          'Toca una imagen generada para ampliar',
          'Usa "Usar Esta Imagen" para establecerla como imagen principal',
          'Guarda imágenes o úsalas en tarjetas short-form',
        ]},
        { iconKey: 'Layers', title: 'Galería de Cortes Virtuales', steps: [
          'Revisa la sección "Corte Virtual" en la pantalla de resultados',
          'La IA genera cortes como si el producto se fotografiara desde varios ángulos y fondos',
          'Compone automáticamente con fondos de estudio, naturaleza, tienda, gradiente',
          'Toca un corte generado para ampliar y verificar',
          'Usa "Usar Esta Imagen" para establecer tu corte preferido como principal',
          'Múltiples cortes pueden usarse en carruseles o videos short-form',
        ]},
        { iconKey: 'Wand2', title: 'Recomendación de Estilo IA', steps: [
          'Revisa la sección "Estilo IA" en la pantalla de resultados',
          'La IA recomienda estilos que coinciden con la categoría y ambiente del producto',
          'Toca un estilo recomendado para aplicarlo instantáneamente',
          'Cambiar estilo ajusta automáticamente diseño, colores y fuentes',
          'Seleccionar un estilo lo aplica consistentemente en todo el contenido',
        ]},
        { iconKey: 'Target', title: 'Predicción Viral', steps: [
          'Revisa la sección "Predicción Viral" en la pantalla de resultados',
          'La IA predice el potencial viral del contenido como puntuación',
          'La puntuación evalúa poder de gancho, adecuación a tendencias y compartibilidad',
          'Toca sugerencias de mejora para consejos de aumento de puntuación',
          'Editar copy o estilo recalcula la puntuación de predicción',
        ]},
        { iconKey: 'Users', title: 'Simulador de Persona', steps: [
          'Revisa la sección "Simulador de Persona" en la pantalla de resultados',
          'Selecciona persona de cliente objetivo (edad, género, intereses)',
          'La IA simula cómo la persona evaluaría el producto',
          'Ve reacciones esperadas, probabilidad de compra y puntos clave de atractivo',
          'Usa resultados para optimizar tu copy de marketing',
        ]},
        { iconKey: 'Globe', title: 'Localización Global', steps: [
          'Revisa la sección "Localización Global" en la pantalla de resultados',
          'Traduce copy de marketing a inglés, japonés, chino, etc.',
          'No solo traducción — localizado a la cultura y tendencias SNS de cada país',
          'Hashtags populares y tono de marketing por país se reflejan automáticamente',
          'Toca copy traducido para copiar al portapapeles',
          'Crea rápidamente contenido optimizado para expansión internacional',
        ]},
        { iconKey: 'Shuffle', title: 'Exportación Multi-Plataforma', steps: [
          'Revisa la sección "Exportación Multi-Plataforma" en la pantalla de resultados',
          'Genera imágenes optimizadas para Instagram, TikTok y YouTube Shorts a la vez',
          'Relación de aspecto y posición de texto óptimas se ajustan por plataforma',
          'Hashtags y estilos de caption recomendados se aplican por plataforma',
          'Guarda imágenes individualmente para cada plataforma',
          'Maximiza exposición con subidas simultáneas a las tres plataformas',
        ]},
        { iconKey: 'TrendingUp', title: 'Coincidencia de Tendencias', steps: [
          'Revisa la sección "Coincidencia de Tendencias" en la pantalla de resultados',
          'La IA coincide automáticamente palabras clave en tendencia con tu producto',
          'Toca una palabra clave para generar copy de marketing relacionado',
          'Recomendaciones de hashtag coincidentes con tendencias también se proporcionan',
          'Crea contenido oportuno para aumentar exposición del algoritmo',
        ]},
        { iconKey: 'Store', title: 'Información de Mi Tienda', steps: [
          'Revisa la sección "Mi Tienda" en la pantalla de resultados',
          'Registra información de tienda física (dirección, horario, teléfono)',
          'La información se incluye automáticamente en tarjetas y contenido compartido',
          'Los clientes pueden verificar la ubicación directamente desde el contenido',
          'Úsalo para marketing integrado online-offline',
        ]},
        { iconKey: 'Video', title: 'Importación de Video', steps: [
          'Usa la función "Importar Video" en la pantalla de resultados',
          'Importa videos grabados previamente y conviértelos en contenido short-form',
          'Extrae automáticamente segmentos clave del video',
          'Añade texto y stickers a los segmentos extraídos',
          'Recicla activos de video existentes para acortar el tiempo de creación',
        ]},
      ],
    },
  ],
  platformTitle: 'Guía de Subida por Plataforma',
  platformDesc: 'Instrucciones paso a paso para subir videos short-form completados a cada plataforma',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'Subir a TikTok', steps: [
          'Toca el botón "TikTok" o usa un video guardado en galería',
          'Abre TikTok y toca el botón "+" en el centro inferior',
          'Selecciona el video short-form guardado de tu galería',
          'Añade texto, stickers y efectos (opcional)',
          'Toca Siguiente e ingresa el título (caption)',
          'Añade hashtags relevantes (usa los recomendados por la app)',
          'Los enlaces afiliados son más efectivos en el bio o comentarios fijados',
          'Configura visibilidad como "Público" y toca Publicar',
        ]},
        { iconKey: 'Instagram', title: 'Subir a Instagram Reels', steps: [
          'Toca el botón "Instagram" o usa un video guardado en galería',
          'Abre Instagram, toca "+" y selecciona "Reels"',
          'Selecciona el video guardado de tu galería',
          'Añade música de Instagram o audio original del video',
          'Añade stickers de texto si es necesario (nombre del producto o hook)',
          'Toca Siguiente e ingresa el caption',
          'Añade enlaces afiliados en el caption o vía bio',
          'Añade hashtags, configura como "Público" y toca Compartir',
          'Registra el enlace afiliado en el botón "Link" del perfil para mayor clic',
        ]},
        { iconKey: 'Youtube', title: 'Subir a YouTube Shorts', steps: [
          'Toca el botón "Shorts" o usa un video guardado en galería',
          'Abre YouTube, toca "+" y selecciona "Crear Short"',
          'Selecciona el video guardado de tu galería',
          'Añade texto, filtros y música (opcional)',
          'Toca Siguiente e ingresa el título',
          'Incluye #Shorts en el título para mejor exposición',
          'Añade enlaces en la descripción o perfil del canal',
          'Configura como "Público" y toca Subir',
        ]},
        { iconKey: 'Share2', title: 'Compartir en Naver Clip y KakaoTalk', steps: [
          'Naver Clip: Toca "Compartir" para copiar texto e imagen al portapapeles',
          'Abre Naver Clip o Naver TV y selecciona Crear nuevo clip',
          'Sube el video guardado y pega el texto copiado',
          'KakaoTalk: Usa compartir para enviar imagen y enlace en un mensaje',
          'Comparte video y enlaces en canales o chats abiertos de KakaoTalk',
        ]},
        { iconKey: 'Lightbulb', title: 'Estrategia de Subida Multi-Plataforma Simultánea', steps: [
          'Subir un video a TikTok, Instagram Reels y YouTube Shorts triplica la exposición',
          'Escribe captions y hashtags ligeramente diferentes por plataforma',
          'Usa hashtags de tendencia para TikTok, de producto para Instagram y #Shorts para YouTube',
          'Registra el mismo enlace en el bio de cada plataforma para fácil gestión',
          'El mejor horario es 6–10 PM (hora local) para mayor audiencia',
          'Configura duración de 15–30 segundos para tiempo de visualización suficiente',
        ]},
      ],
    },
  ],
  soundTitle: 'Guía de Sound Punch (Efectos de Sonido)',
  soundDesc: 'Graba efectos de meme populares y añádelos a cómics short-form por tiempo',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'Uso del Editor Sound Punch', steps: [
          'Expande "Opciones Avanzadas" en el generador de cómics',
          'Habilita "Edición de Sound Punch" (solo navegador web)',
          'Presiona grabar y haz sonidos — las ondas se muestran en tiempo real',
          'Sonidos fuertes se detectan automáticamente y se añaden marcadores',
          'Especifica efectos con comandos de voz ("Bang", "Zoom", "Comic")',
          'Detén la grabación para ver marcadores y reproducir',
          'Toca un marcador para cambiar o eliminar el efecto',
          'Los efectos grabados se componen automáticamente en el video',
          'En móvil se muestra "Solo disponible en navegador web"',
        ]},
      ],
    },
  ],
  helpTitle: 'Ayuda',
  helpItems: [
    { iconKey: 'Info', title: 'Cómo usar', desc: 'Toma o sube una foto y la IA analizará el producto. Usa coincidencia, tarjetas y compartir desde la pantalla de resultados.' },
    { iconKey: 'Link2', title: 'Aplicar Enlaces de Comisión', desc: "Usa 'Pegar mi enlace de comisión' en la pantalla de resultados para aplicar tu enlace de Brand Connect." },
  ],
  feedbackTitle: 'Comentarios y Reporte de Errores',
  feedbackDesc: 'Cuéntanos sobre inconvenientes o errores. Tus comentarios mejoran la app.',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: 'Enviar Comentarios', desc: 'Deja comentarios vía Google Form' },
    { iconKey: 'Bug', title: 'Reporte de Errores y Chat Abierto', desc: 'Obtén ayuda rápida en el chat abierto de KakaoTalk' },
  ],
  footer: 'ShortConnect — AI commerce todo-en-uno para vendedores online y offline',
  onboardingTitle: 'Ver Recorrido de la App',
  onboardingDesc: 'Toca para ver la guía inicial nuevamente',
};

const zh: GuideContent = {
  naverSection: {
    title: 'Naver Shopping Connect 指南',
    desc: 'Naver Shopping Connect 需要在 Brand Connect (brandconnect.naver.com) 注册为创作者后，为每个产品单独生成专属佣金链接。仅输入 ID 无法创建自动追踪链接。',
    guideTitle: '使用方法',
    guideSteps: '1. 在 Naver Brand Connect 注册为创作者\n2. 关联频道（博客/Instagram/YouTube）\n3. 搜索要推广的产品\n4. 点击链接生成按钮获取佣金链接\n5. 将生成的链接插入内容中',
    linkText: '前往 Naver Brand Connect',
    notice: '本应用使用 AI 识别产品并自动生成 Naver Shopping 搜索链接。如需精确佣金追踪，请使用 Brand Connect 发行的个人链接。',
  },
  flowTitle: '内容制作流程',
  flowDesc: '一览应用中可制作的内容全流程',
  flowSteps: [
    { num: '步骤 1', title: '拍摄 & AI 分析', desc: '拍摄商品后 AI 自动识别产品名、类别和价格区间' },
    { num: '步骤 2', title: '购物匹配 & 联盟链接', desc: '在 Naver/Coupang 找到同款商品并自动生成联盟佣金链接' },
    { num: '步骤 3', title: '短频卡片 & 模板', desc: '在照片上合成价格和评论贴纸制作卡片' },
    { num: '步骤 4', title: '轮播 & 短频视频', desc: '将多张卡片制作成滑动画轮播或短频视频' },
    { num: '步骤 5', title: '漫画内容制作', desc: 'AI 用产品生成四格漫画剧本并完成图像' },
    { num: '步骤 6', title: '分享 & 收益追踪', desc: '分享到 Instagram、TikTok、KakaoTalk 并追踪点击和收益' },
    { num: '步骤 7', title: '虚拟试穿 & 切割画廊', desc: 'AI 从产品照片生成虚拟试穿和多角度切割' },
    { num: '步骤 8', title: '病毒预测 & 趋势分析', desc: '预测内容的病毒潜力并通过趋势匹配优化' },
  ],
  featuresTitle: '功能介绍',
  featuresDesc: undefined,
  featureSections: [
    {
      title: '',
      items: [
        { iconKey: 'Camera', title: '实物拍摄 & 购物匹配', desc: '拍摄鞋、灯、衣服等，AI 识别产品并匹配 Naver Shopping 商品' },
        { iconKey: 'Link2', title: '自动生成联盟链接', desc: '用设置的合作伙伴 ID 即时生成佣金链接' },
        { iconKey: 'Sparkles', title: '短频模板自动完成', desc: '自动生成价格和推荐评论贴纸合成的卡片' },
        { iconKey: 'Send', title: '一键 SNS 分享（手风琴）', desc: '点击分享展开 Naver Clip、Naver TV、Instagram、KakaoTalk、博客按钮' },
        { iconKey: 'Shirt', title: '虚拟试穿 & 切割画廊', desc: 'AI 从产品照片生成多种试穿场景和角度切割' },
        { iconKey: 'Wand2', title: 'AI 风格推荐', desc: 'AI 推荐匹配产品的设计风格并一键应用' },
        { iconKey: 'Target', title: '病毒预测 & 人格模拟器', desc: '预测内容病毒潜力并模拟目标客户视角的反应' },
        { iconKey: 'Globe', title: '全球化 & 多平台导出', desc: '将营销文案多语言本地化并一次性生成平台优化图片' },
        { iconKey: 'TrendingUp', title: '趋势匹配 & 趋势文案', desc: '自动匹配实时 SNS 趋势关键词与产品生成时效文案' },
        { iconKey: 'Store', title: '店铺信息 & 线下联动', desc: '注册店铺信息后自动包含在短频卡片和分享内容中' },
        { iconKey: 'Clapperboard', title: 'AR 拍摄模式', desc: '实时 AR 效果下拍摄产品' },
        { iconKey: 'Music2', title: '声效（Sound Punch）', desc: '录制热门 meme 音效并按时间添加到漫画短频中' },
      ],
    },
  ],
  usageTitle: '内容制作功能说明书',
  usageDesc: '点击各制作功能展开详细使用方法',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: '制作短频卡片（模板）', steps: [
          '在结果页面点击"短频卡片"按钮',
          'AI 提供的评论和价格自动合成为贴纸在照片上',
          '选择风格（杂志/粗体/极简/Feed）改变设计',
          '可直接编辑价格、评论和标签文字',
          '使用去除背景按钮制作干净的产品图',
          '更改颜色主题以匹配品牌',
          '保存完成的卡片或直接分享',
        ]},
        { iconKey: 'LayoutTemplate', title: '制作轮播（多张幻灯片）', steps: [
          '在结果页面点击"轮播"按钮',
          '将多个产品或多角度照片按顺序排列',
          '每张幻灯片可单独输入文字和价格',
          '拖动可改变幻灯片顺序',
          '对所有幻灯片应用统一风格',
          '自动调整为 Instagram 竖版尺寸',
          '保存完成的轮播为图片或分享',
        ]},
        { iconKey: 'Film', title: '制作短频视频（剪辑）', steps: [
          '在结果页面点击"短频视频"按钮',
          '将产品照片和文字拼接成短视频',
          '自动应用转场效果和文字动画',
          '可选择背景音乐（欢快/安静/活力/无）和动效（Kenburns/缩放/平移）',
          '高级设置中可更改画面比例（竖/横/正方）和模板风格',
          '开启混合模式（照片→漫画转换）在视频后半段应用漫画效果',
          '选择视频长度（10秒/15秒/20秒/30秒）— 默认 15 秒',
          '竖版（9:16）比例适配 TikTok/Instagram Reels/YouTube Shorts',
          '保存到相册或云端后上传到各平台',
        ]},
        { iconKey: 'BookOpen', title: '制作漫画短频（漫画视频）', steps: [
          '在结果页面点击"漫画短频"按钮',
          'AI 自动用产品生成漫画剧本（单格/2格/3格分割）',
          '可直接编辑每格的对话和场景',
          '选择 webtoon 画风（Instatoon/B级/美食漫画/美式漫画/吉卜力风格）',
          '选择 AI 配音（明亮20代/沉稳旁白/B级口音）',
          '高级设置中选择视频长度 — 根据格数自动推荐',
          '可添加 AI 旁白配音、表情叠加和 MBTI 解说',
          '开启连载模式制作"第1天-第3天-第7天"时间线故事',
          '用声效功能按时间添加漫画音效',
          '音效按情绪自动匹配（惊讶：哇！、开心：耶~、自信：赞！）',
          '保存完成的漫画短频或直接分享到 TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'Film', title: '制作时间线短频（连载剧集）', steps: [
          '在结果页面点击"漫画短频"按钮',
          '在高级设置中开启"连载模式"',
          '自动制作第1天-第3天-第7天时间线故事漫画短频',
          '可编辑每一天的剧本和对话',
          '可同时应用 webtoon 画风和旁白配音',
          '保存或分享时间线短频到 TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'PenLine', title: '文案撰写（自动生成文字）', steps: [
          '在结果页面点击"撰写文案"按钮',
          'AI 根据产品分析结果生成营销文案',
          '可选择语调（休闲/专业/感性/幽默）',
          '直接复制或编辑后使用生成的文案',
          '同时提供标签推荐',
          '比较多个版本选择最佳',
        ]},
        { iconKey: 'Type', title: '评论 & 一句话点评', steps: [
          '在结果页面点击"评论输入"按钮',
          '自行撰写一句话点评或获取 AI 推荐',
          '撰写的评论自动反映到短频卡片和轮播中',
          '编辑评论会更新所有关联内容',
        ]},
        { iconKey: 'Scissors', title: '去除背景 & 图片编辑', steps: [
          '在结果页面点击"去除背景"按钮',
          'AI 自动检测并去除产品背景',
          '保存为透明背景图供多种设计使用',
          '去除的图片自动应用到短频卡片、轮播和漫画中',
          '可手动更改背景颜色',
        ]},
        { iconKey: 'Shirt', title: '虚拟试穿画廊', steps: [
          '在结果页面查看"虚拟试穿"部分',
          'AI 根据产品照片生成多种试穿场景',
          '针对服装、配饰等可穿戴产品优化',
          '点击试穿图可放大查看',
          '用"使用此图"按钮设为主图',
          '保存图片或用于短频卡片',
        ]},
        { iconKey: 'Layers', title: '虚拟切割画廊', steps: [
          '在结果页面查看"虚拟切割"部分',
          'AI 生成多角度多背景的产品切割图',
          '自动合成工作室、自然、店铺、渐变等背景',
          '点击切割图放大确认',
          '用"使用此图"按钮设为主图',
          '多张切割可用于轮播或短频视频',
        ]},
        { iconKey: 'Wand2', title: 'AI 风格推荐', steps: [
          '在结果页面查看"AI 风格"部分',
          'AI 推荐匹配产品类别和氛围的设计风格',
          '点击推荐风格即时应用到短频卡片',
          '更换风格自动调整文字排版、颜色、字体',
          '选择喜欢的风格一致应用到所有内容',
        ]},
        { iconKey: 'Target', title: '病毒预测', steps: [
          '在结果页面查看"病毒预测"部分',
          'AI 以分数预测内容的病毒潜力',
          '预测分数综合评估吸引力、趋势契合度和分享性',
          '点击改进建议查看提分技巧',
          '根据建议修改文案或风格后重新计算分数',
        ]},
        { iconKey: 'Users', title: '人格模拟器', steps: [
          '在结果页面查看"人格模拟器"部分',
          '选择目标客户人格（年龄、性别、兴趣）',
          'AI 模拟该人格如何评价产品',
          '查看预期反应、购买概率和核心卖点',
          '根据模拟结果优化营销文案',
        ]},
        { iconKey: 'Globe', title: '全球化本地化', steps: [
          '在结果页面查看"全球化本地化"部分',
          '将营销文案翻译为英语、日语、中文等多语言',
          '非单纯翻译 — 本地化为各国文化和 SNS 趋势',
          '自动反映各国热门标签和营销语调',
          '点击翻译文案复制到剪贴板',
          '快速制作海外平台优化内容',
        ]},
        { iconKey: 'Shuffle', title: '多平台导出', steps: [
          '在结果页面查看"多平台导出"部分',
          '一次性生成 Instagram、TikTok、YouTube Shorts 优化图片',
          '各平台最佳画面比例和文字位置自动调整',
          '自动应用各平台推荐标签和文案风格',
          '可单独保存各平台图片',
          '三平台同时上传最大化曝光',
        ]},
        { iconKey: 'TrendingUp', title: '趋势匹配', steps: [
          '在结果页面查看"趋势匹配"部分',
          'AI 自动匹配当前 SNS 流行关键词与产品',
          '点击实时趋势关键词自动生成相关营销文案',
          '同时提供趋势标签推荐',
          '制作时效内容提升算法曝光',
        ]},
        { iconKey: 'Store', title: '我的店铺信息', steps: [
          '在结果页面查看"我的店铺信息"部分',
          '注册线下店铺信息（地址、营业时间、电话）',
          '注册信息自动包含在短频卡片和分享内容中',
          '客户可从内容直接查看店铺位置',
          '用于线上线下联动营销',
        ]},
        { iconKey: 'Video', title: '视频导入', steps: [
          '在结果页面使用"视频导入"功能',
          '导入之前拍摄的视频转换为短频内容',
          '自动提取视频关键片段制作短频',
          '可在提取片段中添加文字和贴纸',
          '复用现有视频素材缩短制作时间',
        ]},
      ],
    },
  ],
  platformTitle: '各平台视频发布方法',
  platformDesc: '逐步说明如何将完成的短频视频上传到各平台',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'TikTok 上传', steps: [
          '在完成页面点击"TikTok"分享按钮或使用已保存到相册的视频',
          '打开 TikTok 应用并点击底部中央的"+"按钮',
          '从相册选择已保存的短频视频',
          '在编辑画面添加文字、贴纸、效果（可选）',
          '点击下一步并输入视频标题',
          '添加相关标签（使用应用推荐的标签）',
          '联盟链接放在 TikTok 个人简介或置顶评论中效果最佳',
          '设置可见范围为"公开"并点击发布',
        ]},
        { iconKey: 'Instagram', title: 'Instagram Reels 上传', steps: [
          '在完成页面点击"Instagram"分享按钮或使用已保存的视频',
          '打开 Instagram 应用，点击"+"按钮后选择"Reels"',
          '从相册选择已保存的短频视频',
          '添加音乐：选择 Instagram 内置音乐或原视频音频',
          '按需添加文字贴纸（在画面上显示产品名或引子文字）',
          '点击下一步并输入文案',
          '在文案中直接添加联盟链接或通过个人简介链接引导',
          '添加相关标签，设置为"公开"后点击分享',
          '上传 Reel 后在个人资料的"链接"按钮中注册联盟链接可提高点击率',
        ]},
        { iconKey: 'Youtube', title: 'YouTube Shorts 上传', steps: [
          '在完成页面点击"Shorts"分享按钮或使用已保存的视频',
          '打开 YouTube 应用，点击"+"按钮后选择"创建 Short"',
          '从相册选择已保存的短频视频',
          '在编辑画面添加文字、滤镜、音乐（可选）',
          '点击下一步并输入视频标题',
          '在标题中包含 #Shorts 标签可提升 Shorts 信息流曝光',
          '在视频描述或频道个人资料链接中添加联盟链接',
          '设置为"公开"并点击上传',
        ]},
        { iconKey: 'Share2', title: 'Naver Clip & KakaoTalk 分享', steps: [
          'Naver Clip：在完成页面点击"分享"按钮将推广文字和图片复制到剪贴板',
          '打开 Naver Clip 应用或 Naver TV 选择创建新 Clip',
          '上传已保存的视频并粘贴复制的推广文字',
          'KakaoTalk：用分享按钮在消息中同时发送图片和链接',
          '在 KakaoTalk 频道或开放聊天室分享视频和联盟链接可直接引导点击',
        ]},
        { iconKey: 'Lightbulb', title: '多平台同时上传策略', steps: [
          '将一个短频视频同时上传到 TikTok、Instagram Reels 和 YouTube Shorts 可获三倍曝光',
          '各平台文案和标签稍作不同有利于算法',
          'TikTok 用趋势标签、Instagram 用产品标签、YouTube 用 #Shorts',
          '在各平台个人简介中注册相同联盟链接便于管理',
          '最佳上传时间为当地时间下午 6-10 点',
          '视频长度设为 15-30 秒观看时长充足且有利于算法曝光',
        ]},
      ],
    },
  ],
  soundTitle: '声效（Sound Punch）使用指南',
  soundDesc: '录制热门 meme 音效并按时间添加到漫画短频中',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: '声效编辑器使用方法', steps: [
          '在漫画短频生成器中展开"高级选项"',
          '开启"声效编辑"开关（仅限网页浏览器）',
          '按下录制按钮对麦克风发声 — 实时显示波形',
          '大声音自动检测并添加效果标记（砰、放大、漫画等）',
          '也可用语音命令指定效果（"砰"、"放大"、"漫画"等）',
          '停止录制后在时间线显示标记并可播放',
          '点击标记可更改或删除效果类型',
          '漫画短频生成时录制的效果自动合成到视频中',
          '在移动端显示"仅可在网页浏览器中使用"提示',
        ]},
      ],
    },
  ],
  helpTitle: '帮助',
  helpItems: [
    { iconKey: 'Info', title: '使用方法', desc: '拍摄或上传照片后 AI 会分析产品。在结果页面一站式使用购物匹配、短频卡片和分享。' },
    { iconKey: 'Link2', title: '应用佣金链接', desc: "在结果页面用'粘贴我的佣金链接'按钮应用 Brand Connect 链接。自动反映到分享和卡片中。" },
  ],
  feedbackTitle: '反馈 & 错误报告',
  feedbackDesc: '请告诉我们使用中的不便或发现的错误。您的意见让应用更好。',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: '发送反馈', desc: '通过 Google 表单留下反馈' },
    { iconKey: 'Bug', title: '错误报告 & 开放聊天', desc: '在 KakaoTalk 开放聊天室快速获取帮助' },
  ],
  footer: 'ShortConnect — 面向线上线下卖家的一站式 AI 电商',
  onboardingTitle: '重新查看应用导览',
  onboardingDesc: '点击重新查看初始指南',
};

export const guideTranslations: Record<AppLanguage, GuideContent> = {
  ko,
  en,
  ja,
  vi,
  es,
  zh,
};

export function getGuideContent(lang: AppLanguage): GuideContent {
  return guideTranslations[lang] ?? ko;
}
