import type { AppLanguage } from './i18n';

export interface GuideSection {
  title: string;
  desc?: string;
  items: GuideItem[];
}

export interface GuideItem {
  iconKey: string;
  title: string;
  steps?: string[];
  desc?: string;
}

export interface GuideFlowStep {
  num: string;
  title: string;
  desc: string;
}

export interface GuideContent {
  naverSection: {
    title: string;
    desc: string;
    guideTitle: string;
    guideSteps: string;
    linkText: string;
    notice: string;
  };
  tabsTitle: string;
  tabsDesc: string;
  tabsItems: GuideItem[];
  flowTitle: string;
  flowDesc: string;
  flowSteps: GuideFlowStep[];
  featuresTitle: string;
  featuresDesc?: string;
  featureSections: GuideSection[];
  usageTitle: string;
  usageDesc: string;
  usageSections: GuideSection[];
  automationTitle: string;
  automationDesc: string;
  automationSections: GuideSection[];
  monetizationTitle: string;
  monetizationDesc: string;
  monetizationSections: GuideSection[];
  growthTitle: string;
  growthDesc: string;
  growthSections: GuideSection[];
  platformTitle: string;
  platformDesc: string;
  platformSections: GuideSection[];
  soundTitle: string;
  soundDesc: string;
  soundSections: GuideSection[];
  helpTitle: string;
  helpItems: GuideItem[];
  feedbackTitle: string;
  feedbackDesc: string;
  feedbackItems: GuideItem[];
  footer: string;
  onboardingTitle: string;
  onboardingDesc: string;
}

const ko: GuideContent = {
  naverSection: {
    title: '네이버 쇼핑커넥트 & 제휴 플랫폼 안내',
    desc: '네이버 쇼핑커넥트는 브랜드커넥트(banner.naver.com)에서 크리에이터로 가입 후, 상품별로 전용 수수료 링크를 직접 발급받는 시스템입니다. 앱에서는 네이버뿐 아니라 쿠팡, 아마존 등 다양한 제휴 플랫폼을 전환하며 사용할 수 있습니다.',
    guideTitle: '이용 방법',
    guideSteps: '1. 네이버 브랜드커넥트에 크리에이터로 가입합니다\n2. 채널(블로그/인스타/유튜브)을 연동합니다\n3. 상품 찾기에서 홍보할 상품을 선택합니다\n4. 링크 발급 버튼으로 전용 수수료 링크를 받습니다\n5. 발급받은 링크를 앱 설정에 입력하거나 직접 붙여넣기 합니다\n6. 제휴 플랫폼 전환으로 쿠팡/아마존 등 다른 플랫폼도 함께 사용할 수 있습니다',
    linkText: '네이버 브랜드커넥트 바로가기',
    notice: '본 앱은 AI가 상품을 식별하고 네이버 쇼핑 검색 링크를 자동 생성합니다. 정확한 수수료 추적을 위해서는 브랜드커넥트에서 발급받은 개별 링크를 직접 사용하세요. 제휴 플랫폼 전환 기능으로 여러 플랫폼의 수수료 링크를 통합 관리할 수 있습니다.',
  },
  tabsTitle: '앱 탭 구조',
  tabsDesc: '앱은 3개의 메인 탭으로 구성되어 있습니다. 각 탭에서 담당하는 기능을 확인하세요',
  tabsItems: [
    { iconKey: 'Camera', title: '홈 탭 (촬영 & 제작)', desc: '상품 촬영, AI 분석, 숏폼 카드/캐러셀/영상/만화 제작, 카피라이팅, 스타일 추천, 바이럴 예측 등 모든 콘텐츠 제작 기능이 이 탭에 있습니다' },
    { iconKey: 'Megaphone', title: '마케팅 탭 (마케팅 자동화)', desc: '스마트 스케줄러, 날씨 마케팅, 재고 알림, 리뷰 자동화, 트렌드 분석, 공유 쿨다운 등 마케팅 자동화 도구가 있습니다' },
    { iconKey: 'FolderOpen', title: '에셋 탭 (자산 & 수익 관리)', desc: '저장된 에셋, 링크인바이오, QR 대시보드, 제휴 대시보드, 수익 추적, 크레딧 잔액 등 자산과 수익 관리 도구가 있습니다' },
  ],
  flowTitle: '콘텐츠 제작 순서 가이드',
  flowDesc: '앱에서 만들 수 있는 콘텐츠의 전체 제작 흐름을 한눈에 보여줍니다',
  flowSteps: [
    { num: 'STEP 1', title: '촬영 & AI 분석', desc: '상품을 촬영하면 AI가 제품명, 카테고리, 가격대를 자동 식별합니다. 다각도 촬영, AR 모드, OCR 텍스트 추출도 가능합니다' },
    { num: 'STEP 2', title: '쇼핑 매칭 & 제휴 링크', desc: '네이버/쿠팡/아마존에서 동일 상품을 찾고 제휴 수수료 링크를 자동 생성합니다. 단축 URL과 클릭 추적도 함께 제공됩니다' },
    { num: 'STEP 3', title: '숏폼 카드 & 템플릿', desc: '사진 위에 가격, 한줄평 스티커를 합성한 카드를 만듭니다. AI 이미지 생성, 가상 피팅, 배경 제거도 가능합니다' },
    { num: 'STEP 4', title: '캐러셀 & 숏폼 영상', desc: '여러 장의 카드를 슬라이드 캐러셀이나 숏폼 영상으로 제작합니다. 하이브리드 모드, 모션 줌, 비디오 임포트도 지원합니다' },
    { num: 'STEP 5', title: '만화 콘텐츠 제작', desc: '상품을 활용한 만화 시나리오를 AI로 생성합니다. 5가지 화풍, AI 성우 더빙, 사운드 펀치, 연작 에피소드 모드를 지원합니다' },
    { num: 'STEP 6', title: '공유 & 수익 추적', desc: '인스타, 틱톡, 카카오톡으로 공유하고 클릭수와 수익을 추적합니다. QR 코드, 링크인바이오로 오프라인 연계도 가능합니다' },
    { num: 'STEP 7', title: '마케팅 자동화', desc: '스마트 스케줄러로 업로드 시간을 최적화하고, 날씨/재고 알림으로 시의성 있는 마케팅을 자동화합니다' },
    { num: 'STEP 8', title: '성장 & 게이미피케이션', desc: '퀘스트 달성, 리더보드, 크리에이터 등급으로 성장하고, 계정 안전성과 독창성 점수로 채널을 보호합니다' },
  ],
  featuresTitle: '기능 소개',
  featuresDesc: '앱의 모든 기능을 카테고리별로 확인하세요',
  featureSections: [
    {
      title: '촬영 & 분석',
      items: [
        { iconKey: 'Camera', title: '실물 촬영 & 쇼핑 매칭', desc: '신발, 조명, 옷 등을 촬영하면 AI가 제품을 식별하고 네이버 쇼핑 상품을 매칭합니다' },
        { iconKey: 'Clapperboard', title: 'AR 촬영 모드', desc: '실시간 AR 효과를 적용하며 상품을 촬영할 수 있습니다' },
        { iconKey: 'Grid3x3', title: '다각도 촬영 가이드', desc: '정면/측면/디테일 3가지 각도의 사진을 가이드에 맞춰 촬영합니다' },
        { iconKey: 'ScanLine', title: 'OCR 텍스트 추출', desc: '상품 포장지나 라벨의 텍스트를 AI가 자동 추출하여 상품 정보를 보완합니다' },
      ],
    },
    {
      title: '콘텐츠 제작',
      items: [
        { iconKey: 'Sparkles', title: '숏폼 템플릿 자동 완성', desc: '사진 위에 가격과 추천 한줄평 스티커가 합성된 카드를 자동 생성합니다' },
        { iconKey: 'LayoutTemplate', title: '캐러셀 (여러 장 슬라이드)', desc: '여러 상품이나 다각도 사진을 순서대로 배치한 슬라이드를 만듭니다' },
        { iconKey: 'Film', title: '숏폼 영상 (클립)', desc: '상품 사진과 텍스트를 이어붙여 짧은 영상을 만듭니다. 전환 효과, BGM, 모션 효과 지원' },
        { iconKey: 'BookOpen', title: '만화 숏폼 (만화 영상)', desc: 'AI가 상품을 활용한 만화 시나리오를 자동 생성합니다. 5가지 화풍, AI 더빙, 사운드 펀치 지원' },
        { iconKey: 'ImagePlus', title: 'AI 이미지 생성', desc: '텍스트 프롬프트로 상품 이미지를 AI가 생성합니다' },
        { iconKey: 'Shirt', title: '가상 피팅 (AI 착용)', desc: '의류/액세서리 상품을 AI가 가상으로 착용한 이미지를 생성합니다' },
        { iconKey: 'Layers', title: 'AI 컷 & 배경 합성', desc: '상품 사진을 다양한 각도와 배경으로 합성한 컷을 자동 생성합니다' },
        { iconKey: 'Video', title: '비디오 임포트', desc: '기존 영상을 불러와 숏폼 콘텐츠로 변환합니다' },
        { iconKey: 'Scissors', title: '배경 제거 & 이미지 편집', desc: 'AI가 상품 배경을 자동 제거하고 투명 배경 이미지로 저장합니다' },
      ],
    },
    {
      title: 'AI 콘텐츠 도구',
      items: [
        { iconKey: 'PenLine', title: '카피라이팅 (글 자동 생성)', desc: 'AI가 상품 분석 결과를 바탕으로 마케팅 문구를 생성합니다' },
        { iconKey: 'Wand2', title: 'AI 스타일 추천', desc: '상품에 맞는 디자인 스타일을 AI가 추천하고 원탭으로 적용합니다' },
        { iconKey: 'Target', title: '바이럴 예측', desc: '콘텐츠의 바이럴 잠재력을 점수로 예측하고 개선 팁을 제공합니다' },
        { iconKey: 'Users', title: '페르소나 시뮬레이터', desc: '타겟 고객 관점에서 상품 반응을 시뮬레이션합니다' },
        { iconKey: 'Globe', title: '글로벌 현지화', desc: '마케팅 카피를 다국어로 현지화하고 국가별 해시태그를 반영합니다' },
        { iconKey: 'Shuffle', title: '멀티 플랫폼 익스포트', desc: '인스타·틱톡·쇼츠 맞춤 이미지를 한 번에 생성합니다' },
        { iconKey: 'TrendingUp', title: '트렌드 매칭 & 트렌드 카피', desc: '실시간 SNS 트렌드 키워드와 상품을 자동 매칭합니다' },
        { iconKey: 'Type', title: '플랫폼별 캡션 최적화', desc: '각 플랫폼에 맞는 캡션 스타일과 해시태그를 자동 최적화합니다' },
      ],
    },
    {
      title: '제휴 & 수익화',
      items: [
        { iconKey: 'Link2', title: '제휴 링크 자동 생성', desc: '설정한 파트너스 ID로 수수료 링크를 즉시 생성합니다' },
        { iconKey: 'Send', title: '제휴 플랫폼 전환', desc: '네이버/쿠팡/아마존 등 다양한 제휴 플랫폼을 전환하며 사용합니다' },
        { iconKey: 'Wallet', title: '제휴 대시보드 & 수익 추적', desc: '클릭수, 수익, 전환율을 한눈에 확인하는 대시보드를 제공합니다' },
        { iconKey: 'CreditCard', title: '크레딧 시스템', desc: 'AI 기능 사용에 필요한 크레딧을 관리하고 추가 구매할 수 있습니다' },
        { iconKey: 'QrCode', title: 'QR 코드 & 워터마크', desc: '제휴 링크가 포함된 QR 코드를 생성하고 이미지에 워터마크로 추가합니다' },
        { iconKey: 'Link', title: '링크인바이오', desc: '크리에이터 링크인바이오 페이지를 만들어 모든 제휴 링크를 한 곳에 모읍니다' },
      ],
    },
    {
      title: '마케팅 자동화',
      items: [
        { iconKey: 'CalendarClock', title: '스마트 스케줄러', desc: '업로드 시간을 예약하고 최적 시간대에 자동 게시합니다' },
        { iconKey: 'CloudRain', title: '날씨 마케팅 에이전트', desc: '날씨 변화에 맞춰 시의성 있는 마케팅 메시지를 자동 생성합니다' },
        { iconKey: 'Package', title: '재고 알림 에이전트', desc: '상품 재고 상태를 추적하고 보충 마케팅을 자동화합니다' },
        { iconKey: 'Megaphone', title: '리뷰 자동화', desc: '고객 리뷰를 수집하고 리뷰 기반 숏폼 콘텐츠를 자동 제작합니다' },
        { iconKey: 'Share2', title: '공유 쿨다운', desc: '과도한 공유를 방지하고 플랫폼 알고리즘에 안전한 공유 간격을 유지합니다' },
      ],
    },
    {
      title: '성장 & 게이미피케이션',
      items: [
        { iconKey: 'Trophy', title: '퀘스트 & 리더보드', desc: '일일/주간 퀘스트를 달성하고 다른 크리에이터와 경쟁합니다' },
        { iconKey: 'ShieldCheck', title: '계정 안전성 검사', desc: 'SNS 계정 정지 위험을 사전에 감지하고 안전한 운영 가이드를 제공합니다' },
        { iconKey: 'FileCheck', title: '독창성 점수', desc: '콘텐츠의 독창성을 AI가 분석하고 점수로 평가합니다' },
        { iconKey: 'Globe', title: '현지화 안전성', desc: '다국어 콘텐츠의 문화적 적합성을 검사하고 위험 표현을 사전에 경고합니다' },
        { iconKey: 'Stamp', title: '광고 성공 표시 (FTC 공시)', desc: '제휴 광고임을 자동으로 표시하여 플랫폼 정책을 준수합니다' },
      ],
    },
  ],
  usageTitle: '콘텐츠 제작 기능 설명서',
  usageDesc: '각 제작 기능을 탭하면 상세 사용법이 펼쳐집니다',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: '숏폼 카드 (템플릿) 만들기', steps: [
          '결과 화면에서 "숏폼 카드" 버튼을 탭합니다',
          'AI가 제공한 한줄평과 가격이 사진 위에 스티커로 자동 합성됩니다',
          '스타일(매거진/볼드/미니멀/피드)을 선택해 디자인을 바꿀 수 있습니다',
          '가격, 한줄평, 해시태그 텍스트를 직접 수정할 수 있습니다',
          '배경 제거 버튼으로 깔끔한 상품 이미지를 만들 수 있습니다',
          '색상 테마를 변경해 브랜드에 맞는 디자인을 적용합니다',
          '완성된 카드를 저장하거나 바로 공유할 수 있습니다',
        ]},
        { iconKey: 'LayoutTemplate', title: '캐러셀 (여러 장 슬라이드) 만들기', steps: [
          '결과 화면에서 "캐러셀" 버튼을 탭합니다',
          '여러 상품이나 여러 각도의 사진을 순서대로 배치합니다',
          '각 슬라이드마다 개별 텍스트와 가격을 입력할 수 있습니다',
          '슬라이드 순서를 드래그하여 변경할 수 있습니다',
          '전체 슬라이드에 통일된 스타일을 적용합니다',
          '인스타그램 게시물용으로 세로 크기에 맞춰 자동 조정됩니다',
          '완성된 캐러셀을 이미지로 저장하거나 공유합니다',
        ]},
        { iconKey: 'Film', title: '숏폼 영상 (클립) 만들기', steps: [
          '결과 화면에서 "숏폼 영상" 버튼을 탭합니다',
          '상품 사진과 텍스트를 이어붙여 짧은 영상을 만듭니다',
          '화면 전환 효과와 텍스트 애니메이션이 자동 적용됩니다',
          '배경 음악(업비트/차분/에너지/없음)과 모션 효과(켄번스/줌/팬)를 선택할 수 있습니다',
          '고급 설정에서 화면 비율(세로/가로/정사각형)과 템플릿 스타일을 바꿀 수 있습니다',
          '하이브리드 모드(사진→만화 전환)를 켜면 영상 중반에 만화 효과가 적용됩니다',
          '영상 길이(10초/15초/20초/30초)를 선택합니다 — 기본 15초',
          '세로(9:16) 비율로 틱톡/인스타 릴스/유튜브 쇼츠에 최적화됩니다',
          '완성된 영상을 갤러리에 저장하거나 클라우드에 저장 후 각 플랫폼에 업로드합니다',
        ]},
        { iconKey: 'BookOpen', title: '만화 숏폼 (만화 영상) 만들기', steps: [
          '결과 화면에서 "만화 숏폼" 버튼을 탭합니다',
          'AI가 상품을 활용한 만화 시나리오를 자동 생성합니다 (싱글/2컷/3컷 분할)',
          '각 컷의 대사와 상황을 직접 수정할 수 있습니다',
          '웹툰 화풍(인스타툰/B급 병맛/미식 요리툰/아메리칸 코믹스/감성 지브리풍)을 선택합니다',
          'AI 성우 목소리(밝은 20대/차분한 나레이션/B급 억양)를 선택해 더빙할 수 있습니다',
          '고급 설정에서 영상 길이(10초/15초/20초/30초)를 선택합니다 — 컷 수에 따라 자동 추천',
          'AI 내레이션 더빙, 감정 표정 오버레이, MBTI 맞춤형 해설을 추가할 수 있습니다',
          '연작 에피소드 모드를 켜면 "1일차-3일차-7일차" 시간 흐름 스토리로 만들어집니다',
          '사운드 펀치 효과로 만화 효과음을 시간대별로 추가할 수 있습니다',
          '효과음은 감정에 따라 자동 매칭됩니다 (놀람: 헐 대박!, 행복: 샤방~, 확신: 따봉! 등)',
          '완성된 만화 숏폼을 저장하거나 틱톡/인스타/쇼츠로 바로 공유합니다',
        ]},
        { iconKey: 'Film', title: '타임라인 숏폼 (연작 에피소드) 만들기', steps: [
          '결과 화면에서 "만화 숏폼" 버튼을 탭합니다',
          '고급 설정에서 "연작 에피소드 모드"를 켭니다',
          '1일차-3일차-7일차 등 시간 흐름 스토리로 만화 숏폼이 자동 제작됩니다',
          '각 일차별 시나리오와 대사를 직접 수정할 수 있습니다',
          '웹툰 화풍과 내레이션 더빙을 함께 적용할 수 있습니다',
          '완성된 타임라인 숏폼을 저장하거나 틱톡/인스타/쇼츠로 공유합니다',
        ]},
        { iconKey: 'ImagePlus', title: 'AI 이미지 생성', steps: [
          '결과 화면에서 "AI 이미지 생성" 기능을 사용합니다',
          '텍스트 프롬프트로 원하는 상품 이미지를 AI가 생성합니다',
          '상품 분석 결과를 바탕으로 자동 프롬프트가 제안됩니다',
          '생성된 이미지를 숏폼 카드나 캐러셀에 바로 사용할 수 있습니다',
          '여러 장을 생성하여 가장 좋은 이미지를 선택합니다',
        ]},
        { iconKey: 'Shirt', title: '가상 피팅 (AI 착용)', steps: [
          '결과 화면에서 "가상 피팅" 섹션을 확인합니다',
          'AI가 상품 사진을 바탕으로 착용 장면을 자동 생성합니다',
          '의류, 액세서리 등 착용 가능한 상품에 최적화되어 있습니다',
          '생성된 피팅 이미지를 탭하면 크게 볼 수 있습니다',
          '"이 이미지 사용" 버튼으로 피팅 이미지를 메인 이미지로 설정합니다',
          '생성된 이미지를 저장하거나 숏폼 카드에 활용합니다',
        ]},
        { iconKey: 'Layers', title: 'AI 컷 & 배경 합성', steps: [
          '결과 화면에서 "AI 컷" 섹션을 확인합니다',
          'AI가 상품을 다양한 각도와 배경으로 촬영한 것 같은 컷을 자동 생성합니다',
          '스튜디오, 자연, 매장, 그라데이션 등 다양한 배경에 자동 합성됩니다',
          '생성된 컷을 탭하면 크게 확인할 수 있습니다',
          '"이 이미지 사용" 버튼으로 원하는 컷을 메인 이미지로 설정합니다',
          '여러 컷을 캐러셀이나 숏폼 영상에 활용할 수 있습니다',
        ]},
        { iconKey: 'Grid3x3', title: '다각도 촬영 가이드', steps: [
          '홈 탭에서 "다각도 촬영" 모드를 선택합니다',
          '정면, 측면, 디테일 3가지 각도의 가이드가 표시됩니다',
          '각 가이드에 맞춰 순서대로 사진을 촬영합니다',
          '촬영된 3각도 사진이 캐러셀이나 숏폼 영상에 자동 활용됩니다',
          '상품의 다양한 면을 보여주어 구매 전환율을 높일 수 있습니다',
        ]},
        { iconKey: 'ScanLine', title: 'OCR 텍스트 추출', steps: [
          '홈 탭에서 "OCR 스캔" 모드를 선택합니다',
          '상품 포장지나 라벨을 카메라로 비춥니다',
          'AI가 텍스트를 자동 추출하여 상품명, 성분, 원산지 등을 보완합니다',
          '추출된 텍스트를 확인하고 수정할 수 있습니다',
          '추출된 정보가 카피라이팅과 숏폼 카드에 자동 반영됩니다',
        ]},
        { iconKey: 'PenLine', title: '카피라이팅 (글 자동 생성)', steps: [
          '결과 화면에서 "카피 작성" 버튼을 탭합니다',
          'AI가 상품 분석 결과를 바탕으로 마케팅 문구를 생성합니다',
          '톤앤매너(캐주얼/전문/감성/유머)를 선택할 수 있습니다',
          '생성된 카피를 그대로 복사하거나 수정 후 사용합니다',
          '해시태그 추천도 함께 제공됩니다',
          '여러 버전의 카피를 비교하고 가장 좋은 것을 선택합니다',
        ]},
        { iconKey: 'Type', title: '리뷰 & 한줄평 작성', steps: [
          '결과 화면에서 "리뷰 입력" 버튼을 탭합니다',
          '직접 상품에 대한 한줄평을 작성하거나 AI 추천을 받습니다',
          '작성한 리뷰는 숏폼 카드와 캐러셀에 자동 반영됩니다',
          '리뷰를 수정하면 연결된 모든 콘텐츠가 업데이트됩니다',
        ]},
        { iconKey: 'Scissors', title: '배경 제거 & 이미지 편집', steps: [
          '결과 화면에서 "배경 제거" 버튼을 탭합니다',
          'AI가 상품의 배경을 자동으로 감지하고 제거합니다',
          '투명 배경 이미지로 저장되어 다양한 디자인에 활용 가능합니다',
          '제거된 이미지는 숏폼 카드, 캐러셀, 만화에 자동 적용됩니다',
          '필요시 배경 색상을 직접 변경할 수 있습니다',
        ]},
        { iconKey: 'Video', title: '비디오 임포트', steps: [
          '결과 화면에서 "비디오 임포트" 기능을 사용합니다',
          '기존에 촬영한 영상을 불러와 숏폼 콘텐츠로 변환합니다',
          '영상에서 핵심 구간을 자동 추출하여 숏폼으로 만듭니다',
          '추출된 구간에 텍스트와 스티커를 추가할 수 있습니다',
          '기존 영상 자산을 재활용하여 콘텐츠 제작 시간을 단축하세요',
        ]},
        { iconKey: 'Wand2', title: 'AI 스타일 추천', steps: [
          '결과 화면에서 "AI 스타일" 섹션을 확인합니다',
          'AI가 상품 카테고리와 분위기에 맞는 디자인 스타일을 추천합니다',
          '추천된 스타일을 탭하면 숏폼 카드에 즉시 적용됩니다',
          '스타일을 변경하면 텍스트 배치, 색상, 폰트가 자동으로 조정됩니다',
          '마음에 드는 스타일을 선택하면 모든 콘텐츠에 일관되게 적용됩니다',
        ]},
        { iconKey: 'Target', title: '바이럴 예측', steps: [
          '결과 화면에서 "바이럴 예측" 섹션을 확인합니다',
          'AI가 콘텐츠의 바이럴 잠재력을 점수로 예측합니다',
          '예측 점수는 후킹력, 트렌드 적합도, 공유 가능성을 종합 평가합니다',
          '개선 제안을 탭하면 점수를 높일 수 있는 팁을 확인할 수 있습니다',
          '제안에 따라 카피나 스타일을 수정하면 예측 점수가 다시 계산됩니다',
        ]},
        { iconKey: 'Users', title: '페르소나 시뮬레이터', steps: [
          '결과 화면에서 "페르소나 시뮬레이터" 섹션을 확인합니다',
          '타겟 고객의 페르소나(연령, 성별, 관심사)를 선택합니다',
          'AI가 해당 페르소나 관점에서 상품을 어떻게 평가할지 시뮬레이션합니다',
          '예상 반응, 구매 확률, 주요 어필 포인트를 확인할 수 있습니다',
          '시뮬레이션 결과를 바탕으로 마케팅 카피를 최적화할 수 있습니다',
        ]},
        { iconKey: 'Globe', title: '글로벌 현지화', steps: [
          '결과 화면에서 "글로벌 현지화" 섹션을 확인합니다',
          '마케팅 카피를 영어, 일본어, 중국어, 베트남어, 스페인어 등 다국어로 번역합니다',
          '단순 번역이 아닌 각국 문화와 SNS 트렌드에 맞게 현지화합니다',
          '국가별 인기 해시태그와 마케팅 톤을 자동 반영합니다',
          '번역된 카피를 탭하면 클립보드에 복사됩니다',
          '해외 진출 시 각국 플랫폼에 맞춘 콘텐츠를 빠르게 제작할 수 있습니다',
        ]},
        { iconKey: 'Shuffle', title: '멀티 플랫폼 익스포트', steps: [
          '결과 화면에서 "멀티 플랫폼 익스포트" 섹션을 확인합니다',
          '인스타그램, 틱톡, 유튜브 쇼츠 세 플랫폼에 맞춘 이미지를 한 번에 생성합니다',
          '각 플랫폼별 최적 화면 비율과 텍스트 위치가 자동 조정됩니다',
          '플랫폼별 권장 해시태그와 캡션 스타일이 자동 적용됩니다',
          '생성된 이미지를 각 플랫폼에 맞춰 개별 저장할 수 있습니다',
          '세 플랫폼 동시 업로드로 노출을 극대화할 수 있습니다',
        ]},
        { iconKey: 'TrendingUp', title: '트렌드 매칭', steps: [
          '결과 화면에서 "트렌드 매칭" 섹션을 확인합니다',
          'AI가 현재 SNS에서 유행하는 키워드와 상품을 자동 매칭합니다',
          '실시간 트렌드 키워드를 탭하면 관련 마케팅 카피가 자동 생성됩니다',
          '트렌드에 맞춘 해시태그 추천도 함께 제공됩니다',
          '시의성 있는 콘텐츠로 알고리즘 노출을 높일 수 있습니다',
        ]},
        { iconKey: 'Store', title: '내 가게 정보 & 오프라인 연계', steps: [
          '결과 화면에서 "내 가게 정보" 섹션을 확인합니다',
          '오프라인 매장 정보(주소, 영업시간, 전화번호)를 등록할 수 있습니다',
          '등록한 가게 정보가 숏폼 카드와 공유 콘텐츠에 자동 포함됩니다',
          '고객이 콘텐츠를 보고 매장 위치를 바로 확인할 수 있습니다',
          '온·오프라인 연계 마케팅에 활용하세요',
        ]},
      ],
    },
  ],
  automationTitle: '마케팅 자동화 기능 설명서',
  automationDesc: '마케팅 탭에서 사용할 수 있는 자동화 도구입니다',
  automationSections: [
    {
      title: '',
      items: [
        { iconKey: 'CalendarClock', title: '스마트 스케줄러', steps: [
          '마케팅 탭에서 "스마트 스케줄러"를 엽니다',
          '업로드할 콘텐츠와 플랫폼을 선택합니다',
          '예약 시간을 설정하면 최적 시간대에 자동으로 알림이 울립니다',
          '플랫폼별 최적 업로드 시간대가 자동 추천됩니다',
          '여러 콘텐츠를 일정에 따라 순차 예약할 수 있습니다',
          '예약된 콘텐츠는 목록에서 확인하고 수정할 수 있습니다',
        ]},
        { iconKey: 'CloudRain', title: '날씨 마케팅 에이전트', steps: [
          '마케팅 탭에서 "날씨 마케팅"을 엽니다',
          '현재 날씨와 예보가 자동으로 불러와집니다',
          'AI가 날씨에 맞는 마케팅 메시지를 자동 생성합니다 (예: 비 오는 날 → 실내 상품 추천)',
          '날씨별 마케팅 히스토리를 확인할 수 있습니다',
          '특정 날씨 조건에서 자동으로 마케팅 알림을 받을 수 있습니다',
          '시의성 있는 날씨 마케팅으로 알고리즘 노출을 높이세요',
        ]},
        { iconKey: 'Package', title: '재고 알림 에이전트', steps: [
          '마케팅 탭에서 "재고 알림"을 엽니다',
          '추적할 상품의 재고 상태를 등록합니다',
          '재고가 부족하면 AI가 보충 마케팅 메시지를 자동 생성합니다',
          '품절 임박, 재고 보충 등의 알림을 받을 수 있습니다',
          '재고 상태에 맞춘 숏폼 콘텐츠 제작이 추천됩니다',
        ]},
        { iconKey: 'Megaphone', title: '리뷰 자동화', steps: [
          '마케팅 탭에서 "리뷰 자동화"를 엽니다',
          '고객 리뷰를 수집하고 관리할 수 있습니다',
          'AI가 리뷰를 분석하여 긍정/부정 감정을 자동 분류합니다',
          '긍정 리뷰를 바탕으로 리뷰 기반 숏폼 콘텐츠를 자동 제작합니다',
          '부정 리뷰는 개선 포인트로 활용할 수 있습니다',
          '리뷰 기반 콘텐츠는 신뢰도가 높아 구매 전환율이 높습니다',
        ]},
        { iconKey: 'Share2', title: '공유 쿨다운', steps: [
          '과도한 공유는 플랫폼 알고리즘에 의해 스팸으로 간주될 수 있습니다',
          '앱이 플랫폼별 안전한 공유 간격을 자동으로 계산합니다',
          '쿨다운 시간 동안은 공유 버튼이 비활성화됩니다',
          '남은 대기 시간이 표시되어 언제 공유할 수 있는지 확인할 수 있습니다',
          '계정 안전을 위해 쿨다운 알림을 준수하세요',
        ]},
      ],
    },
  ],
  monetizationTitle: '제휴 & 수익화 도구 설명서',
  monetizationDesc: '에셋 탭과 결과 화면에서 사용할 수 있는 수익화 도구입니다',
  monetizationSections: [
    {
      title: '',
      items: [
        { iconKey: 'Send', title: '제휴 플랫폼 전환', steps: [
          '결과 화면이나 설정에서 제휴 플랫폼을 전환할 수 있습니다',
          '네이버, 쿠팡, 아마존 등 다양한 플랫폼 중 선택합니다',
          '각 플랫폼의 파트너스 ID를 설정에 입력합니다',
          '전환하면 해당 플랫폼의 수수료 링크가 자동 생성됩니다',
          '여러 플랫폼을 동시에 사용하여 수익을 극대화할 수 있습니다',
        ]},
        { iconKey: 'Wallet', title: '제휴 대시보드 & 수익 추적', steps: [
          '에셋 탭에서 "제휴 대시보드"를 엽니다',
          '총 클릭수, 수익, 전환율을 한눈에 확인합니다',
          '플랫폼별, 상품별 수익 분석을 볼 수 있습니다',
          '기간별 수익 추이 그래프를 확인할 수 있습니다',
          '어떤 상품이 가장 수익이 좋은지 분석하여 전략을 세우세요',
        ]},
        { iconKey: 'CreditCard', title: '크레딧 시스템', steps: [
          'AI 기능 사용 시 크레딧이 소모됩니다',
          '에셋 탭에서 현재 크레딧 잔액을 확인할 수 있습니다',
          '크레딧이 부족하면 크레딧 구매 모달에서 추가할 수 있습니다',
          '크리에이터 등급에 따라 월간 무료 크레딧이 제공됩니다',
          '크레딧을 효율적으로 사용하려면 AI 캐시 기능을 활용하세요',
        ]},
        { iconKey: 'QrCode', title: 'QR 코드 & 워터마크', steps: [
          '결과 화면에서 "QR 코드" 기능을 사용합니다',
          '제휴 링크가 포함된 QR 코드를 자동 생성합니다',
          'QR 코드를 숏폼 카드 이미지에 워터마크로 추가할 수 있습니다',
          '오프라인 매장이나 명함에 QR 코드를 인쇄하여 활용하세요',
          'QR 리뷰 대시보드에서 스캔 추적을 확인할 수 있습니다',
        ]},
        { iconKey: 'Link', title: '링크인바이오', steps: [
          '에셋 탭에서 "링크인바이오"를 엽니다',
          '크리에이터 프로필 페이지를 만듭니다',
          '모든 제휴 링크를 한 페이지에 모아 관리합니다',
          '프로필 사진, 소개 문구, 소셜 링크를 설정합니다',
          '생성된 링크인바이오 URL을 인스타 바이오에 등록하세요',
          '방문자 통계를 확인할 수 있습니다',
        ]},
        { iconKey: 'Link2', title: '단축 URL & 클릭 추적', steps: [
          '제휴 링크를 자동으로 단축 URL로 변환합니다',
          '단축 URL은 클릭수를 자동 추적합니다',
          '플랫폼별, 캠페인별 클릭 통계를 확인할 수 있습니다',
          '단축 URL을 복사하여 각 플랫폼에 쉽게 공유할 수 있습니다',
          '클릭 추적 데이터는 제휴 대시보드에 자동 반영됩니다',
        ]},
      ],
    },
  ],
  growthTitle: '성장 & 게이미피케이션 설명서',
  growthDesc: '크리에이터로 성장하고 계정을 안전하게 보호하는 도구입니다',
  growthSections: [
    {
      title: '',
      items: [
        { iconKey: 'Trophy', title: '퀘스트 & 리더보드', steps: [
          '마케팅 탭이나 홈에서 "퀘스트" 섹션을 확인합니다',
          '일일 퀘스트(촬영, 카드 제작, 공유 등)를 달성하여 포인트를 얻습니다',
          '주간 퀘스트로 더 큰 보상을 받을 수 있습니다',
          '리더보드에서 다른 크리에이터와 순위를 경쟁합니다',
          '퀘스트 달성으로 크레딧 보상을 받을 수 있습니다',
        ]},
        { iconKey: 'ShieldCheck', title: '계정 안전성 검사', steps: [
          '결과 화면이나 설정에서 "계정 안전성"을 확인합니다',
          'AI가 콘텐츠가 SNS 정책에 위반될 위험을 분석합니다',
          '과도한 광고, 금지 표현, 반복 콘텐츠 등의 위험 요소를 감지합니다',
          '위험도가 높으면 안전한 운영 가이드가 제공됩니다',
          '계정 정지를 사전에 방지하세요',
        ]},
        { iconKey: 'FileCheck', title: '독창성 점수', steps: [
          '결과 화면에서 "독창성 점수"를 확인합니다',
          'AI가 콘텐츠의 독창성을 분석하여 점수로 평가합니다',
          '유사 콘텐츠와의 차별성, 창의성, 오리지널리티를 종합 평가합니다',
          '점수가 낮으면 독창성을 높이는 팁이 제공됩니다',
          '높은 독창성 점수는 알고리즘 노출에도 유리합니다',
        ]},
        { iconKey: 'Globe', title: '현지화 안전성', steps: [
          '다국어 콘텐츠 제작 시 "현지화 안전성"을 확인합니다',
          'AI가 문화적으로 부적절한 표현을 사전에 감지합니다',
          '국가별 금지어, 민감한 주제, 오해의 소지가 있는 표현을 경고합니다',
          '해외 진출 시 문화적 위험을 사전에 방지하세요',
        ]},
        { iconKey: 'Stamp', title: '광고 성공 표시 (FTC 공시)', desc: '제휴 광고임을 자동으로 표시하여 플랫폼 정책과 FTC 가이드라인을 준수합니다. 공시 문구는 설정에서 켜거나 끌 수 있고, 숏폼 카드와 공유 콘텐츠에 자동 포함됩니다' },
      ],
    },
  ],
  platformTitle: '플랫폼별 영상 게시 방법',
  platformDesc: '완성된 숏폼 영상을 각 플랫폼에 업로드하는 방법을 단계별로 설명합니다',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: '틱톡 (TikTok) 업로드', steps: [
          '완성 화면에서 "틱톡" 공유 버튼을 탭하거나, 갤러리에 저장한 영상을 사용합니다',
          '틱톡 앱을 실행하고 하단 중앙의 "+" 버튼을 탭합니다',
          '갤러리에서 저장한 숏폼 영상을 선택합니다',
          '편집 화면에서 텍스트, 스티커, 효과를 추가할 수 있습니다 (선택사항)',
          '다음 버튼을 탭하고 영상 제목(캡션)을 입력합니다',
          '관련 해시태그를 추가합니다 (앱에서 추천받은 해시태그 활용)',
          '제휴 링크는 틱톡 프로필 바이오에 넣거나, 댓글에 고정하는 것이 효과적입니다',
          '공개 범위를 "공개"로 설정하고 게시 버튼을 탭합니다',
        ]},
        { iconKey: 'Instagram', title: '인스타그램 릴스 (Instagram Reels) 업로드', steps: [
          '완성 화면에서 "인스타" 공유 버튼을 탭하거나, 갤러리에 저장한 영상을 사용합니다',
          '인스타그램 앱을 실행하고 하단의 "+" 버튼을 탭한 후 "릴스"를 선택합니다',
          '갤러리에서 저장한 숏폼 영상을 선택합니다',
          '음악 추가: 인스타그램 내장 음악이나 원본 영상의 오디오를 선택합니다',
          '필요시 텍스트 스티커를 추가합니다 (상품명이나 후킹 문구를 화면에 표시)',
          '다음 버튼을 탭하고 캡션을 입력합니다',
          '제휴 링크는 캡션에 직접 넣거나, 프로필 바이오 링크를 통해 유도합니다',
          '관련 해시태그를 추가하고 "공개"로 설정한 후 공유 버튼을 탭합니다',
          '릴스 업로드 후 프로필의 "링크" 버튼에 제휴 링크를 등록해 두면 클릭률이 높아집니다',
        ]},
        { iconKey: 'Youtube', title: '유튜브 쇼츠 (YouTube Shorts) 업로드', steps: [
          '완성 화면에서 "쇼츠" 공유 버튼을 탭하거나, 갤러리에 저장한 영상을 사용합니다',
          '유튜브 앱을 실행하고 하단 중앙의 "+" 버튼을 탭한 후 "쇼츠 만들기"를 선택합니다',
          '갤러리에서 저장한 숏폼 영상을 선택합니다',
          '편집 화면에서 텍스트, 필터, 음악을 추가할 수 있습니다 (선택사항)',
          '다음 버튼을 탭하고 영상 제목을 입력합니다',
          '제목에 #Shorts 해시태그를 포함하면 쇼츠 피드에 더 잘 노출됩니다',
          '제휴 링크는 영상 설명란에 넣거나, 채널 프로필 링크에 등록합니다',
          '공개 설정을 "공개"로 하고 업로드 버튼을 탭합니다',
        ]},
        { iconKey: 'Share2', title: '네이버클립 & 카카오톡 공유', steps: [
          '네이버클립: 완성 화면에서 "공유" 버튼을 탭하면 홍보 문구와 이미지가 클립보드에 복사됩니다',
          '네이버클립 앱 또는 네이버TV에서 새 클립 만들기를 선택합니다',
          '저장한 영상을 업로드하고 복사된 홍보 문구를 붙여넣습니다',
          '카카오톡: 공유 버튼으로 메시지에 이미지와 링크를 함께 보낼 수 있습니다',
          '카카오톡 채널이나 오픈채팅방에 영상과 제휴 링크를 공유하면 직접 클릭 유도가 가능합니다',
        ]},
        { iconKey: 'Lightbulb', title: '멀티 플랫폼 동시 업로드 전략', steps: [
          '하나의 숏폼 영상을 틱톡, 인스타 릴스, 유튜브 쇼츠 세 곳에 모두 업로드하면 노출이 3배 늘어납니다',
          '각 플랫폼마다 캡션과 해시태그를 조금씩 다르게 작성하는 것이 알고리즘에 유리합니다',
          '틱톡은 트렌드 해시태그, 인스타는 상품 관련 해시태그, 쇼츠는 #Shorts를 함께 사용하세요',
          '제휴 링크는 각 플랫폼의 프로필 바이오에 동일하게 등록해 두면 관리가 편합니다',
          '업로드 시간대는 저녁 6시~10시(한국 시간)가 가장 시청률이 높습니다',
          '영상 길이는 15~30초로 설정하면 시청 지속 시간이 충분하면서도 알고리즘 노출에 유리합니다',
          '스마트 스케줄러를 사용하면 최적 시간대에 자동으로 업로드 알림을 받을 수 있습니다',
        ]},
      ],
    },
  ],
  soundTitle: '소리 펀치 (사운드 효과) 사용법',
  soundDesc: '인기 밈 효과음을 직접 녹음해서 만화 숏폼에 타이밍별로 추가하는 기능입니다',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: '소리 펀치 편집기 사용법', steps: [
          '만화 숏폼 생성기에서 "고급 옵션"을 펼칩니다',
          '"소리 펀치 컷 편집" 토글을 켭니다 (웹 브라우저에서만 사용 가능)',
          '녹음 버튼을 누르고 마이크에 소리를 내면 실시간으로 음파가 표시됩니다',
          '큰 소리가 감지되면 자동으로 효과 마커가 추가됩니다 (빵, 줌, 코믹 등)',
          '음성 명령으로 효과를 지정할 수도 있습니다 ("빵", "줌 인", "코믹" 등)',
          '녹음을 중지하면 타임라인에 마커가 표시되고 재생할 수 있습니다',
          '마커를 탭하면 효과 종류를 변경하거나 삭제할 수 있습니다',
          '만화 숏폼 생성 시 녹음된 효과가 영상에 자동으로 합성됩니다',
          '모바일에서는 "웹 브라우저에서만 사용할 수 있어요" 메시지가 표시됩니다',
        ]},
      ],
    },
  ],
  helpTitle: '도움말',
  helpItems: [
    { iconKey: 'Info', title: '사용 방법', desc: '사진을 찍거나 업로드하면 AI가 제품을 분석합니다. 결과 화면에서 쇼핑 매칭, 숏폼 카드, 공유를 한 번에 이용하세요.' },
    { iconKey: 'Link2', title: '수수료 링크 적용', desc: "결과 화면에서 '내 수수료 링크 붙여넣기' 버튼으로 브랜드커넥트 링크를 적용하세요. 공유와 카드에 자동 반영됩니다." },
    { iconKey: 'CreditCard', title: '크레딧 관리', desc: 'AI 기능 사용 시 크레딧이 소모됩니다. 에셋 탭에서 잔액을 확인하고 부족하면 추가 구매할 수 있습니다.' },
    { iconKey: 'ShieldCheck', title: '계정 안전', desc: '공유 쿨다운을 준수하고, 계정 안전성 검사를 정기적으로 확인하여 SNS 계정을 보호하세요.' },
  ],
  feedbackTitle: '피드백 & 오류 신고',
  feedbackDesc: '사용 중 불편한 점이나 오류를 발견하면 알려주세요. 여러분의 의견이 앱을 더 좋게 만듭니다.',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: '의견 보내기', desc: '구글 설문지로 피드백을 남겨주세요' },
    { iconKey: 'Bug', title: '오류 신고 & 오픈채팅', desc: '카카오톡 오픈채팅방에서 빠르게 도움받기' },
  ],
  footer: 'ShortConnect (숏커넥트) — 온·오프라인 셀러를 위한 올인원 AI 커머스',
  onboardingTitle: '앱 둘러보기 다시 보기',
  onboardingDesc: '처음 안내를 다시 확인하고 싶다면 눌러주세요',
};

const en: GuideContent = {
  naverSection: {
    title: 'Naver Shopping Connect & Affiliate Platform Guide',
    desc: 'Naver Shopping Connect requires signing up as a creator on Brand Connect (brandconnect.naver.com) and generating dedicated commission links for each product. The app supports multiple affiliate platforms including Naver, Coupang, and Amazon.',
    guideTitle: 'How to Use',
    guideSteps: '1. Sign up as a creator on Naver Brand Connect\n2. Link your channel (blog/Instagram/YouTube)\n3. Search for products you want to promote\n4. Click the link generation button to get your commission link\n5. Enter the link in app settings or paste it directly\n6. Use the affiliate platform switch to also use Coupang, Amazon, and other platforms',
    linkText: 'Go to Naver Brand Connect',
    notice: 'This app uses AI to identify products and automatically generate Naver Shopping search links. For accurate commission tracking, use the individual links issued by Brand Connect. The affiliate platform switch lets you manage commission links across multiple platforms.',
  },
  tabsTitle: 'App Tab Structure',
  tabsDesc: 'The app is organized into 3 main tabs. Here is what each tab contains',
  tabsItems: [
    { iconKey: 'Camera', title: 'Home Tab (Capture & Create)', desc: 'Product capture, AI analysis, short-form cards/carousel/video/comic creation, copywriting, style recommendations, viral prediction — all content creation features are here' },
    { iconKey: 'Megaphone', title: 'Marketing Tab (Marketing Automation)', desc: 'Smart scheduler, weather marketing, inventory alerts, review automation, trend analysis, share cooldown — marketing automation tools' },
    { iconKey: 'FolderOpen', title: 'Assets Tab (Assets & Revenue)', desc: 'Saved assets, link-in-bio, QR dashboard, affiliate dashboard, revenue tracking, credit balance — asset and revenue management tools' },
  ],
  flowTitle: 'Content Creation Workflow',
  flowDesc: 'An overview of the entire content creation flow available in the app',
  flowSteps: [
    { num: 'STEP 1', title: 'Capture & AI Analysis', desc: 'AI automatically identifies product name, category, and price from photos. Multi-angle capture, AR mode, and OCR text extraction are also available' },
    { num: 'STEP 2', title: 'Shopping Match & Affiliate Links', desc: 'Finds the same product on Naver/Coupang/Amazon and auto-generates affiliate commission links with short URLs and click tracking' },
    { num: 'STEP 3', title: 'Short-form Cards & Templates', desc: 'Creates cards with price and review stickers composited on photos. AI image generation, virtual fitting, and background removal are also available' },
    { num: 'STEP 4', title: 'Carousel & Short-form Video', desc: 'Turns multiple cards into slide carousels or short-form videos. Hybrid mode, motion zoom, and video import are also supported' },
    { num: 'STEP 5', title: 'Comic Content Creation', desc: 'AI generates comic scenarios using your product. 5 art styles, AI voice dubbing, sound punch, and episode mode are supported' },
    { num: 'STEP 6', title: 'Share & Revenue Tracking', desc: 'Share to Instagram, TikTok, KakaoTalk and track clicks and revenue. QR codes and link-in-bio enable offline integration' },
    { num: 'STEP 7', title: 'Marketing Automation', desc: 'Optimize upload timing with smart scheduler, automate timely marketing with weather and inventory alerts' },
    { num: 'STEP 8', title: 'Growth & Gamification', desc: 'Grow through quests, leaderboard, and creator tiers. Protect your channel with account safety and originality scores' },
  ],
  featuresTitle: 'Feature Overview',
  featuresDesc: 'All app features organized by category',
  featureSections: [
    {
      title: 'Capture & Analysis',
      items: [
        { iconKey: 'Camera', title: 'Product Capture & Shopping Match', desc: 'Photograph shoes, lighting, clothing — AI identifies the product and matches it on Naver Shopping' },
        { iconKey: 'Clapperboard', title: 'AR Capture Mode', desc: 'Capture products with real-time AR effects applied' },
        { iconKey: 'Grid3x3', title: 'Multi-Angle Capture Guide', desc: 'Guide for shooting front, side, and detail angles of your product' },
        { iconKey: 'ScanLine', title: 'OCR Text Extraction', desc: 'AI automatically extracts text from product packaging and labels to supplement product info' },
      ],
    },
    {
      title: 'Content Creation',
      items: [
        { iconKey: 'Sparkles', title: 'Short-form Template Auto-Complete', desc: 'Auto-generates cards with price and recommended review stickers on photos' },
        { iconKey: 'LayoutTemplate', title: 'Carousel (Multi-Slide)', desc: 'Arrange multiple products or multi-angle photos in order as slides' },
        { iconKey: 'Film', title: 'Short-form Video (Clip)', desc: 'Stitch product photos and text into short videos with transitions, BGM, and motion effects' },
        { iconKey: 'BookOpen', title: 'Comic Short-form (Comic Video)', desc: 'AI generates comic scenarios. 5 art styles, AI dubbing, sound punch, and episode mode supported' },
        { iconKey: 'ImagePlus', title: 'AI Image Generation', desc: 'Generate product images from text prompts using AI' },
        { iconKey: 'Shirt', title: 'Virtual Fitting (AI Try-On)', desc: 'AI generates virtual try-on images for clothing and accessories' },
        { iconKey: 'Layers', title: 'AI Cuts & Background Composite', desc: 'AI generates cuts of your product from various angles and backgrounds' },
        { iconKey: 'Video', title: 'Video Import', desc: 'Import existing videos and convert them to short-form content' },
        { iconKey: 'Scissors', title: 'Background Removal & Image Editing', desc: 'AI automatically removes product backgrounds and saves as transparent images' },
      ],
    },
    {
      title: 'AI Content Tools',
      items: [
        { iconKey: 'PenLine', title: 'Copywriting (Auto Text Generation)', desc: 'AI generates marketing copy based on product analysis results' },
        { iconKey: 'Wand2', title: 'AI Style Recommendation', desc: 'AI recommends design styles matching your product and applies them with one tap' },
        { iconKey: 'Target', title: 'Viral Prediction', desc: 'Predicts viral potential of content as a score with improvement tips' },
        { iconKey: 'Users', title: 'Persona Simulator', desc: 'Simulates how target customers would react to your product' },
        { iconKey: 'Globe', title: 'Global Localization', desc: 'Localizes marketing copy into multiple languages with country-specific hashtags' },
        { iconKey: 'Shuffle', title: 'Multi-Platform Export', desc: 'Generates platform-optimized images for Instagram, TikTok, and YouTube at once' },
        { iconKey: 'TrendingUp', title: 'Trend Matching & Trend Copy', desc: 'Auto-matches real-time SNS trend keywords with products for timely copy' },
        { iconKey: 'Type', title: 'Platform Caption Optimizer', desc: 'Auto-optimizes caption styles and hashtags for each platform' },
      ],
    },
    {
      title: 'Affiliate & Monetization',
      items: [
        { iconKey: 'Link2', title: 'Auto Affiliate Link Generation', desc: 'Instantly creates commission links using your partner ID' },
        { iconKey: 'Send', title: 'Affiliate Platform Switch', desc: 'Switch between Naver, Coupang, Amazon, and other affiliate platforms' },
        { iconKey: 'Wallet', title: 'Affiliate Dashboard & Revenue Tracking', desc: 'Dashboard showing clicks, revenue, and conversion rates at a glance' },
        { iconKey: 'CreditCard', title: 'Credit System', desc: 'Manage and purchase credits needed for AI feature usage' },
        { iconKey: 'QrCode', title: 'QR Code & Watermark', desc: 'Generate QR codes with affiliate links and add as image watermarks' },
        { iconKey: 'Link', title: 'Link-in-Bio', desc: 'Create a creator link-in-bio page to collect all affiliate links in one place' },
      ],
    },
    {
      title: 'Marketing Automation',
      items: [
        { iconKey: 'CalendarClock', title: 'Smart Scheduler', desc: 'Schedule uploads and auto-notify at optimal times' },
        { iconKey: 'CloudRain', title: 'Weather Marketing Agent', desc: 'Auto-generates timely marketing messages based on weather changes' },
        { iconKey: 'Package', title: 'Inventory Alert Agent', desc: 'Tracks product stock and automates restock marketing' },
        { iconKey: 'Megaphone', title: 'Review Automation', desc: 'Collects customer reviews and auto-creates review-based short-form content' },
        { iconKey: 'Share2', title: 'Share Cooldown', desc: 'Prevents excessive sharing and maintains safe intervals for platform algorithms' },
      ],
    },
    {
      title: 'Growth & Gamification',
      items: [
        { iconKey: 'Trophy', title: 'Quests & Leaderboard', desc: 'Complete daily/weekly quests and compete with other creators' },
        { iconKey: 'ShieldCheck', title: 'Account Safety Checker', desc: 'Detects SNS account suspension risks and provides safe operation guides' },
        { iconKey: 'FileCheck', title: 'Originality Score', desc: 'AI analyzes content originality and scores it' },
        { iconKey: 'Globe', title: 'Localization Safety', desc: 'Checks cultural appropriateness of multilingual content and warns of risky expressions' },
        { iconKey: 'Stamp', title: 'Ad Disclosure (FTC Compliance)', desc: 'Automatically marks affiliate ads to comply with platform policies and FTC guidelines' },
      ],
    },
  ],
  usageTitle: 'Content Creation Guide',
  usageDesc: 'Tap each feature to see detailed usage instructions',
  usageSections: [
    {
      title: '',
      items: [
        { iconKey: 'ImageIcon', title: 'Create Short-form Cards (Templates)', steps: [
          'Tap the "Short-form Card" button on the result screen',
          'AI-provided review and price are automatically composited as stickers on the photo',
          'Choose a style (Magazine/Bold/Minimal/Feed) to change the design',
          'You can directly edit price, review, and hashtag text',
          'Use the background removal button for a clean product image',
          'Change color themes to match your brand',
          'Save the completed card or share it directly',
        ]},
        { iconKey: 'LayoutTemplate', title: 'Create Carousel (Multi-Slide)', steps: [
          'Tap the "Carousel" button on the result screen',
          'Arrange multiple products or multi-angle photos in order',
          'Each slide can have individual text and price input',
          'Drag to change slide order',
          'Apply a unified style across all slides',
          'Automatically adjusted to vertical size for Instagram posts',
          'Save the completed carousel as an image or share it',
        ]},
        { iconKey: 'Film', title: 'Create Short-form Video (Clip)', steps: [
          'Tap the "Short-form Video" button on the result screen',
          'Product photos and text are stitched into a short video',
          'Transition effects and text animations are automatically applied',
          'Choose background music (Upbeat/Calm/Energetic/None) and motion effects (Kenburns/Zoom/Pan)',
          'Advanced settings let you change aspect ratio (vertical/horizontal/square) and template style',
          'Enable hybrid mode (photo-to-comic transition) for a comic effect in the second half',
          'Choose video length (10s/15s/20s/30s) — default 15s',
          'Optimized for vertical (9:16) ratio for TikTok/Instagram Reels/YouTube Shorts',
          'Save the completed video to gallery or cloud, then upload to each platform',
        ]},
        { iconKey: 'BookOpen', title: 'Create Comic Short-form (Comic Video)', steps: [
          'Tap the "Comic Short-form" button on the result screen',
          'AI automatically generates a comic scenario using your product (single/2-panel/3-panel split)',
          'You can directly edit dialogue and situations for each panel',
          'Choose a webtoon style (Instatoon/B-grade/Food comic/American comic/Studio Ghibli style)',
          'Choose an AI narrator voice (Bright 20s/Calm narration/B-grade accent) for dubbing',
          'In advanced settings, select video length (10s/15s/20s/30s) — auto-recommended based on panel count',
          'Add AI narration dubbing, emotion expression overlays, and MBTI-tailored commentary',
          'Enable episode mode for a "Day 1–Day 3–Day 7" timeline story',
          'Add comic sound effects by timing with the Sound Punch feature',
          'Sound effects are auto-matched by emotion (Surprise: Whoa!, Happy: Yay~, Confidence: Thumbs up!)',
          'Save the completed comic short-form or share directly to TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'Film', title: 'Create Timeline Short-form (Episode Series)', steps: [
          'Tap the "Comic Short-form" button on the result screen',
          'Enable "Episode Mode" in advanced settings',
          'A timeline story (Day 1–Day 3–Day 7) comic short-form is automatically produced',
          'You can edit the scenario and dialogue for each day',
          'Webtoon style and narration dubbing can be applied together',
          'Save the completed timeline short-form or share to TikTok/Instagram/Shorts',
        ]},
        { iconKey: 'ImagePlus', title: 'AI Image Generation', steps: [
          'Use the "AI Image Generation" feature on the result screen',
          'AI generates product images from text prompts',
          'Auto-prompts are suggested based on product analysis',
          'Generated images can be used directly in short-form cards or carousels',
          'Generate multiple images and choose the best one',
        ]},
        { iconKey: 'Shirt', title: 'Virtual Fitting (AI Try-On)', steps: [
          'Check the "Virtual Fitting" section on the result screen',
          'AI generates try-on scenes based on product photos',
          'Optimized for wearable products like clothing and accessories',
          'Tap a generated image to view it larger',
          'Use "Use This Image" to set the try-on image as the main image',
          'Save generated images or use them in short-form cards',
        ]},
        { iconKey: 'Layers', title: 'AI Cuts & Background Composite', steps: [
          'Check the "AI Cuts" section on the result screen',
          'AI generates cuts as if your product was photographed from various angles and backgrounds',
          'Automatically composited with studio, nature, store, and gradient backgrounds',
          'Tap a generated cut to view it larger',
          'Use "Use This Image" to set your preferred cut as the main image',
          'Multiple cuts can be used in carousels or short-form videos',
        ]},
        { iconKey: 'Grid3x3', title: 'Multi-Angle Capture Guide', steps: [
          'Select "Multi-Angle Capture" mode from the Home tab',
          'Guides for front, side, and detail angles are displayed',
          'Shoot photos following each guide in order',
          'Captured 3-angle photos are automatically used in carousels and short-form videos',
          'Showing multiple sides of your product increases purchase conversion',
        ]},
        { iconKey: 'ScanLine', title: 'OCR Text Extraction', steps: [
          'Select "OCR Scan" mode from the Home tab',
          'Point the camera at product packaging or labels',
          'AI automatically extracts text to supplement product name, ingredients, origin, etc.',
          'Review and edit extracted text as needed',
          'Extracted info is automatically reflected in copywriting and short-form cards',
        ]},
        { iconKey: 'PenLine', title: 'Copywriting (Auto Text Generation)', steps: [
          'Tap the "Write Copy" button on the result screen',
          'AI generates marketing copy based on product analysis results',
          'Choose tone and manner (Casual/Professional/Emotional/Humor)',
          'Copy the generated copy as-is or edit before use',
          'Hashtag recommendations are also provided',
          'Compare multiple copy versions and choose the best one',
        ]},
        { iconKey: 'Type', title: 'Review & One-line Comment', steps: [
          'Tap the "Review Input" button on the result screen',
          'Write your own one-line review or get AI recommendations',
          'Written reviews are automatically reflected in short-form cards and carousels',
          'Editing a review updates all linked content',
        ]},
        { iconKey: 'Scissors', title: 'Background Removal & Image Editing', steps: [
          'Tap the "Remove Background" button on the result screen',
          'AI automatically detects and removes the product background',
          'Saved as a transparent background image for versatile design use',
          'The removed image is automatically applied to short-form cards, carousels, and comics',
          'You can manually change the background color if needed',
        ]},
        { iconKey: 'Video', title: 'Video Import', steps: [
          'Use the "Video Import" feature on the result screen',
          'Import previously recorded videos and convert them to short-form content',
          'Automatically extract key segments from videos to create short-forms',
          'Add text and stickers to extracted segments',
          'Recycle existing video assets to shorten content creation time',
        ]},
        { iconKey: 'Wand2', title: 'AI Style Recommendation', steps: [
          'Check the "AI Style" section on the result screen',
          'AI recommends design styles matching the product category and mood',
          'Tap a recommended style to apply it instantly to the short-form card',
          'Changing style automatically adjusts text layout, colors, and fonts',
          'Selecting a style applies it consistently across all content',
        ]},
        { iconKey: 'Target', title: 'Viral Prediction', steps: [
          'Check the "Viral Prediction" section on the result screen',
          'AI predicts the viral potential of content as a score',
          'The prediction score evaluates hook power, trend fit, and shareability',
          'Tap improvement suggestions for tips to increase the score',
          'Editing copy or style based on suggestions recalculates the prediction score',
        ]},
        { iconKey: 'Users', title: 'Persona Simulator', steps: [
          'Check the "Persona Simulator" section on the result screen',
          'Select a target customer persona (age, gender, interests)',
          'AI simulates how the persona would evaluate the product',
          'View expected reactions, purchase probability, and key appeal points',
          'Use simulation results to optimize your marketing copy',
        ]},
        { iconKey: 'Globe', title: 'Global Localization', steps: [
          'Check the "Global Localization" section on the result screen',
          'Translate marketing copy into English, Japanese, Chinese, Vietnamese, Spanish, and more',
          'Not just translation — localized to each country\'s culture and SNS trends',
          'Country-specific popular hashtags and marketing tones are auto-reflected',
          'Tap translated copy to copy to clipboard',
          'Quickly create platform-optimized content for overseas expansion',
        ]},
        { iconKey: 'Shuffle', title: 'Multi-Platform Export', steps: [
          'Check the "Multi-Platform Export" section on the result screen',
          'Generate images optimized for Instagram, TikTok, and YouTube Shorts all at once',
          'Optimal aspect ratio and text position are auto-adjusted per platform',
          'Recommended hashtags and caption styles are auto-applied per platform',
          'Save generated images individually for each platform',
          'Maximize exposure with simultaneous uploads to all three platforms',
        ]},
        { iconKey: 'TrendingUp', title: 'Trend Matching', steps: [
          'Check the "Trend Matching" section on the result screen',
          'AI auto-matches currently trending SNS keywords with your product',
          'Tap a real-time trend keyword to auto-generate related marketing copy',
          'Trend-matched hashtag recommendations are also provided',
          'Create timely content to boost algorithm exposure',
        ]},
        { iconKey: 'Store', title: 'My Store Info & Offline Integration', steps: [
          'Check the "My Store Info" section on the result screen',
          'Register offline store info (address, hours, phone number)',
          'Registered store info is automatically included in short-form cards and shared content',
          'Customers can check store location directly from content',
          'Use for online-offline integrated marketing',
        ]},
      ],
    },
  ],
  automationTitle: 'Marketing Automation Guide',
  automationDesc: 'Automation tools available in the Marketing tab',
  automationSections: [
    {
      title: '',
      items: [
        { iconKey: 'CalendarClock', title: 'Smart Scheduler', steps: [
          'Open "Smart Scheduler" from the Marketing tab',
          'Select the content and platform to upload',
          'Set the scheduled time and get auto-notified at optimal times',
          'Optimal upload times are auto-recommended per platform',
          'Schedule multiple content items sequentially',
          'Review and edit scheduled content from the list',
        ]},
        { iconKey: 'CloudRain', title: 'Weather Marketing Agent', steps: [
          'Open "Weather Marketing" from the Marketing tab',
          'Current weather and forecast are automatically loaded',
          'AI generates weather-appropriate marketing messages (e.g., rainy day → indoor product picks)',
          'View marketing history by weather condition',
          'Receive automatic marketing alerts for specific weather conditions',
          'Timely weather marketing boosts algorithm exposure',
        ]},
        { iconKey: 'Package', title: 'Inventory Alert Agent', steps: [
          'Open "Inventory Alerts" from the Marketing tab',
          'Register product stock status to track',
          'When stock is low, AI auto-generates restock marketing messages',
          'Receive alerts for near-out-of-stock and restock events',
          'Short-form content creation is recommended based on stock status',
        ]},
        { iconKey: 'Megaphone', title: 'Review Automation', steps: [
          'Open "Review Automation" from the Marketing tab',
          'Collect and manage customer reviews',
          'AI analyzes reviews and auto-classifies positive/negative sentiment',
          'Positive reviews are used to auto-create review-based short-form content',
          'Negative reviews highlight areas for improvement',
          'Review-based content has high credibility and conversion rates',
        ]},
        { iconKey: 'Share2', title: 'Share Cooldown', steps: [
          'Excessive sharing can be flagged as spam by platform algorithms',
          'The app automatically calculates safe sharing intervals per platform',
          'The share button is disabled during cooldown periods',
          'Remaining wait time is displayed so you know when you can share again',
          'Follow cooldown alerts to protect your account',
        ]},
      ],
    },
  ],
  monetizationTitle: 'Affiliate & Monetization Guide',
  monetizationDesc: 'Monetization tools available in the Assets tab and result screen',
  monetizationSections: [
    {
      title: '',
      items: [
        { iconKey: 'Send', title: 'Affiliate Platform Switch', steps: [
          'Switch affiliate platforms from the result screen or settings',
          'Choose from Naver, Coupang, Amazon, and other platforms',
          'Enter each platform\'s partner ID in settings',
          'Switching auto-generates commission links for that platform',
          'Use multiple platforms simultaneously to maximize revenue',
        ]},
        { iconKey: 'Wallet', title: 'Affiliate Dashboard & Revenue Tracking', steps: [
          'Open "Affiliate Dashboard" from the Assets tab',
          'View total clicks, revenue, and conversion rates at a glance',
          'See revenue analysis by platform and by product',
          'Check revenue trend graphs by period',
          'Analyze which products generate the most revenue and plan your strategy',
        ]},
        { iconKey: 'CreditCard', title: 'Credit System', steps: [
          'AI feature usage consumes credits',
          'Check your current credit balance in the Assets tab',
          'Purchase more credits from the credit purchase modal when running low',
          'Free monthly credits are provided based on your creator tier',
          'Use the AI cache feature to use credits efficiently',
        ]},
        { iconKey: 'QrCode', title: 'QR Code & Watermark', steps: [
          'Use the "QR Code" feature on the result screen',
          'QR codes with affiliate links are auto-generated',
          'Add QR codes as watermarks on short-form card images',
          'Print QR codes for offline stores or business cards',
          'Track QR scans from the QR review dashboard',
        ]},
        { iconKey: 'Link', title: 'Link-in-Bio', steps: [
          'Open "Link-in-Bio" from the Assets tab',
          'Create a creator profile page',
          'Collect all affiliate links on one page',
          'Set profile photo, bio text, and social links',
          'Register the generated link-in-bio URL in your Instagram bio',
          'View visitor statistics',
        ]},
        { iconKey: 'Link2', title: 'Short URL & Click Tracking', steps: [
          'Affiliate links are automatically converted to short URLs',
          'Short URLs automatically track click counts',
          'View click statistics by platform and by campaign',
          'Copy short URLs for easy sharing on each platform',
          'Click tracking data is automatically reflected in the affiliate dashboard',
        ]},
      ],
    },
  ],
  growthTitle: 'Growth & Gamification Guide',
  growthDesc: 'Tools to grow as a creator and protect your account safely',
  growthSections: [
    {
      title: '',
      items: [
        { iconKey: 'Trophy', title: 'Quests & Leaderboard', steps: [
          'Check the "Quests" section from the Marketing tab or Home',
          'Complete daily quests (capture, card creation, sharing) to earn points',
          'Weekly quests offer bigger rewards',
          'Compete with other creators on the leaderboard',
          'Earn credit rewards by completing quests',
        ]},
        { iconKey: 'ShieldCheck', title: 'Account Safety Checker', steps: [
          'Check "Account Safety" from the result screen or settings',
          'AI analyzes the risk of your content violating SNS policies',
          'Detects risk factors like excessive advertising, banned expressions, repetitive content',
          'When risk is high, safe operation guides are provided',
          'Prevent account suspension before it happens',
        ]},
        { iconKey: 'FileCheck', title: 'Originality Score', steps: [
          'Check "Originality Score" on the result screen',
          'AI analyzes content originality and scores it',
          'Evaluates differentiation from similar content, creativity, and overall originality',
          'Low scores come with tips to increase originality',
          'High originality scores are also favorable for algorithm exposure',
        ]},
        { iconKey: 'Globe', title: 'Localization Safety', steps: [
          'Check "Localization Safety" when creating multilingual content',
          'AI detects culturally inappropriate expressions in advance',
          'Warns about country-specific banned words, sensitive topics, and misleading expressions',
          'Prevent cultural risks before expanding overseas',
        ]},
        { iconKey: 'Stamp', title: 'Ad Disclosure (FTC Compliance)', desc: 'Automatically marks affiliate ads to comply with platform policies and FTC guidelines. Disclosure text can be toggled in settings and is automatically included in short-form cards and shared content' },
      ],
    },
  ],
  platformTitle: 'Platform Upload Guide',
  platformDesc: 'Step-by-step instructions for uploading completed short-form videos to each platform',
  platformSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'TikTok Upload', steps: [
          'Tap the "TikTok" share button on the result screen, or use a video saved to gallery',
          'Open the TikTok app and tap the "+" button at the bottom center',
          'Select the saved short-form video from your gallery',
          'Add text, stickers, and effects on the edit screen (optional)',
          'Tap Next and enter a video title (caption)',
          'Add relevant hashtags (use the app\'s recommended hashtags)',
          'Affiliate links are most effective in your TikTok profile bio or pinned comments',
          'Set visibility to "Public" and tap Post',
        ]},
        { iconKey: 'Instagram', title: 'Instagram Reels Upload', steps: [
          'Tap the "Instagram" share button on the result screen, or use a video saved to gallery',
          'Open the Instagram app, tap the "+" button, and select "Reels"',
          'Select the saved short-form video from your gallery',
          'Add music: Choose from Instagram\'s built-in music or the original video audio',
          'Add text stickers if needed (show product name or hook text on screen)',
          'Tap Next and enter a caption',
          'Add affiliate links directly in the caption or via profile bio link',
          'Add relevant hashtags, set to "Public", and tap Share',
          'After uploading the Reel, register the affiliate link in your profile\'s "Link" button for higher click rates',
        ]},
        { iconKey: 'Youtube', title: 'YouTube Shorts Upload', steps: [
          'Tap the "Shorts" share button on the result screen, or use a video saved to gallery',
          'Open the YouTube app, tap the "+" button, and select "Create Short"',
          'Select the saved short-form video from your gallery',
          'Add text, filters, and music on the edit screen (optional)',
          'Tap Next and enter a video title',
          'Include the #Shorts hashtag in the title for better Shorts feed exposure',
          'Add affiliate links in the video description or channel profile link',
          'Set visibility to "Public" and tap Upload',
        ]},
        { iconKey: 'Share2', title: 'Naver Clip & KakaoTalk Sharing', steps: [
          'Naver Clip: Tap the "Share" button to copy promotional text and image to clipboard',
          'Open the Naver Clip app or Naver TV and select Create New Clip',
          'Upload the saved video and paste the copied promotional text',
          'KakaoTalk: Use the share button to send images and links together in a message',
          'Share videos and affiliate links in KakaoTalk channels or open chat rooms for direct click engagement',
        ]},
        { iconKey: 'Lightbulb', title: 'Multi-Platform Simultaneous Upload Strategy', steps: [
          'Uploading one short-form video to TikTok, Instagram Reels, and YouTube Shorts triples your exposure',
          'Write slightly different captions and hashtags for each platform — this helps with the algorithm',
          'Use trend hashtags for TikTok, product-related hashtags for Instagram, and #Shorts for YouTube',
          'Register the same affiliate link in each platform\'s profile bio for easy management',
          'The best upload time is 6–10 PM (local time) for highest viewership',
          'Set video length to 15–30 seconds for sufficient watch time and algorithm-friendly exposure',
          'Use the Smart Scheduler to get auto-notified at optimal upload times',
        ]},
      ],
    },
  ],
  soundTitle: 'Sound Punch (Sound Effects) Guide',
  soundDesc: 'Record popular meme sounds and add them to comic short-forms by timing',
  soundSections: [
    {
      title: '',
      items: [
        { iconKey: 'Music2', title: 'Sound Punch Editor Usage', steps: [
          'Expand "Advanced Options" in the comic short-form generator',
          'Enable the "Sound Punch Cut Edit" toggle (web browser only)',
          'Press the record button and make sounds into the mic — waveforms display in real time',
          'Loud sounds are automatically detected and effect markers are added (Bang, Zoom, Comic, etc.)',
          'You can also specify effects with voice commands ("Bang", "Zoom in", "Comic", etc.)',
          'Stop recording to see markers on the timeline and play them back',
          'Tap a marker to change the effect type or delete it',
          'Recorded effects are automatically composited into the video during comic short-form generation',
          'On mobile, a "Only available in web browser" message is displayed',
        ]},
      ],
    },
  ],
  helpTitle: 'Help',
  helpItems: [
    { iconKey: 'Info', title: 'How to Use', desc: 'Take or upload a photo and AI will analyze the product. Use shopping match, short-form cards, and sharing all from the result screen.' },
    { iconKey: 'Link2', title: 'Applying Commission Links', desc: "Use the 'Paste my commission link' button on the result screen to apply your Brand Connect link. It will be automatically reflected in sharing and cards." },
    { iconKey: 'CreditCard', title: 'Credit Management', desc: 'AI feature usage consumes credits. Check your balance in the Assets tab and purchase more when needed.' },
    { iconKey: 'ShieldCheck', title: 'Account Safety', desc: 'Follow share cooldowns and regularly check account safety to protect your SNS accounts.' },
  ],
  feedbackTitle: 'Feedback & Bug Reports',
  feedbackDesc: 'Let us know about any inconveniences or bugs. Your feedback makes the app better.',
  feedbackItems: [
    { iconKey: 'MessageSquare', title: 'Send Feedback', desc: 'Leave feedback via the Google Form' },
    { iconKey: 'Bug', title: 'Bug Reports & Open Chat', desc: 'Get quick help in the KakaoTalk open chat room' },
  ],
  footer: 'ShortConnect — All-in-one AI commerce for online and offline sellers',
  onboardingTitle: 'Replay App Tour',
  onboardingDesc: 'Tap to see the initial guide again',
};

const ja: GuideContent = {
  ...en,
  naverSection: {
    title: 'Naverショッピングコネクト & アフィリエイトプラットフォームガイド',
    desc: 'Naverショッピングコネクトは、Brand Connectでクリエイター登録後、商品ごとに専用コミッションリンクを発行するシステムです。アプリはNaver、Coupang、Amazonなど複数のアフィリエイトプラットフォームに対応しています。',
    guideTitle: '使い方',
    guideSteps: '1. Naver Brand Connectにクリエイターとして登録\n2. チャンネル（ブログ/インスタ/YouTube）を連携\n3. プロモーション商品を検索\n4. リンク発行ボタンでコミッションリンクを取得\n5. アプリ設定にリンクを入力または直接貼り付け\n6. アフィリエイトプラットフォーム切替でCoupang/Amazonも使用可能',
    linkText: 'Naver Brand Connectへ移動',
    notice: '本アプリはAIが商品を識別し、Naverショッピング検索リンクを自動生成します。正確なコミッション追跡にはBrand Connect発行のリンクを使用してください。',
  },
  tabsTitle: 'アプリタブ構造',
  tabsDesc: 'アプリは3つのメインタブで構成されています',
  tabsItems: [
    { iconKey: 'Camera', title: 'ホームタブ（撮影＆制作）', desc: '商品撮影、AI分析、ショートフォーム制作、コピー作成、スタイル推薦、バイラル予測など全制作機能' },
    { iconKey: 'Megaphone', title: 'マーケティングタブ（自動化）', desc: 'スマートスケジューラー、天気マーケティング、在庫アラート、レビュー自動化、トレンド分析' },
    { iconKey: 'FolderOpen', title: 'アセットタブ（資産＆収益）', desc: '保存アセット、リンクインバイオ、QRダッシュボード、アフィリエイトダッシュボード、収益追跡' },
  ],
  flowTitle: 'コンテンツ制作ワークフロー',
  flowDesc: 'アプリで制作できるコンテンツの全体ワークフロー',
  flowSteps: [
    { num: 'STEP 1', title: '撮影 & AI分析', desc: 'AIが商品名、カテゴリ、価格帯を自動識別。多角度撮影、ARモード、OCRテキスト抽出も可能' },
    { num: 'STEP 2', title: 'ショッピングマッチ & アフィリエイト', desc: 'Naver/Coupang/Amazonで同一商品を見つけ、コミッションリンクと短縮URLを自動生成' },
    { num: 'STEP 3', title: 'ショートフォームカード', desc: '写真に価格とレビューステッカーを合成。AI画像生成、仮想試着、背景除去も可能' },
    { num: 'STEP 4', title: 'カルーセル & ショート動画', desc: '複数カードをカルーセルや動画に。ハイブリッドモード、ビデオインポートも対応' },
    { num: 'STEP 5', title: '漫画コンテンツ制作', desc: 'AIが漫画シナリオを生成。5種の画風、AIダビング、サウンドパンチ、エピソードモード対応' },
    { num: 'STEP 6', title: '共有 & 収益追跡', desc: 'インスタ、TikTok、カカオトークで共有し収益を追跡。QRコード、リンクインバイオでオフライン連携' },
    { num: 'STEP 7', title: 'マーケティング自動化', desc: 'スマートスケジューラー、天気/在庫アラートでタイムリーなマーケティングを自動化' },
    { num: 'STEP 8', title: '成長 & ゲーミフィケーション', desc: 'クエスト、リーダーボード、クリエイターTierで成長。アカウント安全性と独創性スコアで保護' },
  ],
  featuresTitle: '機能紹介',
  featuresDesc: 'カテゴリ別の全機能',
  featureSections: en.featureSections,
  usageTitle: 'コンテンツ制作ガイド',
  usageDesc: '各機能をタップして詳細な使い方を確認',
  usageSections: en.usageSections,
  automationTitle: 'マーケティング自動化ガイド',
  automationDesc: 'マーケティングタブで使用できる自動化ツール',
  automationSections: en.automationSections,
  monetizationTitle: 'アフィリエイト & 収益化ガイド',
  monetizationDesc: 'アセットタブと結果画面で使用できる収益化ツール',
  monetizationSections: en.monetizationSections,
  growthTitle: '成長 & ゲーミフィケーションガイド',
  growthDesc: 'クリエイターとして成長しアカウントを安全に保護するツール',
  growthSections: en.growthSections,
  platformTitle: 'プラットフォーム別投稿ガイド',
  platformDesc: '完成したショート動画を各プラットフォームにアップロードする手順',
  platformSections: en.platformSections,
  soundTitle: 'サウンドパンチガイド',
  soundDesc: 'ミーム効果音を録音して漫画ショートフォームに追加',
  soundSections: en.soundSections,
  helpTitle: 'ヘルプ',
  helpItems: en.helpItems,
  feedbackTitle: 'フィードバック & バグ報告',
  feedbackDesc: 'ご不便やバグがあればお知らせください。',
  feedbackItems: en.feedbackItems,
  footer: 'ShortConnect — オンライン・オフラインセラーのためのオールインワンAIコマース',
  onboardingTitle: 'アプリツアーをもう一度見る',
  onboardingDesc: '初期ガイドをもう一度確認',
};

const vi: GuideContent = {
  ...en,
  naverSection: {
    title: 'Hướng dẫn Naver Shopping Connect & Affiliate',
    desc: 'Naver Shopping Connect yêu cầu đăng ký trên Brand Connect và tạo liên kết hoa hồng riêng. Ứng dụng hỗ trợ nhiều nền tảng bao gồm Naver, Coupang, Amazon.',
    guideTitle: 'Cách sử dụng',
    guideSteps: '1. Đăng ký trên Naver Brand Connect\n2. Liên kết kênh (blog/Instagram/YouTube)\n3. Tìm sản phẩm để quảng bá\n4. Tạo liên kết hoa hồng\n5. Nhập liên kết vào cài đặt ứng dụng\n6. Chuyển nền tảng để dùng Coupang/Amazon',
    linkText: 'Đi đến Naver Brand Connect',
    notice: 'Ứng dụng dùng AI nhận diện sản phẩm và tạo liên kết Naver Shopping. Dùng liên kết Brand Connect để theo dõi chính xác.',
  },
  tabsTitle: 'Cấu trúc Tab ứng dụng',
  tabsDesc: 'Ứng dụng có 3 tab chính',
  tabsItems: [
    { iconKey: 'Camera', title: 'Tab Home (Chụp & Tạo)', desc: 'Chụp sản phẩm, phân tích AI, tạo short-form, copy, phong cách, dự đoán viral' },
    { iconKey: 'Megaphone', title: 'Tab Marketing (Tự động hóa)', desc: 'Lịch thông minh, marketing thời tiết, cảnh báo tồn kho, tự động đánh giá' },
    { iconKey: 'FolderOpen', title: 'Tab Assets (Tài sản & Doanh thu)', desc: 'Tài sản đã lưu, link-in-bio, QR dashboard, affiliate dashboard, theo dõi doanh thu' },
  ],
  flowTitle: 'Quy trình tạo nội dung',
  flowDesc: 'Tổng quan quy trình tạo nội dung trong ứng dụng',
  flowSteps: [
    { num: 'BƯỚC 1', title: 'Chụp & Phân tích AI', desc: 'AI nhận diện sản phẩm. Chụp đa góc, AR, OCR cũng có sẵn' },
    { num: 'BƯỚC 2', title: 'Khớp & Liên kết', desc: 'Tìm sản phẩm trên Naver/Coupang/Amazon và tạo liên kết hoa hồng' },
    { num: 'BƯỚC 3', title: 'Thẻ & Mẫu', desc: 'Tạo thẻ với sticker giá và đánh giá. AI ảnh, thử ảo, xóa nền' },
    { num: 'BƯỚC 4', title: 'Carousel & Video', desc: 'Chuyển thẻ thành carousel hoặc video. Hybrid, import video' },
    { num: 'BƯỚC 5', title: 'Truyện tranh', desc: 'AI tạo kịch bản. 5 phong cách, AI lồng tiếng, sound punch, episode' },
    { num: 'BƯỚC 6', title: 'Chia sẻ & Doanh thu', desc: 'Chia sẻ lên Instagram/TikTok/KakaoTalk. QR, link-in-bio cho offline' },
    { num: 'BƯỚC 7', title: 'Tự động hóa Marketing', desc: 'Lịch thông minh, cảnh báo thời tiết/tồn kho cho marketing kịp thời' },
    { num: 'BƯỚC 8', title: 'Tăng trưởng', desc: 'Quest, leaderboard, tier. An toàn tài khoản, điểm độc sáng' },
  ],
  featuresTitle: 'Tổng quan tính năng',
  featuresDesc: 'Tất cả tính năng theo danh mục',
  featureSections: en.featureSections,
  usageTitle: 'Hướng dẫn tạo nội dung',
  usageDesc: 'Nhấn từng tính năng để xem hướng dẫn chi tiết',
  usageSections: en.usageSections,
  automationTitle: 'Hướng dẫn Tự động hóa Marketing',
  automationDesc: 'Công cụ tự động hóa trong tab Marketing',
  automationSections: en.automationSections,
  monetizationTitle: 'Hướng dẫn Affiliate & Doanh thu',
  monetizationDesc: 'Công cụ doanh thu trong tab Assets và màn hình kết quả',
  monetizationSections: en.monetizationSections,
  growthTitle: 'Hướng dẫn Tăng trưởng',
  growthDesc: 'Công cụ tăng trưởng và bảo vệ tài khoản',
  growthSections: en.growthSections,
  platformTitle: 'Hướng dẫn tải lên theo nền tảng',
  platformDesc: 'Hướng dẫn từng bước tải video lên từng nền tảng',
  platformSections: en.platformSections,
  soundTitle: 'Hướng dẫn Sound Punch',
  soundDesc: 'Thu âm hiệu ứng và thêm vào truyện tranh short-form',
  soundSections: en.soundSections,
  helpTitle: 'Trợ giúp',
  helpItems: en.helpItems,
  feedbackTitle: 'Phản hồi & Báo cáo lỗi',
  feedbackDesc: 'Cho chúng tôi biết về bất tiện hoặc lỗi.',
  feedbackItems: en.feedbackItems,
  footer: 'ShortConnect — AI commerce all-in-one cho nhà bán online và offline',
  onboardingTitle: 'Xem lại hướng dẫn ứng dụng',
  onboardingDesc: 'Nhấn để xem lại hướng dẫn ban đầu',
};

const es: GuideContent = {
  ...en,
  naverSection: {
    title: 'Guía de Naver Shopping Connect & Affiliate',
    desc: 'Naver Shopping Connect requiere registrarse en Brand Connect y generar enlaces de comisión. La app soporta múltiples plataformas: Naver, Coupang, Amazon.',
    guideTitle: 'Cómo usar',
    guideSteps: '1. Regístrate en Naver Brand Connect\n2. Vincula tu canal\n3. Busca productos\n4. Genera enlaces de comisión\n5. Ingresa el enlace en la configuración\n6. Cambia entre plataformas para usar Coupang/Amazon',
    linkText: 'Ir a Naver Brand Connect',
    notice: 'La app usa IA para identificar productos y generar enlaces. Usa enlaces de Brand Connect para seguimiento preciso.',
  },
  tabsTitle: 'Estructura de Pestañas',
  tabsDesc: 'La app tiene 3 pestañas principales',
  tabsItems: [
    { iconKey: 'Camera', title: 'Pestaña Home (Capturar & Crear)', desc: 'Captura, análisis IA, short-form, copy, estilo, predicción viral' },
    { iconKey: 'Megaphone', title: 'Pestaña Marketing (Automatización)', desc: 'Programador, marketing por clima, alertas de inventario, automatización de reseñas' },
    { iconKey: 'FolderOpen', title: 'Pestaña Assets (Recursos & Ingresos)', desc: 'Recursos guardados, link-in-bio, QR dashboard, affiliate dashboard, ingresos' },
  ],
  flowTitle: 'Flujo de creación de contenido',
  flowDesc: 'Vista general del flujo de creación en la app',
  flowSteps: [
    { num: 'PASO 1', title: 'Captura & Análisis IA', desc: 'IA identifica el producto. Multi-ángulo, AR, OCR disponibles' },
    { num: 'PASO 2', title: 'Coincidencia & Enlaces', desc: 'Encuentra el producto en Naver/Coupang/Amazon y genera enlaces' },
    { num: 'PASO 3', title: 'Tarjetas & Plantillas', desc: 'Crea tarjetas con stickers. IA de imágenes, prueba virtual, eliminar fondo' },
    { num: 'PASO 4', title: 'Carrusel & Video', desc: 'Convierte tarjetas en carrusel o video. Modo híbrido, importar video' },
    { num: 'PASO 5', title: 'Contenido Cómic', desc: 'IA genera cómics. 5 estilos, doblaje IA, sound punch, episodios' },
    { num: 'PASO 6', title: 'Compartir & Ingresos', desc: 'Comparte en Instagram/TikTok/KakaoTalk. QR, link-in-bio para offline' },
    { num: 'PASO 7', title: 'Automatización Marketing', desc: 'Programador inteligente, alertas de clima/inventario' },
    { num: 'PASO 8', title: 'Crecimiento', desc: 'Quests, leaderboard, tiers. Seguridad de cuenta, originalidad' },
  ],
  featuresTitle: 'Resumen de Funciones',
  featuresDesc: 'Todas las funciones por categoría',
  featureSections: en.featureSections,
  usageTitle: 'Guía de Creación de Contenido',
  usageDesc: 'Toca cada función para ver instrucciones detalladas',
  usageSections: en.usageSections,
  automationTitle: 'Guía de Automatización de Marketing',
  automationDesc: 'Herramientas de automatización en la pestaña Marketing',
  automationSections: en.automationSections,
  monetizationTitle: 'Guía de Affiliate & Monetización',
  monetizationDesc: 'Herramientas de monetización en la pestaña Assets y pantalla de resultados',
  monetizationSections: en.monetizationSections,
  growthTitle: 'Guía de Crecimiento',
  growthDesc: 'Herramientas para crecer como creador y proteger tu cuenta',
  growthSections: en.growthSections,
  platformTitle: 'Guía de Subida por Plataforma',
  platformDesc: 'Instrucciones paso a paso para subir videos a cada plataforma',
  platformSections: en.platformSections,
  soundTitle: 'Guía de Sound Punch',
  soundDesc: 'Graba efectos de sonido y añádelos a cómics short-form',
  soundSections: en.soundSections,
  helpTitle: 'Ayuda',
  helpItems: en.helpItems,
  feedbackTitle: 'Comentarios y Reporte de Errores',
  feedbackDesc: 'Cuéntanos sobre inconvenientes o errores.',
  feedbackItems: en.feedbackItems,
  footer: 'ShortConnect — AI commerce todo-en-uno para vendedores online y offline',
  onboardingTitle: 'Ver Recorrido de la App',
  onboardingDesc: 'Toca para ver la guía inicial nuevamente',
};

const zh: GuideContent = {
  ...en,
  naverSection: {
    title: 'Naver Shopping Connect & 联盟营销指南',
    desc: 'Naver Shopping Connect 需要在 Brand Connect 注册并生成专属佣金链接。应用支持多个平台：Naver、Coupang、Amazon。',
    guideTitle: '使用方法',
    guideSteps: '1. 在 Naver Brand Connect 注册\n2. 关联频道\n3. 搜索产品\n4. 生成佣金链接\n5. 在应用设置中输入链接\n6. 切换平台使用 Coupang/Amazon',
    linkText: '前往 Naver Brand Connect',
    notice: '应用使用 AI 识别产品并生成链接。请使用 Brand Connect 的链接进行精确追踪。',
  },
  tabsTitle: '应用标签页结构',
  tabsDesc: '应用有 3 个主标签页',
  tabsItems: [
    { iconKey: 'Camera', title: '首页标签（拍摄 & 创作）', desc: '拍摄、AI 分析、短频制作、文案、风格、病毒预测' },
    { iconKey: 'Megaphone', title: '营销标签（自动化）', desc: '智能调度、天气营销、库存提醒、评论自动化' },
    { iconKey: 'FolderOpen', title: '资产标签（资产 & 收益）', desc: '已保存资产、link-in-bio、QR 仪表板、联盟仪表板、收益追踪' },
  ],
  flowTitle: '内容制作流程',
  flowDesc: '应用中内容制作的完整流程',
  flowSteps: [
    { num: '步骤 1', title: '拍摄 & AI 分析', desc: 'AI 识别产品。多角度、AR、OCR 均可用' },
    { num: '步骤 2', title: '匹配 & 链接', desc: '在 Naver/Coupang/Amazon 找到产品并生成佣金链接' },
    { num: '步骤 3', title: '卡片 & 模板', desc: '制作带贴纸的卡片。AI 图像、虚拟试穿、去背景' },
    { num: '步骤 4', title: '轮播 & 视频', desc: '将卡片转为轮播或视频。混合模式、视频导入' },
    { num: '步骤 5', title: '漫画内容', desc: 'AI 生成漫画。5 种画风、AI 配音、声效、连载模式' },
    { num: '步骤 6', title: '分享 & 收益', desc: '分享到 Instagram/TikTok/KakaoTalk。QR、link-in-bio 用于线下' },
    { num: '步骤 7', title: '营销自动化', desc: '智能调度、天气/库存提醒实现及时营销' },
    { num: '步骤 8', title: '成长', desc: '任务、排行榜、等级。账号安全、独创性分数' },
  ],
  featuresTitle: '功能介绍',
  featuresDesc: '按类别的全部功能',
  featureSections: en.featureSections,
  usageTitle: '内容制作指南',
  usageDesc: '点击各功能查看详细使用方法',
  usageSections: en.usageSections,
  automationTitle: '营销自动化指南',
  automationDesc: '营销标签中的自动化工具',
  automationSections: en.automationSections,
  monetizationTitle: '联盟 & 变现指南',
  monetizationDesc: '资产标签和结果页面中的变现工具',
  monetizationSections: en.monetizationSections,
  growthTitle: '成长指南',
  growthDesc: '成长和保护账号的工具',
  growthSections: en.growthSections,
  platformTitle: '各平台上传指南',
  platformDesc: '逐步说明如何上传视频到各平台',
  platformSections: en.platformSections,
  soundTitle: '声效指南',
  soundDesc: '录制音效并添加到漫画短频中',
  soundSections: en.soundSections,
  helpTitle: '帮助',
  helpItems: en.helpItems,
  feedbackTitle: '反馈 & 错误报告',
  feedbackDesc: '请告诉我们不便或错误。',
  feedbackItems: en.feedbackItems,
  footer: 'ShortConnect — 面向线上线下卖家的一站式 AI 电商',
  onboardingTitle: '重新查看应用导览',
  onboardingDesc: '点击重新查看初始指南',
};

export const guideTranslations: Partial<Record<AppLanguage, GuideContent>> = {
  ko,
  en,
  ja,
  vi,
  es,
  zh,
};

export function getGuideContent(lang: AppLanguage): GuideContent {
  return guideTranslations[lang] ?? guideTranslations.en ?? ko;
}
