/*
# Create saved_assets table with upload status tracking

1. New Tables
- `saved_assets`: Stores user's saved creative content (images, videos) generated by the app.
  - `id` (uuid, primary key)
  - `scan_id` (uuid, nullable, references scans)
  - `asset_type` (text: 'image' or 'video')
  - `title` (text, name of the asset)
  - `file_url` (text, URL to the stored file)
  - `file_name` (text, original filename)
  - `file_size` (integer, nullable, size in bytes)
  - `mime_type` (text, nullable)
  - `thumbnail_url` (text, nullable, thumbnail for videos)
  - `platform` (text, nullable, target platform)
  - `affiliate_platform` (text, nullable)
  - `upload_status` (text: 'not_uploaded', 'uploaded', 'scheduled'; default 'not_uploaded')
  - `share_url` (text, nullable, URL where content was published)
  - `created_at` (timestamptz, default now())

2. Security
- Enable RLS on saved_assets.
- Policies for anon + authenticated CRUD (single-tenant app, no sign-in required).

3. Notes
- This table was referenced in code but didn't exist in the database yet.
- `upload_status` tracks publishing state: not yet uploaded, uploaded, or scheduled.
- `share_url` stores the link to the published content on the target platform.
*/

CREATE TABLE IF NOT EXISTS saved_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scan_id uuid REFERENCES scans(id) ON DELETE SET NULL,
  asset_type text NOT NULL DEFAULT 'image',
  title text NOT NULL DEFAULT '',
  file_url text NOT NULL,
  file_name text NOT NULL DEFAULT '',
  file_size integer,
  mime_type text,
  thumbnail_url text,
  platform text,
  affiliate_platform text,
  upload_status text NOT NULL DEFAULT 'not_uploaded',
  share_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE saved_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_saved_assets" ON saved_assets;
CREATE POLICY "anon_select_saved_assets"
  ON saved_assets FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_saved_assets" ON saved_assets;
CREATE POLICY "anon_insert_saved_assets"
  ON saved_assets FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_saved_assets" ON saved_assets;
CREATE POLICY "anon_update_saved_assets"
  ON saved_assets FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_saved_assets" ON saved_assets;
CREATE POLICY "anon_delete_saved_assets"
  ON saved_assets FOR DELETE
  TO anon, authenticated USING (true);
